/**
 * UI copy for articles area. English only.
 */
export const articles = {
    // RISImportDialog
    risTitle: 'Import articles from RIS file',
    risDesc: 'Select a .ris file exported from a reference manager (Zotero, Mendeley, EndNote, etc.).',
    risNoRecords: 'No RIS records found in the file.',
    risReadError: 'Error reading RIS file',
    risFileReadFailed: 'Failed to read the file.',
    risNoImported: 'No articles were imported. Check the RIS file data.',
    risCloseConfirm: 'Closing now will cancel the import. Do you want to close?',
    risSelectFile: 'Select file',
    risRecordsFound: 'record(s) found. Preview:',
    risNoTitle: 'No title',
    risImportCount: 'Import',
    risImporting: 'Importing…',
    risSuccessCount: 'article(s) imported successfully.',
    risFailCount: 'record(s) could not be imported. Check the console.',
    // AddArticleDialog / ArticleForm shared
    addArticle: 'Add article',
    addArticleDesc: 'Fill in the article bibliographic information',
    titleRequired: 'Title *',
    titlePlaceholder: 'Article title',
    abstract: 'Abstract',
    abstractPlaceholder: 'Article abstract or summary',
    authors: 'Authors (comma-separated)',
    authorsPlaceholder: 'Silva A, Santos B, Oliveira C',
    authorsPlaceholderComma: 'Separate authors with commas',
    publicationYear: 'Publication year',
    publicationMonth: 'Publication month',
    publicationDay: 'Publication day',
    monthBetween: 'Month must be between 1 and 12',
    dayBetween: 'Day must be between 1 and 31',
    validNumber: 'Must be a valid number',
    yearRange: 'Year must be between 1600 and 2500',
    fixDateErrors: 'Please fix the date field errors before saving',
    articleUrl: 'Article URL',
    uploadPdfOptional: 'Upload PDF (optional)',
    errorAddArticle: 'Error adding article',
    errorUploadFile: 'Error uploading file',
    errorRegisterFile: 'Error registering file',
    journalTitle: 'Journal',
    journalPlaceholder: 'Scientific journal name',
    volume: 'Volume',
    volumePlaceholder: '12',
    issue: 'Issue',
    pages: 'Pages',
    pagesPlaceholder: '1-10',
    keywords: 'Keywords (comma-separated)',
    keywordsPlaceholder: 'keyword1, keyword2',
    doi: 'DOI',
    pmid: 'PMID',
    notProvided: 'Not provided',
    saving: 'Saving…',
    createArticle: 'Create article',
    editArticle: 'Edit article',
    titleRequiredToast: 'Title is required',
    errorLoadArticle: 'Error loading article',
    errorUpdateArticle: 'Error updating article',
    errorCreateArticle: 'Error creating article',
    errorUnknown: 'Unknown error',
    articleCreatedSuccess: 'Article created successfully!',
    articleUpdatedSuccess: 'Article updated successfully!',
    errorDownloadFile: 'Error downloading file',
    errorViewPdf: 'Error viewing PDF. Try downloading instead.',
    errorRemoveFile: 'Error removing file',
    fileRemovedSuccess: 'File removed successfully!',
    addFiles: 'Add files',
    addFilesHint: 'Click "Add files" to get started',
    articleFiles: 'Article files',
    articleFilesDesc: 'PDFs and other documents',
    delete: 'Delete',
    loadingArticle: 'Loading article…',
    formStepsAria: 'Form steps',
    basicInfo: 'Basic information',
    basicInfoDesc: 'Title, abstract and authors',
    publication: 'Publication',
    publicationDesc: 'Journal, volume and pages',
    identifiersLabel: 'Identifiers',
    identifiersDesc: 'DOI, PMID and other IDs',
    filesLabel: 'Files',
    filesDesc: 'PDFs and documents',
    additionalInfo: 'Additional information',
    additionalInfoDesc: 'Keywords and metadata',
    publicationDetails: 'Publication details',
    publicationDetailsDesc: 'Journal, volume and pages information',
    titleAbstractAuthors: 'Title, abstract and author information',
    keywordsAndMetadata: 'Keywords, metadata and other information',
    keywordsLabel: 'Keywords',
    meshPlaceholder: 'MeSH terms separated by comma',
    languagePlaceholder: 'Portuguese, English, etc.',
    typePlaceholder: 'Original article, Review, etc.',
    confirmRemove: 'Confirm removal',
    confirmRemoveDesc: 'This action cannot be undone.',
    confirmRemoveFile: 'Are you sure you want to remove the file',
    noFilesLinked: 'No files linked to this article',
    removing: 'Removing…',
    remove: 'Remove',
    downloadFile: 'Download file',
    removeFile: 'Remove file',
    noFilesAddedYet: 'No files added yet',
    notSpecified: 'Not specified',
    addFirstFile: 'Add first file',
    addFile: 'Add file',
    edition: 'Edition',
    // ArticleFileUploadDialogNew
    addFilesToArticle: 'Add files to article',
    supplementalHint: 'Select "Supplemental material" or another role for the new files.',
    alreadyExists: '(already exists)',
    errors: 'Errors',
    statusCompleted: 'Completed',
    statusError: 'Error',
    statusPending: 'Pending',
    authRequired: 'You need to be authenticated',
    mainExists: 'A main file already exists. Remove it first or choose another role',
    invalidFile: 'Invalid file',
    mainExistsError: 'A main file already exists for this article',
    uploadError: 'Upload error',
    registerError: 'Error registering file',
    uploadFilesError: 'Error uploading files',
    uploadSelectAtLeastOne: 'Select at least one file',
    uploadOnlyOneMain: 'Only one file can be marked as main',
    uploadCancelConfirm: 'Uploads in progress. Do you really want to cancel?',
    uploadMainFileExists: 'Main file already exists:',
    uploadDragFilesHere: 'Drag files here',
    uploadOrClickToSelect: 'or click to select multiple files',
    uploadDragOrClickDesc: 'Drag files or click to select. You can set the role of each file individually.',
    uploadSelectFiles: 'Select Files',
    uploadMaxPerFile: 'Max {{n}}MB per file',
    uploadFormats: 'Formats:',
    uploadFormatsShort: '.pdf, .doc, .docx, .txt, .csv, .xls, .xlsx, images',
    uploadFilesSelected: 'Selected Files',
    uploadRoleLabel: 'Role:',
    uploadTotal: 'Total',
    uploadReady: 'Ready',
    uploadPending: 'Pending',
    uploadUploadingFiles: 'Uploading Files',
    uploadUploading: 'Uploading…',
    uploadSuccessCount: '{{n}} file(s) uploaded successfully!',
    uploadPartialCount: '{{completed}} file(s) uploaded, but {{failed}} failed. Check errors above.',
    // ZoteroImportDialog
    zoteroTitle: 'Import from Zotero',
    zoteroSelectCollection: 'Select a collection to import',
    zoteroConfigureOptions: 'Configure import options',
    zoteroImportingArticles: 'Importing articles…',
    zoteroUpdated: 'Updated',
    zoteroSkipped: 'Skipped',
    zoteroImportInProgress: 'Import in progress',
    zoteroCloseConfirmTitle: 'Import in progress',
    zoteroCloseConfirmDesc: 'The import is still running. You can minimize the dialog and it will continue in the background, or cancel to stop the process.',
    zoteroContinueInBackground: 'Continue in background',
    zoteroImportTagsAsKeywords: 'Import tags as keywords',
    zoteroErrors: 'Errors',
    zoteroCancelImport: 'Cancel import',
    zoteroImportContinuing: 'Import continuing in background. You will be notified when it completes.',
    zoteroImportError: 'Import error',
    zoteroNoCollectionsFound: 'No collections found in your Zotero library.',
    zoteroStep2Desc: 'Configure how articles should be imported.',
    zoteroUpdateExisting: 'Update existing articles',
    zoteroUpdateExistingDesc: 'If an article with the same DOI already exists, update its metadata',
    zoteroTagsAsKeywordsDesc: 'Zotero tags will be imported as article keywords',
    zoteroBack: 'Back',
    zoteroNext: 'Next',
    zoteroDownloadPdfs: 'Download PDFs automatically',
    zoteroDownloadPdfsDesc: 'Download PDFs and attachments from Zotero. The first PDF will be the main file (MAIN).',
    zoteroOnlyPdfs: 'Download PDFs only',
    zoteroOnlyPdfsDesc: 'If disabled, also downloads HTML snapshots and other attachments',
    zoteroMinimize: 'Minimize',
    zoteroClose: 'Close',
    zoteroImporting: 'Importing…',
    zoteroStartImport: 'Start import',
    zoteroImported: 'Imported',
    fileWithoutName: 'Unnamed file',
    // ArticlesList
    listNoArticlesYet: 'No articles yet',
    listStartByImporting: 'Start by importing your research articles to organize your review.',
    listAddFirstArticle: 'Add first article',
    listImportFromRis: 'Import from RIS file',
    listFromZotero: 'From Zotero',
    listImportArticles: 'Import articles',
    listNoMatchSearch: 'No articles match your search',
    listAdjustSearchOrClearFilters: 'Try adjusting your search terms or clearing the active filters.',
    listClearAllFiltersButton: 'Clear all filters',
    listConfirmDelete: 'Confirm delete',
    listConfirmDeleteDesc: 'Are you sure you want to delete this article? This action cannot be undone. All linked PDF files will also be removed.',
    listConfirmBulkDelete: 'Confirm bulk delete',
    listConfirmBulkDeleteDesc: 'Are you sure you want to delete {{n}} selected article(s)? This action cannot be undone. All linked PDF files will also be removed.',
    listCancel: 'Cancel',
    listDeleting: 'Deleting…',
    listDelete: 'Delete',
    listDeleteCount: 'Delete {{n}} article(s)',
    listArticleDeletedSuccess: 'Article deleted successfully!',
    listErrorDeletingArticle: 'Error deleting article',
    listErrorDeletingArticles: 'Error deleting article(s)',
    listPdfNotFound: 'PDF file not found',
    listErrorAccessingPdf: 'Error accessing PDF file',
    listErrorOpeningPdf: 'Error opening PDF',
    listAddPdf: 'Add PDF',
    listUntitled: 'Untitled',
    listOfArticles: 'of',
    listArticle: 'article',
    listArticles: 'articles',
    listSelected: 'selected',
    listClearAll: 'Clear all',
    listSearchTitlePlaceholder: 'Search title…',
    listSearchAuthorPlaceholder: 'Search author…',
    listSearchJournalPlaceholder: 'Search journal…',
    listSearchKeywordPlaceholder: 'Search keyword…',
    listMatchesTextInTitle: 'Matches text in title.',
    listSuggestions: 'Suggestions',
    listYearFilterHint: 'Min and max year (inclusive). Leave one empty for no bound.',
    listFromYear: 'From year',
    listToYear: 'To year',
    listAny: 'Any',
    listSingleYear: 'Single year',
    listQuick: 'Quick',
    listBeforeYear: 'Before {{year}}',
    listAfterYear: 'After {{year}}',
    listHasPdf: 'Has PDF',
    listNoPdf: 'No PDF',
    listAddFilter: 'Add filter…',
    listSelectFilterAbove: 'Select a filter above.',
    listDisplayOptions: 'Display options',
    listDisplayAndSort: 'Display & sort',
    listOrdering: 'Ordering',
    listDisplayProperties: 'Display properties',
    listRemoveFilter: 'Remove filter {{label}}',
    listFilterBy: 'Filter by {{label}}',
    listSelectAll: 'Select all',
    listResizeColumn: 'Resize column',
    listSelectArticle: 'Select {{title}}',
    listAuthorsLabel: 'Authors:',
} as const;

export type ArticlesCopy = typeof articles;
