/**
 * UI copy for assessment area. English only.
 */
export const assessment = {
    headerAssessmentComplete: 'Assessment complete',
    headerItemsRemaining: 'item(s) remaining',
    headerSaving: 'Saving…',
    headerSaved: 'Saved',
    headerLastUpdate: 'Last update',
    // Header Finalize / Navigation / PDF
    headerCompleteRequired: 'Complete all required items',
    headerWaitSave: 'Wait for auto-save to finish',
    headerFinalizing: 'Finalizing…',
    headerFinalizeSubmit: 'Finalize and submit assessment',
    headerCompleteAssessment: 'Complete Assessment',
    headerBack: 'Back',
    headerArticlePrevious: 'Previous article',
    headerArticleNext: 'Next article',
    headerPdfHide: 'Hide PDF',
    headerPdfShow: 'Show PDF',
    headerCompare: 'Compare',
    headerHideComparison: 'Hide comparison',
    headerCompareWithOthers: 'Compare with others',
    headerArticles: 'Articles',
    headerUndo: 'Undo',
    headerRedo: 'Redo',
    headerExportData: 'Export data',
    // InstrumentManager
    instrumentManagerTitle: 'Assessment Instruments',
    instrumentManagerDesc: 'Configure the quality assessment instrument for this project',
    instrumentConfigured: 'Instrument configured',
    instrumentNoneConfigured: 'No instrument configured. Select an instrument below to get started.',
    instrumentCloneSuccess: 'Instrument cloned successfully!',
    instrumentCloneError: 'Error cloning instrument',
    instrumentBack: 'Back',
    instrumentProjectInstruments: 'Project instruments',
    instrumentActive: 'Active',
    instrumentItemsCount: 'assessment items',
    instrumentPerModel: 'Per model',
    instrumentPerArticle: 'Per article',
    instrumentConfigure: 'Configure',
    instrumentAvailableToImport: 'Instruments available to import',
    instrumentErrorLoad: 'Error loading instruments',
    instrumentNoGlobalAvailable: 'No global instruments available.',
    instrumentErrorUnknown: 'Unknown error',
    instrumentSelectorLabel: 'Assessment Instrument',
    instrumentSelectorPlaceholder: 'Select an instrument',
    errors_entityTypeNotConfigured: 'Entity type not configured for instance-based assessment',
    errors_loadAssessment: 'Error loading assessment',
    errors_updateAssessment: 'Error updating assessment',
    errors_createAssessment: 'Error creating assessment',
    errors_loadResponses: 'Error loading responses',
    errors_saveResponses: 'Error saving responses',
    errors_createResponse: 'Error creating response',
    errors_createResponsesBatch: 'Error creating responses in batch',
    errors_updateResponse: 'Error updating response',
    errors_deleteResponse: 'Error deleting response',
    responsesCreatedCount: '{{n}} response(s) created',
    errors_loadBlindMode: 'Error loading blind mode',
    errors_autoSaveFailed: 'Error saving data automatically',
    errors_batchAssessment: 'Error in batch assessment',
    errors_assessment: 'Assessment error',
    errors_assessmentAuth: 'Authentication error',
    errors_assessmentOpenAI: 'OpenAI API error',
    errors_loadData: 'Error loading data',
    errors_assessItem: 'Error assessing item',
    errors_assessBatch: 'Error assessing in batch',
    errors_loadSuggestions: 'Error loading suggestions',
    errors_getHistory: 'Error fetching history',
    errors_updateSuggestion: 'Error updating suggestion',
    errors_removeResponse: 'Error removing response',
    errors_acceptSuggestion: 'Error accepting suggestion',
    errors_rejectSuggestion: 'Error rejecting suggestion',
    errors_configNotFoundUpdate: 'No configuration found to update',
    errors_configNotFoundDelete: 'No configuration found to delete',
    errors_saveConfig: 'Error saving configuration',
    errors_updateConfig: 'Error updating configuration',
    errors_deleteConfig: 'Error deleting configuration',
    errors_promptConfigNotFoundUpdate: 'No prompt configuration found to update',
    errors_promptConfigNotFoundDelete: 'No prompt configuration found to delete',
    errors_savePromptConfig: 'Error saving prompt configuration',
    errors_updatePromptConfig: 'Error updating prompt configuration',
    errors_deletePromptConfig: 'Error deleting prompt configuration',
    errors_resetPromptConfig: 'Error resetting to defaults',
    errors_onlyManagersCanToggleBlind: 'Only managers can change blind mode',
    assessmentPdfNotFoundDesc: 'PDF not found. Make sure the article has a PDF file attached.',
    assessmentAuthDesc: 'Please sign in again.',
    assessmentOpenAIDesc: 'Check your OpenAI API key or use the key provided by the project.',
    assessmentBatchPartialSuccess: 'Batch assessment completed with {{n}} failure(s)',
    assessmentBatchPartialDesc: '{{success}} of {{total}} items assessed successfully',
    assessmentBatchSuccess: 'Batch assessment completed! {{n}} suggestions created',
    assessmentItemSuccess: 'Assessment completed! Suggestion created: {{level}}',
    toastSuggestionAccepted: 'Suggestion accepted successfully',
    toastSuggestionRejected: 'Suggestion rejected',
    noItemsInDomain: 'No items in this domain',
    batchAllItemsHaveResponses: 'All items already have responses. No assessment needed.',
    batchAcceptSuccessToast: '{{n}} suggestion(s) accepted automatically',
    noSuggestionThresholdToast: 'No suggestions met the confidence threshold',
    assessmentItemConfidence: 'Confidence: {{n}}% • {{tokens}} tokens used',
    // Clone/Import dialog
    instrumentCloneDialogTitle: 'Import Instrument',
    instrumentCloneDialogDesc: 'Import this instrument into your project. You can customize items after importing.',
    instrumentCloneCustomNameLabel: 'Custom name (optional)',
    instrumentCloneCustomNameHint: 'Leave blank to use the original name',
    instrumentCloneImporting: 'Importing…',
    instrumentImport: 'Import',
    instrumentImported: 'Imported',
    instrumentItemsLabel: 'items',
    instrumentDomainsLabel: 'domains',
    // AddItemDialog
    addItemTitle: 'Add Item',
    addItemDesc: 'Create a new assessment item for the instrument.',
    addItemDomainRequired: 'Domain is required',
    addItemCodeRequired: 'Code is required',
    addItemCodeMax: 'Code must be at most 50 characters',
    addItemQuestionRequired: 'Question is required',
    addItemQuestionMax: 'Question must be at most 2000 characters',
    addItemDescriptionMax: 'Description must be at most 2000 characters',
    addItemNewDomainNameRequired: 'New domain name is required',
    addItemDomainLabel: 'Domain *',
    addItemDomainPlaceholder: 'Select domain',
    addItemNewDomainOption: 'New domain…',
    addItemNewDomainLabel: 'New Domain Name *',
    addItemNewDomainPlaceholder: 'e.g. D5, New Domain',
    addItemCodeLabel: 'Item Code *',
    addItemCodePlaceholder: 'e.g. 1.4, C1',
    addItemCodeDesc: 'Short code to identify the item',
    addItemQuestionLabel: 'Question *',
    addItemQuestionPlaceholder: 'The assessment question the reviewer must answer',
    addItemDescriptionLabel: 'Description (optional)',
    addItemDescriptionPlaceholder: 'Additional guidance for the assessor',
    addItemAllowedLevelsLabel: 'Allowed Levels *',
    addItemAddOneLevel: 'Add at least one allowed level',
    addItemRequiredLabel: 'Required Item',
    addItemRequiredDesc: 'When enabled, this item must be answered for all articles',
    addItemAdding: 'Adding…',
    addItemSubmit: 'Add Item',
    addItemSuccess: 'Item added successfully',
    addItemError: 'Error adding item',
    addItemErrorUnknown: 'Unknown error',
    // InstrumentConfigEditor
    configEditorRequired: 'Required',
    configEditorOptional: 'Optional',
    configEditorSave: 'Save',
    configEditorTitle: 'Instrument Configuration',
    configEditorDesc: 'Configure the assessment items for',
    configEditorLoading: 'Loading configuration…',
    configEditorErrorLoad: 'Error loading instrument. Please try again.',
    configEditorNoDomain: 'No domain',
    configEditorRequiredCount: 'required',
    configEditorNoItems: 'No items configured',
    configEditorNoItemsDesc: 'This instrument has no assessment items yet.',
    configEditorQuestionLabel: 'Question',
    configEditorDescriptionLabel: 'Description',
    configEditorDescriptionPlaceholder: 'Description or guidance for the assessor',
    configEditorItemUpdated: 'Item updated successfully',
    configEditorItemUpdateError: 'Error updating item',
    configEditorItemOptional: 'Item marked as optional',
    configEditorItemRequired: 'Item marked as required',
    configEditorItemChangeError: 'Error changing item',
    configEditorItemRemoved: 'Item removed successfully',
    configEditorItemRemoveError: 'Error removing item',
    // AIPromptConfigDialog
    aiPromptSaving: 'Saving…',
    aiPromptSaveConfig: 'Save Configuration',
    aiPromptSystemLabel: 'System instruction',
    aiPromptSystemPlaceholder: 'Describe the AI role and expertise…',
    aiPromptSystemDesc: 'Defines the context and expertise of the AI for assessment',
    aiPromptUserLabel: 'User prompt template',
    aiPromptUserPlaceholder: 'Template for the specific question…',
    aiPromptVariablesTitle: 'Available variables:',
    aiPromptVarQuestion: 'The assessment item question',
    aiPromptVarLevels: 'The allowed response levels',
    aiPromptPreviewTitle: 'Final prompt preview:',
    aiPromptPreviewSystem: 'System:',
    aiPromptPreviewUser: 'User:',
    aiPromptDialogTitle: 'Configure AI prompt',
    aiPromptDialogDesc: 'Customize how the AI assesses this question',
    aiPromptTriggerTitle: 'Configure AI prompt',
    aiPromptToastSaved: 'Configuration saved',
    aiPromptToastSavedDesc: 'Prompt template updated successfully',
    aiPromptToastError: 'Error saving',
    aiPromptToastErrorDesc: 'Unknown error',
    // BlindModeToggle
    blindOnlyManagers: 'Only managers can change blind mode',
    blindEnabled: 'Blind mode enabled – reviewers cannot see other assessments',
    blindDisabled: 'Blind mode disabled – reviewers can see other assessments',
    blindErrorToggle: 'Error changing blind mode',
    blindActive: 'Blind active',
    blindInactive: 'Blind inactive',
    blindDeactivate: 'Disable blind mode',
    blindActivate: 'Enable blind mode',
    blindErrorLabel: 'Error',
    // AISuggestionEvidence
    aiEvidenceCited: 'Cited evidence',
    aiEvidencePage: 'Page',
    // AssessmentItemInput (extra)
    itemInputCommentLabel: 'Comment / justification (optional)',
    itemInputCommentPlaceholder: 'Add comments or justification for this assessment…',
    itemInputRequiredError: 'This item is required',
    // AIGlobalConfigModal / AIAssessmentConfigModal
    aiConfigToastSaved: 'Configuration saved',
    aiConfigToastSavedDesc: 'AI global configuration updated successfully',
    aiConfigToastSavedDescQuestion: 'Question "{{question}}" configuration updated',
    aiConfigSelectOneArticle: 'Select at least one article to process',
    aiConfigPerfFaster: '~{{n}}x faster',
    aiConfigPerfPerItem: '~{{s}}s per item',
    aiConfigToastError: 'Error saving',
    aiConfigToastErrorDesc: 'Unknown error',
    aiConfigToastReset: 'Configuration reset',
    aiConfigToastResetDesc: 'Settings restored to default values',
    aiConfigSelectionRequired: 'Selection required',
    aiConfigSelectOneQuestion: 'Select at least one question to assess',
    aiConfigConcurrency: 'Concurrency',
    aiConfigConcurrencyBadge: 'simultaneous requests',
    aiConfigSequential: '1 (Sequential)',
    aiConfigMaxParallel: '5 (Max parallel)',
    aiConfigConcurrencyDesc: 'Number of AI requests sent at once. Higher values may be faster but can hit API limits.',
    aiConfigDelayBatches: 'Delay between batches',
    aiConfigDelayFast: '500ms (Fast)',
    aiConfigDelaySafe: '2000ms (Safe)',
    aiConfigDelayDesc: 'Wait time between batches to avoid API rate limiting.',
    aiConfigPerfEstimate: 'Performance estimate',
    aiConfigMode: 'Mode',
    aiConfigParallel: 'Parallel',
    aiConfigSequentialMode: 'Sequential',
    aiConfigPerformance: 'Performance',
    aiConfigPendingQuestions: 'Pending questions',
    aiConfigParallelActive: 'Parallel mode active',
    aiConfigAIModel: 'AI model',
    aiConfigOptimized: 'Optimized',
    aiConfigModelCostBenefit: 'Model optimized for best cost-effectiveness',
    aiConfigTemperature: 'Temperature',
    aiConfigMaxConsistency: 'Maximum consistency',
    aiConfigOptimizedScientific: 'Configuration optimized for scientific assessments with maximum reproducibility',
    aiConfigMaxTokens: 'Max tokens',
    aiConfigTokenEconomy: '500 (Economy)',
    aiConfigTokenDetailed: '4000 (Detailed)',
    aiConfigForceRag: 'Force vector search (RAG)',
    aiConfigRagTooltip: 'Use vector search even for small PDFs (slower, more accurate)',
    aiConfigRagActive: 'Vector search enabled – better accuracy for complex documents',
    aiConfigGlobalPrompts: 'Global prompts',
    aiConfigSystemPromptLabel: 'System prompt',
    aiConfigUserPromptLabel: 'User prompt template',
    aiConfigVariables: 'Variables',
    aiConfigVariablesAvailable: 'Available variables',
    aiConfigSelectQuestion: 'Select question to configure',
    aiConfigQuestionConfig: 'Question configuration',
    aiConfigSaveQuestion: 'Save question',
    aiConfigCharacters: 'characters',
    aiConfigSaving: 'Saving…',
    aiConfigSaveSettings: 'Save settings',
    aiConfigReset: 'Reset',
    aiConfigBatchTitle: 'AI configuration for batch assessment',
    aiConfigTabSelection: 'Selection',
    aiConfigTabProcessing: 'Processing',
    aiConfigTabAI: 'AI settings',
    aiConfigTabPrompts: 'Per-question prompts',
    aiConfigSelectedArticles: 'Selected articles',
    aiConfigSelectedQuestions: 'Selected questions',
    aiConfigUnselectAll: 'Unselect all',
    aiConfigSelectAll: 'Select all',
    aiConfigSelectionSummary: 'Selection summary',
    aiConfigArticlesLabel: 'Articles',
    aiConfigQuestionsLabel: 'Questions',
    aiConfigTotalAssessments: 'Total assessments',
    aiConfigEstTime: 'Estimated time',
    aiConfigEstCost: 'Estimated cost',
    aiConfigArticleSelection: 'Article selection',
    aiConfigQuestionSelection: 'Question selection',
    aiConfigParallelProcessing: 'Parallel processing',
    aiConfigParallelTooltip: 'Process multiple questions at once for higher speed',
    aiConfigParallelDesc: 'Process multiple questions simultaneously for higher speed. Recommended for large volumes.',
    aiConfigSelectQuestionPrompt: 'Select a question to configure its prompts',
    aiConfigStarting: 'Starting…',
    aiConfigStartBatch: 'Start batch processing',
    // AssessmentHeaderAIActions
    aiSuggestionPendingSingle: 'AI suggestion pending',
    aiSuggestionPendingPlural: 'AI suggestions pending',
    // AISuggestionDisplay
    aiEvidenceClickTitle: 'Click to view justification and evidence',
    aiEvidenceClickAria: 'View suggestion justification and evidence',
    // AI suggestion history
    aiHistoryInvalidDate: 'Invalid date',
    aiHistoryTitle: 'Suggestion History',
    aiHistoryCount: 'suggestion(s) found',
    aiHistoryEmpty: 'No previous suggestions found',
    aiHistoryAccepted: 'Accepted',
    aiHistoryRejected: 'Rejected',
    aiHistoryReject: 'Reject',
    // AssessmentItemInput
    itemInputViewGuidance: 'View guidance',
    itemInputEvaluatingAI: 'Evaluating with AI…',
    itemInputAssessWithAI: 'Assess with AI',
    // AssessmentInterface tabs
    tabAssessment: 'Assessment',
    tabDashboard: 'Dashboard',
    tabConfiguration: 'Configuration',
    // AssessmentInterface dashboard
    dashboardArticles: 'Articles',
    dashboardInProject: 'in project',
    dashboardCompleted: 'Completed Assessments',
    dashboardAssessed: 'articles assessed',
    dashboardOverallProgress: 'Overall Progress',
    dashboardAverageCompleteness: 'average completeness',
    dashboardNoInstrument: 'No instrument configured',
    dashboardNoInstrumentDesc: 'Configure an assessment instrument in the project settings.',
    // AssessmentInterface configuration panel
    configInstrumentsTitle: 'Instrument Configuration',
    configInstrumentsDesc: 'Manage assessment instruments for the project',
    // Loading
    loadingInstruments: 'Loading instruments',
    // Errors
    errorLoadArticles: 'Error loading articles',
    // ConfigureInstrumentFirst
    configInstrumentFirstTitle: 'Configure the Assessment Instrument',
    configInstrumentFirstDesc: 'To start assessing study quality, first configure an assessment instrument for this project.',
    configInstrumentsAvailable: 'Available instruments:',
    configInstrumentButton: 'Configure Instrument',
    // ArticleAssessmentTable
    tableErrorLoad: 'Error loading articles',
    tableTryAgain: 'Try again',
    tableNoArticlesInProject: 'No articles found in this project',
    tableNoArticlesDesc: 'Add articles first to start assessments.',
    tableSearchPlaceholder: 'Search all fields…',
    tableArticlesCount: 'articles',
    tableColumnTitle: 'Title',
    tableColumnAuthors: 'Authors',
    tableColumnYear: 'Year',
    tableColumnProgress: 'Progress',
    tableColumnStatus: 'Status',
    tableActions: 'Actions',
    tableNotStarted: 'Not started',
    tableStart: 'Start',
    tableView: 'View',
    tableContinue: 'Continue',
    tableNoArticlesFilter: 'No articles found',
    tableAdjustFilters: 'Try adjusting your search filters.',
    tableClearFilters: 'Clear filters',
    tableFilterStatusPlaceholder: 'Select status…',
    tableFilterTitlePlaceholder: 'Search title…',
    tableFilterYearPlaceholder: 'e.g. 2023, 2020-2024…',
    tableFilterProgressPlaceholder: 'e.g. complete, in progress, 50…',
    tableFilterAuthorsPlaceholder: 'Search author…',
    tableFilterSearchPlaceholder: 'Search…',
    tableFilterLabel: 'Filter',
    tableFilterClear: 'Clear',
    statusAll: 'All statuses',
    // useAssessmentInstances toasts
    instanceLoadError: 'Error loading assessment instances',
    instanceCreateSuccess: 'Assessment instance created successfully',
    instanceCreateError: 'Error creating assessment instance',
    instanceUpdateError: 'Error updating instance',
    instanceUpdateSuccess: 'Instance updated',
    instanceDeleteError: 'Error deleting instance',
    instanceDeleteSuccess: 'Instance deleted',
    instanceFetchError: 'Error fetching instance',
    instanceFetchChildrenError: 'Error fetching child instances',
    statusNotStarted: 'Not started',
    statusInProgress: 'In progress',
    statusComplete: 'Complete',
    filterColumnField: 'Field',
    statusCompleteLabel: 'Complete',
    loadingConfig: 'Loading settings…',
    noDomainFound: 'No domains found in this assessment instrument',
    errorCalculatingProgress: 'Error calculating progress',
    batchAcceptError: 'Batch accept error',
    statusReviewed: 'Reviewed',
    statusLocked: 'Locked',
    statusArchived: 'Archived',
    statusInProgressLabel: 'In progress',
    progressLabel: 'Progress',
} as const;

export type AssessmentCopy = typeof assessment;
