/**
 * Shared UI copy (English) used across areas.
 * Per data-model: common namespace; error messages under errors.*
 */
export const common = {
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading…',
    error: 'Error',
    success: 'Success',
    close: 'Close',
    confirm: 'Confirm',
    delete: 'Delete',
    attention: 'Attention',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    search: 'Search',
    filterBy: 'Filter by',
    of: 'of',
    errors_notFound: 'Not found',
    errors_unauthorized: 'Unauthorized',
    errors_forbidden: 'Access denied',
    errors_serverError: 'Something went wrong. Please try again.',
    errors_networkError: 'Network error. Check your connection.',
    errors_useProject: 'useProject must be used within a ProjectProvider',
    errors_authRequired: 'Authentication required',
    errors_requestExpired: 'Request timed out. Please try again.',
    errors_connectionError: 'Connection error. Check your internet.',
    errors_unknownError: 'Unknown error',
    timeJustNow: 'just now',
    timeAgoMin: '{{n}} min ago',
    timeAgoH: '{{n}}h ago',
    timeAgoD: '{{n}}d ago',
    errorContextApp: 'Main application',
    errorContextAuth: 'Authentication',
    errorContextDashboard: 'Dashboard',
    errorContextProjectView: 'Project view',
    errorContextAssessment: 'Full assessment',
    errorContextExtraction: 'Data extraction',
    errorContextAddArticle: 'Add article',
    errorContextEditArticle: 'Edit article',
    errorContextUserSettings: 'User settings',
    errors_userNotAuthenticated: 'User not authenticated',
    errors_templateNotFound: 'Global template not found',
    errors_loadProfileFailed: 'Error loading user profile',
    errors_inContext: 'Error in {{context}}',
    errorBoundaryTitle: 'Something went wrong',
    errorBoundaryDescContext: 'An unexpected error occurred in {{context}}.',
    errorBoundaryDescApp: 'An unexpected error occurred in the application.',
    errorBoundaryToastTitle: 'Unexpected error',
    errorBoundaryToastContext: ' in {{context}}',
    errorBoundaryToastDesc: 'Details have been recorded. Try reloading the page.',
    errorBoundaryTechnicalDetails: 'Technical details',
    errorBoundaryErrorLabel: 'Error:',
    errorBoundaryErrorIdLabel: 'Error ID:',
    errorBoundaryTryAgain: 'Try again',
    errorBoundaryReloadPage: 'Reload page',
    errorBoundaryGoHome: 'Back to home',
    errorBoundarySupportMessage: 'If the problem persists, contact support.',
    errorBoundaryErrorIdFooter: 'Error ID:',
    userRoleAria: 'User role: {{role}}',
    roleManager: 'Manager',
    roleConsensus: 'Consensus',
    roleReviewer: 'Reviewer',
    roleViewer: 'Viewer',
    // Generic error toasts (hooks/services)
    errors_loadFailed: 'Error loading',
    errors_saveFailed: 'Error saving',
    errors_sendFeedbackFailed: 'Error sending feedback',
    feedbackSuccessTitle: 'Feedback sent successfully!',
    feedbackSuccessDesc: 'Thank you for your feedback. We will review it shortly.',
    feedbackDescriptionMinLength: 'Description must be at least 10 characters',
    errors_userNotProjectMember: 'User is not a project member',
    errors_invalidRole: 'Invalid role',
    errors_loadPermissions: 'Error loading permissions',
    errors_loadProject: 'Error loading project',
    pdfNotLinked: 'PDF not linked',
    pdfLoadError: 'Error loading PDF',
    pdfNotLinkedDesc: 'This article does not have a main PDF linked yet.',
    pdfLoadErrorDesc: 'Could not load the document. Please try again.',
    linkPdf: 'Link PDF',
    tryAgain: 'Try again',
    typeHere: 'Type here',
    addItemPlaceholder: 'Add item…',
    otherSpecify: 'Other (specify)',
    remove: 'Remove',
    removeAria: 'Remove {{name}}',
    loadingEllipsis: 'Loading…',
    unknownError: 'Unknown error',
    loadingPdf: 'Loading PDF…',
} as const;

export type CommonCopy = typeof common;
