/**
 * UI copy for extraction area. English only.
 */
export const extraction = {
    // HeaderPDFControls
    // HeaderNavigation
    back: 'Back',
    // ConfigureTemplateFirst
    configTemplateFirstTitle: 'Configure the template first',
    configTemplateFirstDesc: 'You need to configure the variables that will be extracted from articles. Go to the Configuration tab and choose:',
    configImportCharms: 'Import CHARMS template',
    configImportCharmsDesc: 'Use the official checklist for predictive model reviews',
    configCreateCustom: 'Create custom sections',
    configCreateCustomDesc: 'Define your own extraction variables',
    configGoToConfig: 'Go to Configuration',
    // ExtractionInterface tabs
    tabWorklist: 'Worklist',
    tabDashboard: 'Dashboard',
    tabConfiguration: 'Configuration',
    // ExtractionInterface dashboard
    dashboardArticles: 'Articles',
    dashboardInProject: 'in project',
    dashboardExtractionsStarted: 'Extractions Started',
    // Dense stat strip + completeness distribution bar
    dashboardStatInExtraction: 'In extraction',
    dashboardStatCompleted: 'Completed',
    dashboardStatAvgCompleteness: 'Avg. completeness',
    dashboardDistributionTitle: 'Completeness distribution',
    dashboardBucketNotStarted: 'Not started',
    dashboardBucketInProgress: 'In progress',
    dashboardBucketComplete: 'Complete',
    dashboardConfigureTitle: 'Configure your extraction template',
    dashboardConfigureDesc: 'To start extracting data, you need to configure the variables that will be collected.',
    dashboardYouCan: 'You can:',
    dashboardImportCharmsOption: 'Import the CHARMS template (official checklist)',
    dashboardCreateSectionsOption: 'Create your own sections and custom fields',
    dashboardConfigureButton: 'Configure',
    // ExtractionInterface configuration
    configPanelTitle: 'Configure your extraction template',
    configPanelDesc: 'Choose how you want to structure data extraction from articles',
    configCreateCustomTitle: 'Create Custom Template',
    configCreateCustomFullDesc: 'Define your own extraction sections and fields. Ideal for reviews with specific needs or different frameworks.',
    configCreateTemplateButton: 'Create Template',
    // The catalogue table moved into the import dialog; this card is
    // now the only entry point to it (spec 2026-08-27, slice A).
    configImportCardTitle: 'Import a template',
    configImportCardDesc: 'Start from a ready-made framework, or import a JSON file you or an AI assistant prepared.',
    configImportCardButton: 'Import template',
    configManagersNote: 'Managers can configure templates',
    configManagersNoteDesc: 'If you are not a project manager, ask a manager to configure the extraction template before you start.',
    configContactManagerToConfigure: 'Only project managers can configure the extraction template. Contact the project manager to set up templates and start extracting.',
    configImportTemplateButton: 'Import Template',
    configHeaderTitle: 'Template configuration',
    configPublishButton: 'Publish',
    configPublishTooltip:
      'Publish these configuration changes so reviewers and AI runs see them',
    configUnpublishedChanges: 'Unpublished changes',
    configPublishedVersion: 'Published · v{{n}}',
    configPublishSuccess: 'Published v{{n}}',
    configSectionsCountOne: '{{n}} section · {{main}} main',
    configSectionsCountOther: '{{n}} sections · {{main}} main',
    // ExtractionInterface loading & error
    loadingTemplates: 'Loading templates',
    errorLoadTemplates: 'Error loading templates',
    errorLoadArticles: 'Error loading articles',
    errors_autoSaveFailed: 'Error saving data automatically',
    errors_advanceFailed: 'Could not advance the extraction stage',
    errors_markReadyFailed: 'Could not update your ready signal',
    // useSectionExtraction toasts
    sectionExtractionNoSuggestionsTitle: 'Extraction completed with no suggestions',
    sectionExtractionNoSuggestionsDesc: 'Extraction finished but no suggestions were created. Check that field names match exactly or that the PDF contains the expected data.',
    sectionExtractionSuccessTitle: 'Extraction completed! {{n}} suggestion(s) created for this section.',
    sectionExtractionErrorTitle: 'Extraction error',
    sectionExtractionErrorAuth: 'Authentication error',
    sectionExtractionErrorAuthDesc: 'Please sign in again.',
    // FullAIExtractionProgress
    fullAIProgressTitle: 'Full AI Extraction',
    fullAIProgressInProgress: 'AI extraction in progress…',
    fullAIProgressExtractingModels: 'Extracting models from article with AI…',
    fullAIProgressExtractingSections: 'Extracting top-level sections: {{label}}',
    fullAIProgressExtractingAllSections: 'Extracting sections from all models…',
    fullAIProgressRestore: 'Restore',
    fullAIProgressClose: 'Close',
    fullAIProgressMinimize: 'Minimize',
    // BatchExtractionProgress
    batchExtractingAllSections: 'Extracting all sections of the model',
    batchChunkOf: 'Chunk {{current}} of {{total}}',
    batchSectionsOf: 'Sections: {{completed}} of {{total}}',
    batchProcessing: 'Processing: {{name}}…',
    // Field/template management toasts
    errors_addField: 'Error adding field',
    errors_updateField: 'Error updating field',
    errors_removeField: 'Error removing field',
    errors_deleteFieldInUse:
      'This field cannot be deleted: extraction work (proposals, decisions, or published values) already references it.',
    errors_cloneTemplate: 'Error cloning template',
    errors_republishTemplate:
      'Publishing failed — your changes are still saved as a draft. Try Publish again.',
    errors_updateTemplateStatus: 'Error updating status',
    templateClonedSuccess: 'Template "{{name}}" cloned successfully!',
    templateActivatedSuccess: 'Template activated successfully!',
    templateDeactivatedSuccess: 'Template deactivated successfully!',
    errors_loadSuggestions: 'Error loading suggestions',
    errors_batchAcceptSuggestions: 'Error accepting suggestions in batch',
    noSectionsForModel: 'No sections found for this model',
    modelExtractionErrorTitle: 'Extraction error',
    modelExtractionAuthErrorTitle: 'Authentication error',
    noModelsExtractionComplete: 'Extraction completed but no prediction models were found in the article.',
    noModelsToExtractSections: 'No models to extract sections from. Extract models first.',
    extractionMayTakeMinutes: 'This may take a few minutes',
    fullAICompleteSuccessTitle: 'Full AI extraction complete!',
    fullAISuccessDescription: '{{n}} model(s) processed with all sections extracted.',
    fullAITopLevelSections: '{{n}} top-level section(s) extracted.',
    fullAIPartialTitle: 'Extraction partially complete',
    fullAIPartialTopLevelFailed: 'Prediction models were extracted, but study-level sections failed and were not saved. Re-run extraction to retry them.',
    fullAIErrorPrefix: 'Error in full AI extraction',
    modelExtractionSuccessTitle: 'Extraction complete! {{n}} model(s) found and created.',
    modelExtractionSuccessTokens: '{{n}} tokens used',
    noModelsFoundTitle: 'No models found',
    errors_loadExtractionData: 'Error loading data',
    errors_loadExtractedValues: 'Error loading extracted values',
    labelUpdatedSuccess: 'Label updated successfully',
    instanceRemoveAction: 'Remove "{{label}}"',
    instanceRenameAction: 'Rename "{{label}}"',
    // Entry dialogs (every repeating section is an entry group). The key
    // field's label is data; `{{key}}` carries it lower-cased into copy.
    entryLabelField: 'Label',
    entryKeyHint:
      'Identity for AI re-runs: a re-run that finds this {{key}} updates this {{noun}} instead of adding another.',
    entryKeyEmpty: '{{key}} cannot be empty',
    entryKeyDuplicate: 'A {{noun}} with this {{key}} already exists',
    renameEntryTitle: 'Rename {{noun}}',
    renameEntryDesc:
      'Change how this {{noun}} is shown, and what identifies it to AI re-runs.',
    entryUpdatedSuccess: '{{noun}} updated',
    errors_updateEntry: 'Error updating {{noun}}',
    saving: 'Saving…',
    processingArticle: 'Processing article {{current}}/{{total}}: {{title}}',
    zoteroImportCompletedWithErrors: 'Import completed with errors',
    modelNotAuthenticatedOrInvalid: 'User not authenticated or invalid template',
    errors_createModel: 'Error creating model',
    errors_removeModel: 'Error removing model',
    errors_topLevelSectionsExtraction: 'Error in top-level sections extraction',
    errors_sectionsExtraction: 'Error in section extraction',
    modelCreatedSuccess: 'Model "{{label}}" created successfully!',
    modelRemovedSuccess: 'Model "{{label}}" removed successfully',
    errors_zoteroFetch: 'Error fetching Zotero collections',
    errors_zoteroImport: 'Error importing articles',
    zoteroDisconnectSuccess: 'Zotero integration removed',
    zoteroDisconnectError: 'Error removing integration',
    zoteroImportCompleteSuccess: 'Import complete! {{imported}} imported, {{updated}} updated',
    zoteroImportPdfsDownloaded: ', {{n}} PDFs downloaded',
    zoteroConnectionSuccess: 'Connection successful! User: {{name}}',
    zoteroConnectionFailed: 'Failed to connect to Zotero',
    zoteroTestConnectionError: 'Error testing connection',
    zoteroCredentialsSavedSuccess: 'Credentials saved successfully!',
    zoteroCredentialsSaveError: 'Error saving credentials',
    noTopLevelSectionsFound: 'No top-level sections found to extract',
    zoteroProgressProcessing: 'Processing articles…',
    zoteroProgressProcessingCount: 'Processing {{current}}/{{total}}…',
    zoteroProgressComplete: 'Import complete!',
    zoteroProgressError: 'Import error',
    zoteroItemTitleFallback: 'No title',
    batchAcceptCountToast: '{{n}} suggestion(s) accepted in batch',
    noSuggestionConfidenceToast: 'No suggestions with confidence ≥{{pct}}%',
    errors_noPermissionAddField: 'You do not have permission to add fields',
    errors_validationPrefix: 'Validation: {{message}}',
    errors_duplicateFieldKey: 'A field with this key already exists in this section',
    errors_cannotChangeFieldType: 'Cannot change field type when it already has extracted data',
    errors_typeChangeProbeFailed: 'Could not verify the field’s extracted data — the type was not changed',
    // ExtractionErrorBoundary
    errorBoundaryTitle: 'Extraction error',
    errorBoundaryTryAgain: 'Try again',
    fieldUpdatedSuccess: 'Field updated successfully!',
    fieldRemovedSuccess: 'Field removed successfully!',
    // Article extraction list/table shared strings
    listStatusNotStarted: 'Not started',
    listStatusComplete: 'Complete',
    listStatusInProgress: 'In progress',
    statusInProgressPct: 'In progress · {{n}}%',
    listTryAgain: 'Try again',
    listNoArticles: 'No articles found in this project',
    listNoArticlesDesc: 'Add articles first to start data extraction.',
    // ArticleExtractionTable (toast)
    tableErrorLoadArticles: 'Error loading articles',
    tableSelectAtLeastOne: 'Select at least one article',
    tableErrorProcessAI: 'Error processing AI extraction',
    tableErrorUnknown: 'Unknown error',
    batchChunkedSuccessTitle: 'Extraction complete! {{n}} section(s) extracted successfully.',
    batchChunkedSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchChunkedPartialTitle: 'Extraction partially complete: {{success}}/{{total}} section(s) extracted successfully.',
    batchChunkedPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} section(s) failed. {{tokens}} tokens used.',
    topLevelSuccessTitle: 'Top-level sections extracted: {{success}}/{{total}}',
    topLevelSuccessDesc: '{{suggestions}} suggestion(s) created.',
    topLevelPartialTitle: 'Top-level extraction partially complete: {{success}}/{{total}} section(s).',
    topLevelPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} section(s) failed.',
    topLevelFailedTitle: 'Failed to extract top-level sections',
    topLevelFailedDesc: 'All {{failed}} section(s) failed.',
    batchAllModelsSuccessTitle: 'Extraction complete! Sections extracted from {{n}} model(s) successfully.',
    batchAllModelsSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchAllModelsPartialTitle: 'Extraction partially complete: {{success}}/{{total}} model(s) processed successfully.',
    batchAllModelsPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} model(s) failed. {{tokens}} tokens used.',
    zoteroImportStarting: 'Starting import…',
    zoteroImportCancelled: 'Import cancelled',
    sectionLabelLabel: 'Section label *',
    sectionDescriptionOptional: 'Description (optional)',
    sectionTypeLabel: 'Section type *',
    sectionTypeSingle: 'Single section',
    sectionTypeMultiple: 'Multiple sections',
    sectionRequiredLabel: 'Required section',
    evidenceCited: 'Cited evidence',
    pageLabel: 'Page {{n}}',
    tableNoArticles: 'No articles found',
    // CreateCustomTemplateDialog
    createTitle: 'Create Custom Template',
    createDesc: 'Create an empty template and add custom sections and fields',
    createNameLabel: 'Template Name',
    createNamePlaceholder: 'e.g. Custom Extraction - Diabetes',
    createNameDesc: 'Descriptive name to identify this template',
    createDescriptionLabel: 'Description',
    createDescriptionPlaceholder: 'Describe the purpose of this template…',
    createDescriptionDesc: 'Explain what data will be extracted and for what purpose',
    createFrameworkLabel: 'Base Framework',
    createFrameworkPlaceholder: 'Select a framework',
    createFrameworkCustom: 'Custom',
    createFrameworkCharms: 'CHARMS (customized)',
    createFrameworkPicos: 'PICOS (customized)',
    createFrameworkDesc: 'Conceptual base of the template (can be CUSTOM if fully custom)',
    createCreating: 'Creating…',
    createTemplateButton: 'Create Template',
    createSuccessCreated: 'Template created successfully!',
    createInfoAddSections: 'Now add sections and fields in the Setup tab',
    createErrorCreate: 'Error creating template',
    createValidationNameMin: 'Name must be at least 3 characters',
    createValidationNameMax: 'Name must be at most 100 characters',
    createValidationDescMax: 'Description must be at most 500 characters',
    createValidationFramework: 'Select a framework',
    // ArticleExtractionTable (columns, filters, actions)
    tableColumnTitle: 'Title',
    tableColumnYear: 'Year',
    tableColumnStatus: 'Status',
    tableColumnAuthors: 'Authors',
    tableColumnCreatedAt: 'Created at',
    tableSearchTitle: 'Search in title…',
    tableSearchAuthor: 'Search author…',
    tableSearchPlaceholderShortcut: 'Search… (⌘F / Ctrl+F)',
    tableShortcutFilter: 'Filter (F)',
    tableDisplayAndSort: 'Display & sort',
    tableOrdering: 'Ordering',
    tableDisplayOptions: 'Display options',
    tableClearAll: 'Clear all',
    tableRemoveFilter: 'Remove filter {{label}}',
    tableSelectArticleAria: 'Select article: {{title}}',
    tableOpenRowAria: 'Open extraction for {{title}}',
    tableStatusLegendAria: 'Status legend',
    tableArticlesCount: 'articles',
    tableSelectFiltered: 'Select filtered articles',
    tableSelectAll: 'Select all articles',
    tableActions: 'Actions',
    tableActionOpen: 'Open',
    tableStart: 'Start',
    tableView: 'View',
    tableContinue: 'Continue',
    tableAdjustFilters: 'Try adjusting the search filters.',
    tableClearFilters: 'Clear filters',
    tableBatchAIStarting: 'Starting AI extraction for {{count}} article(s)…',
    tableSelectedCount: '{{n}} selected',
    tableBatchActionsLabel: 'Batch actions',
    tableAIExtraction: 'AI extraction',
    // AISuggestionReviewPopover – invalid-timestamp fallback
    historyInvalidDate: 'Invalid date',
    suggestionAccepted: 'Accepted',
    suggestionRejected: 'Rejected',
    toastSuggestionAcceptedSuccess: 'Suggestion accepted successfully',
    toastSuggestionRejectedSuccess: 'Suggestion rejected',
    // FieldInput
    fieldRequired: 'Required field',
    fieldMustBeNumber: 'Value must be a number',
    valuesCommaSeparated: 'Comma-separated values',
    yes: 'Yes',
    no: 'No',
    defaultUnit: '(default)',
    // Field vocabulary shared by the grid, inspector and value editors
    otherSpecifyDefault: 'Other (specify)',
    fieldTypeBoolean: 'Yes/No',
    fieldTypeText: 'Text',
    fieldTypeNumber: 'Number',
    fieldTypeDate: 'Date',
    fieldTypeSelect: 'Selection',
    fieldTypeMultiselect: 'Multiple choice',
    actionsForFieldAria: 'Actions for field {{label}}',
    // RemoveModelDialog
    removeModelAnyway: 'Yes, remove anyway',
    removeModel: 'Remove {{noun}}',
    // AllowedUnitsList
    unitsEmptyHint: 'Leave empty to use automatic suggestions based on context, or add custom units above. The first unit will be the default.',
    // RemoveModelDialog
    removeModelTitle: 'Remove {{noun}}',
    removeModelDesc: 'You are about to remove the {{noun}} "{{name}}"',
    removeModelWarningTitle: 'Warning: This {{noun}} contains extracted data!',
    removeModelFieldFilled: 'field is filled in this {{noun}}.',
    removeModelFieldsFilled: 'fields are filled in this {{noun}}.',
    removeModelDataPermanent: 'All extracted data will be permanently removed and cannot be recovered.',
    removeModelNoData: 'This {{noun}} has no extracted data. Removal will not affect other entries or study-level sections.',
    removeModelWhatRemoved: 'What will be removed:',
    removeModelSubsections: 'All sub-sections of this {{noun}}',
    removeModelAllValues: 'All extracted values ({{count}} fields)',
    removeModelRemoving: 'Removing…',
    removeModelError: 'Error removing {{noun}}',
    noUnitsConfigured: 'No units configured',
    loadingConfiguration: 'Loading configuration…',
    noSectionsConfigured: 'No sections configured',
    noModelsAdded: 'No {{noun}} added yet',
    noModelsAddedDesc: 'Add a {{noun}} manually or extract it automatically from the article.',
    // RunHeader (extraction-specific keys — shared header keys now live in the runs namespace)
    runHeaderFinishExtraction: 'Finish extraction',
    runHeaderFinishExtractionTooltip: 'Signal that you are done extracting this article and open the next one.',
    runHeaderExtractionFinished: 'Extraction finished',
    runHeaderStartConsensus: 'Start consensus',
    runHeaderStartConsensusTooltip: 'Move this article into consensus for review and publishing.',
    runHeaderApproveFinalize: 'Approve & finalize',
    runHeaderApproveFinalizeTooltip: 'Publish every agreed value and finalize this article.',
    runHeaderApproveBlocked: 'Resolve every diverging field and fill all required fields first',
    runHeaderFinalizeTooltip: 'Lock and publish the agreed values.',
    runHeaderGateBlocked: 'Complete the required fields first',
    runHeaderCompareToggle: 'Compare reviewers',
    runHeaderReopenForRevision: 'Reopen for revision',
    runHeaderReopening: 'Reopening…',
    // Reopen consensus -> extraction (arbitrator-only, destructive). See ADR-0017.
    runHeaderReopenExtraction: 'Reopen extraction',
    reopenExtractionTitle: 'Reopen for extraction?',
    reopenExtractionBodyDiscard:
      'This discards {{count}} resolved consensus decision(s), and any evidence attached to them, and returns the article to Extraction where reviewers can edit again. This cannot be undone.',
    reopenExtractionBodyClean:
      'This returns the article to Extraction so reviewers can edit again. Nothing has been resolved yet, so nothing is discarded.',
    reopenExtractionConfirmDiscard: 'Reopen & discard',
    reopenExtractionConfirmClean: 'Reopen',
    reopenExtractionToast: 'Article reopened for extraction.',
    // Section navigation rail
    sectionNavRequiredLeft: '{{count}} required left',
    sectionNavComplete: 'All required fields complete',
    sectionNavAria: 'Section navigation',
    sectionNavJumpNext: 'Go to next unfilled',
    sectionNavJumpNextHint: 'Jump to the next required field still waiting for an answer.',
    // DeleteFieldConfirm
    deleteField: 'Delete field',
    exportButton: 'Export',
    // AddSectionDialog
    selectTypePlaceholder: 'Select type',
    placeholderSectionNameExample: 'e.g. exclusion_criteria',
    // ModelSelector / AddModelDialog
    selectModelPlaceholder: 'Select a {{noun}}…',
    modelNamePlaceholder: 'Enter a name for this {{noun}}…',
    modelDescriptionPlaceholder: 'e.g. Supervised learning, Neural network…',
    modelNameLabel: '{{noun}} name',
    modelNameHint: 'Choose a descriptive name to identify this {{noun}}',
    modellingMethodLabel: 'Modelling method',
    modellingMethodOptional: '(optional)',
    modellingMethodHint: 'You can fill this in later during extraction',
    modelSelectorTitle: '{{noun}} entries',
    modelSelectorDesc: 'Select a {{noun}} to extract its data',
    modelExtractAITitle: 'Extract {{noun}} entries automatically with AI',
    modelExtractAIShort: 'Extract with AI',
    modelExtractModelsOnly: 'Extract {{noun}} entries only',
    modelExtractAllSections: 'Extract sections from every {{noun}}',
    modelAddManuallyTitle: 'Add new {{noun}} manually',
    modelNewShort: 'New',
    modelRemoveActiveTitle: 'Remove active {{noun}}',
    modelRenameActiveTitle: 'Rename active {{noun}}',
    modelActiveLabel: 'Active {{noun}}',
    // SectionAccordion
    sectionNoInstances: 'No instances created for this section',
    sectionMultipleBadge: 'Multiple ({{count}})',
    sectionAddInstance: 'Add',
    // AllowedUnitsList
    unitMoveUp: 'Move up',
    unitMoveDown: 'Move down',
    unitRemove: 'Remove',
    // AISuggestionEvidence
    copyCopied: 'Copied!',
    copySnippet: 'Copy snippet',
    // PDF / UI aria
    removeFileAria: 'Remove file',
    placeholderTypeHere: 'Type here',
    allowOtherSpecifyLabel: 'Allow "Other (specify)"',
    otherLabelLabel: '"Other" label',
    placeholderLabel: 'Placeholder',
    fieldPlaceholderEnter: 'Enter {{label}}',
    // Impact-probe messages (delete confirm + type-change guard)
    fieldExtractedValuesMessage: 'This field has {{count}} extracted values in {{n}} article(s).',
    fieldSafeToModifyMessage: 'Field can be modified safely.',
    // Placeholders and inline UI (FieldInput, dialogs)
    selectFieldPlaceholder: 'Select {{label}}',
    addInstanceLabel: 'Add {{label}}',
    createModel: 'Create {{noun}}',
    addNewModel: 'Add new {{noun}}',
    addNewModelDesc: 'Create a new {{noun}} to extract its data. You can add as many as you need.',
    modelsAlreadyAdded: 'Already added:',
    creating: 'Creating…',
    addManually: 'Add manually',
    addSection: 'Add section',
    addNewSection: 'Add new section',
    createSection: 'Create section',
    typeAbovePressEnter: 'Type above and press Enter or click',
    dragToReorder: 'Drag to reorder',
    noOptionsAddedYet: 'No options added yet',
    complete: 'complete',
    // ExtractionExportDialog (009-extraction-excel-export)
    exportDialogTitle: 'Export to Excel',
    exportDialogSubtitle: "Export this project's recorded values as an Excel workbook (.xlsx).",
    exportSourceLabel: 'Source of values',
    exportSourceConsensus: 'Consensus',
    exportSourceSingleUser: 'Single user',
    exportSourceAllUsers: 'All users',
    exportSourceAllUsersDisabledTooltip: 'Only project managers can export all reviewers side-by-side.',
    exportReviewerLabel: 'Reviewer',
    exportReviewerSelfFallback: 'Only your own decisions are available — your role does not allow exporting other reviewers.',
    exportReviewerEmptyState: 'No reviewer has recorded decisions on this template yet, so there is nothing to export for a single user. Run extraction and review first, or pick another source.',
    exportShapeLabel: 'Sheets to include',
    exportShapeComplete: 'Complete workbook',
    exportShapeCompleteDesc: 'Every sheet — the matrix, the publication tables, the appraisal summary and the data dictionary.',
    exportShapeDictionary: 'Data dictionary only',
    exportShapeDictionaryDesc: 'The field catalogue and its dropdown lists, for wiring another tool to this template.',
    exportShapePublication: 'Publication tables',
    exportShapePublicationDesc: 'The per-section tables and the appraisal summary, ready to paste into a manuscript.',
    exportTemplatesLabel: 'Templates to export',
    exportTemplatesSingleUserHint: 'Single-user export covers one template at a time.',
    exportPartialFailureTitle: 'Some exports did not run',
    exportRateLimited: 'Too many exports in the last minute. Wait a moment, then retry.',
    exportAdditionalLabel: 'Additional content',
    exportIncludeAiMetadata: 'Include AI metadata sheet',
    exportIncludeAiMetadataDesc: 'Adds a flat sheet listing every AI proposal with confidence, rationale, evidence, and reviewer outcome.',
    exportAnonymizeReviewers: 'Anonymize reviewer names',
    exportAnonymizeReviewersDesc: 'Replace reviewer names with Reviewer A / B / … in the exported file. Useful when sharing the file outside your team.',
    exportEmptyNoArticlesReason: 'No articles in scope — adjust filters or pick a different article scope.',
    exportConfirm: 'Export',
    exportGenerating: 'Generating…',
    exportRetry: 'Retry',
    exportCancel: 'Cancel',
    exportSuccessToast: 'Export downloaded.',
    exportStartedToast: 'Export started — we will notify you when it is ready.',
    exportFailedToast: 'Export failed.',
    exportPreviewLineFmt: 'Will export {articles} articles × {fields} fields → {delivery}',
    exportPreviewLineNoFieldsFmt: 'Will export {articles} articles → {delivery}',
    exportPreviewLineDictionaryFmt: "Will export this template's field catalogue → {delivery}",
    exportPreviewDeliveryInline: 'inline download',
    exportPreviewDeliveryAsync: 'background job',
    // TemplateInspector section summary
    fieldsCountLabel: 'field(s)',
    // TemplateConfigEditor section card labels
    editLabelButton: 'Edit label',
    removeButton: 'Remove',
    // Template config grid (B-1 shell): columns, section metadata, search
    gridAria: 'Template fields',
    gridColLabel: 'Label',
    gridColType: 'Type',
    gridColRequired: 'Req.',
    gridColKey: 'Key',
    gridColOptions: 'Options',
    gridColAi: 'AI instruction',
    gridNewField: 'New field',
    gridNewSection: 'New section',
    gridSearchPlaceholder: 'Search fields…',
    gridSearchCount: '{{n}}/{{total}}',
    gridSearchClear: 'Clear search',
    gridNoMatches: 'No field matches this search.',
    gridDisplayMenu: 'Display options',
    gridOutlineToggle: 'Show or hide the section outline',
    gridOutlineResize: 'Section outline width',
    gridDisplayKeyColumn: 'Key column',
    gridDisplayOptionsColumn: 'Options column',
    gridEditLabelAria: 'Edit label',
    gridEditKeyAria: 'Edit key',
    gridRenameSectionAria: 'Rename section',
    gridNewFieldAria: 'New field label',
    gridNewFieldPlaceholder: 'Field label',
    gridRowActions: 'Field actions',
    gridEmptyTemplate: 'This template has no sections yet.',
    gridCollapseSection: 'Collapse section',
    gridExpandSection: 'Expand section',
    gridSectionActions: 'Section actions',
    // Control cells (B-5 Task 5): act on first click
    gridTypeMenuAria: 'Change type — {{label}}',
    gridRequiredToggleAria: 'Required — {{label}}',
    gridAiCellAria: 'AI instruction — {{label}}',
    gridOptionsCellAria: 'Options — {{label}}',
    sectionMetaRepeatingGroup: 'Repeating group',
    sectionMetaRepeatsPerArticle: 'repeats per article',
    sectionMetaRepeatsPerModel: 'repeats per {{noun}}', // B-8 D7: grid call site interpolates the group's entry noun
    matchHintKey: 'in key',
    matchHintDescription: 'in description',
    matchHintAiInstruction: 'in AI instruction',
    matchHintOptions: 'in options',
    // Template config inspector (B-1 shell; field form editable in place)
    inspectorEmptyTitle: 'Nothing selected',
    inspectorEmptyHint: 'Select a field or a section to see its details.',
    inspectorSectionLabel: 'Section',
    inspectorKeyLabel: 'Key',
    inspectorTypeLabel: 'Type',
    inspectorRequiredLabel: 'Required',
    inspectorRequiredYes: 'Required',
    inspectorRequiredNo: 'Optional',
    inspectorOptionsLabel: 'Options',
    inspectorAiLabel: 'AI instruction — this field',
    inspectorAiHint: 'Guides the AI on this field only.',
    inspectorAiEmpty: 'No field-level instruction.',
    inspectorDescriptionLabel: 'Description — for reviewers',
    inspectorDescriptionHint: 'Never sent to the AI.',
    inspectorDescriptionEmpty: 'No description.',
    inspectorLabelLabel: 'Label',
    inspectorSave: 'Save changes',
    inspectorReset: 'Reset',
    inspectorRequiredSwitch: 'Mark this field as required',
    inspectorKindRoot: 'Section',
    inspectorKindGroup: 'Repeating group',
    inspectorKindGroupChild: 'Per-{{noun}} section', // B-8 D7: badge call site interpolates the entry noun
    // Inspector absorption + visibility (B-5 Task 5)
    inspectorUnitsLabel: 'Units',
    inspectorUnitsHint: 'The first unit is the default reviewers see.',
    inspectorDispositionsLabel: 'Dispositions',
    inspectorTypeChangeHint: 'Changing the type of a field that already holds answers is a destructive change — you will confirm it before publishing.',
    inspectorToggle: 'Show or hide the inspector (⌘./Ctrl+.)',
    inspectorResize: 'Inspector width',
    inspectorSheetTitle: 'Field inspector',
    // TemplateInstructionControl (general AI instruction, config bar)
    instructionTitle: 'General AI instruction',
    instructionEmpty:
      'No general instruction — the AI receives only section and field instructions.',
    instructionPlaceholder:
      'Guidance sent to the AI before every section of this template…',
    instructionCustomizeChip: '{{n}} to customize',
  instructionUnsavedDraft: 'Unsaved instruction draft',
    instructionCounter: '{{n}} / 4000',
    instructionSave: 'Save',
    instructionCancel: 'Cancel',
    instructionResetDefault: 'Reset to template default',
    instructionInsertDefault: 'Insert suggested default',
    instructionSuggestedDefault:
      "You are extracting data for a systematic review. Report values exactly as stated in the article, do not infer unreported values, and quote the passage supporting each value. [customize: describe this review's scope]",
    instructionSavedToast: 'General AI instruction saved',
    errors_saveInstruction: 'Could not save the general AI instruction',
    instructionScopeHint:
      'Saved to this template draft — reaches reviewers when the template is published.',
    // Short form for the dialog's tab strip, which must fit a phone.
    instructionTabLabel: 'Instruction',
    instructionCustomizeWarning:
      '{{n}} unfilled [customize:] slot(s) — the AI receives the placeholder text as written.',
    // QualityAssessmentInterface / dashboard
    dashboardProgress: 'Progress',
    // AddSectionDialog – auto-generated technical name toggle
    autoNameLabel: 'Auto',
    autoNameAriaLabel: 'Auto-generate the technical name',
    autoNameTooltip: 'Derive the technical name from the label. Turn off to type it yourself.',
    // AddSectionDialog – validation messages
    nameRequired: 'Name is required',
    nameMin2: 'Name must be at least 2 characters',
    nameMax50: 'Name must be at most 50 characters',
    nameFormat: 'Invalid name format',
    labelRequired: 'Label is required',
    labelMin2: 'Label must be at least 2 characters',
    labelMax100: 'Label must be at most 100 characters',
    descriptionMax500: 'Description must be at most 500 characters',
    cardinalityRequired: 'Required',
    sectionCreatedSuccess: 'Section "{{label}}" created successfully',
    sectionCreateError: 'Error creating section',
    placeholderSectionLabel: 'Section label',
    placeholderSectionDescription: 'Section description',
    // AllowedUnitsList
    enterUnit: 'Enter a unit',
    unitAlreadyAdded: 'Unit already added',
    max20Units: 'At most 20 units',
    placeholderUnits: 'Enter units',
    suggestionsButton: 'Suggestions',
    searchUnit: 'Search unit',
    noUnitFound: 'No unit found',
    unitAdded: 'Added',
    // AllowedValuesList
    enterValue: 'Enter a value',
    valueAlreadyAdded: 'Value already added',
    max100Values: 'At most 100 values',
    placeholderOptions: 'Enter options',
    // SectionAccordion – AI extraction buttons
    extractSectionWithAI: 'Extract {{label}} with AI',
    extractAllSectionsWithAI: 'Extract all sections with AI',
    extractingWithAI: 'Extracting with AI…',
    extractingAllSectionsWithAI: 'Extracting all sections with AI…',
    createInstanceBeforeExtract: 'Create an instance before extracting',
    // AddModelDialog – validation & errors
    modelCreateError: 'Error creating {{noun}}',
    evidenceCitedAria: 'Cited evidence',
    // AISuggestionReviewPopover – rationale section label
    aiRationaleLabel: 'Rationale',
    // AISuggestionConfidence
    aiConfidenceTooltip: 'AI suggestion confidence level',
    // AISuggestionReviewPopover – unified version review + selection
    reviewTitle: 'Review suggestion',
    reviewVersionsCount: '{{n}} version(s)',
    reviewNoVersions: 'No AI versions yet',
    reviewHistoryError: 'Couldn’t load the version history. Close and reopen to retry.',
    reviewSelected: 'Selected',
    reviewUseThisVersion: 'Use this version',
    reviewNoInformation: 'No information found',
    reviewNoInformationDesc: 'The model reported no information for this field in the document.',
    // For a `'unmarked'` valueless proposal (see `valuelessProposalKind`).
    // Distinct from the marker copy above on purpose — where "NI" is a scale
    // answer, "No information found" would read as that answer.
    reviewNoValue: 'No value proposed',
    reviewNoValueDesc: 'The model returned no value for this field. It stays unanswered until you fill it in.',
    reviewNoValueRecorded: 'Recorded — the field stays empty.',
    reviewLowConfidence: 'low',
    reviewClear: 'Clear',
    reviewClearHint: 'Each selection is recorded with who chose it and when.',
    reviewDetails: 'Details',
    reviewOpenFromValue: 'Open review · see other versions, evidence and provenance',
    reviewPinNotInHistory: 'The adopted version is older than the loaded history.',
    // Consensus-trace attribution (D3) — pinned-row chip + cross-marks + run headers
    reviewAdoptedBy: 'Adopted by {{name}}',
    reviewEditedBy: 'Edited by {{name}}',
    reviewRunBy: 'Run by {{name}}',
    // Verified-mode verdict chip (§5) — the second pass's per-value judgement.
    // No chip = "not verified" (Fast run, degraded pass, or no-info proposal).
    verificationConfirmed: 'Verified',
    verificationUnsupported: 'Not supported',
    verificationUncertain: 'Uncertain',
    // Runtime disposition control (ADR-0016) — set a "no value, on purpose" answer
    // on any field type when the source is silent / the item does not apply.
    dispositionNoInformation: 'No information',
    dispositionNotApplicable: 'Not applicable',
    dispositionNotEvaluated: 'Not evaluated',
    // Hover descriptions — same wording as the export legend (value_semantics
    // labels ↔ extraction_export_service legend), so screen and export agree.
    dispositionNoInformationHint: 'The source does not state this item.',
    dispositionNotApplicableHint: 'The item does not apply to this study.',
    dispositionNotEvaluatedHint: 'The item was not assessed.',
    dispositionActiveHint: 'Recorded as a resolved answer.',
    // Template builder — the two opt-in disposition flags. "No information"
    // became per-field too (migration 0062) but is not edited here: it
    // defaults ON, and these templates keep it that way.
    dispositionBuilderHint: '"No information" is enabled by default and is not configured here.',
    dispositionAllowNotApplicableLabel: 'Allow "Not applicable"',
    dispositionAllowNotEvaluatedLabel: 'Allow "Not evaluated"',
    // Provenance summary + GenerationDetailsDialog – "how this was generated"
    provenanceToggle: 'How this was generated',
    provenanceRanBy: 'Ran by',
    provenanceProvider: 'Provider',
    provenanceModel: 'Model',
    provenanceReasoning: 'Reasoning',
    provenanceTemperature: 'Temperature',
    provenanceOutputRetries: 'Output retries',
    provenanceTimeout: 'Timeout',
    provenanceTokensPrompt: 'Prompt tokens',
    provenanceTokensCompletion: 'Completion tokens',
    provenanceTokens: 'Tokens',
    provenanceStrategy: 'Strategy',
    provenancePromptVersion: 'Prompt version',
    provenanceTokensSummary: '{{n}} tokens',
    provenanceCopyPrompt: 'Copy prompt',
    provenanceCopied: 'Copied!',
    // GenerationDetailsDialog – full "how this was generated" surface
    generationParamsHeading: 'Run parameters',
    generationCompositionHeading: 'Prompt composition',
    generationSystemPrompt: 'System prompt',
    generationSectionInstruction: 'Section instruction',
    generationArticleInserted: 'Full article text inserted here',
    generationArticleTokens: '{{n}} tokens',
    generationArticleTruncated: 'A budgeted subset of this text was sent',
    generationViewTextSent: 'View text sent',
    generationHideTextSent: 'Hide text sent',
    generationFieldsRequested: 'Requested fields ({{n}})',
    generationSplitCalls: 'Split across {{n}} calls',
    generationShowAll: 'Show all',
    generationShowLess: 'Show less',
    generationLegacyPrompt: 'Prompt sent',
    generationTextError: "Couldn't load the text. Retry",
    generationTextRetry: 'Retry',
    // AISuggestionEvidence – markdown-first citation locate
    evidenceLocate: 'Locate in document',
    evidenceLocatedInReader: 'Highlighted in the reader',
    // AISuggestionEvidence – multi-citation list + attribution badges
    evidenceAlsoCited: 'Also cited ({{n}})',
    attributionEntailed: 'Verified',
    attributionWeak: 'Weak match',
    attributionUnsupported: 'Not supported',
    attributionUngroundable: 'Verify manually',
    // Attribution badge tooltips — this grades whether the CITED QUOTE supports
    // the value, independent of the AI's confidence or its rationale.
    attributionTooltipEntailed:
      'The cited quote supports this value. This grades the quote — not the AI confidence or rationale.',
    attributionTooltipWeak:
      'The cited quote is related but does not clearly establish this value. This grades the quote, not whether the value is right — verify in the document.',
    attributionTooltipUnsupported:
      'The cited quote does not establish this value. This grades the quote, not the AI confidence or rationale — the value may still be correct, but verify it against the document.',
    attributionTooltipUngroundable:
      'The value could not be located in the document text (e.g. it appears only in a figure). Verify manually.',
    // useExtractionJob async polling toasts
    extractionJobFailedTitle: 'AI extraction failed',
    extractionJobCancelledTitle: 'AI extraction cancelled',
} as const;

export type ExtractionCopy = typeof extraction;
