/**
 * UI copy for extraction area. English only.
 */
export const extraction = {
    headerBlindMode: 'Blind mode',
    headerSaving: 'Saving…',
    headerSavedAt: 'Saved at',
    headerUnsavedChanges: 'Unsaved changes',
    headerSaveFailed: 'Save failed — will retry on next edit',
    headerProgressFields: 'fields complete',
    headerProgressOf: 'of',
    headerViewAllStatus: 'View all status',
    headerRole: 'Role',
    headerProgress: 'Progress',
    headerStatus: 'Status',
    // HeaderFinalizeButton
    headerFinalize: 'Finalize',
    headerFinalizing: 'Finalizing…',
    // HeaderPDFControls
    pdfHide: 'Hide PDF',
    pdfShow: 'Show PDF',
    pdfHideShort: 'Hide',
    pdfShowShort: 'Show',
    comparisonToggleAria: 'Toggle comparison mode',
    comparison: 'Comparison',
    // HeaderNavigation
    back: 'Back',
    articleFirst: 'First article',
    articleLast: 'Last article',
    // ConfigureTemplateFirst
    configTemplateFirstTitle: 'Configure the template first',
    configTemplateFirstDesc: 'You need to configure the variables that will be extracted from articles. Go to the Configuration tab and choose:',
    configImportCharms: 'Import CHARMS template',
    configImportCharmsDesc: 'Use the official checklist for predictive model reviews',
    configCreateCustom: 'Create custom sections',
    configCreateCustomDesc: 'Define your own extraction variables',
    configGoToConfig: 'Go to Configuration',
    // ExtractionInterface tabs
    tabExtraction: 'Extraction',
    tabWorklist: 'Worklist',
    tabDashboard: 'Dashboard',
    tabConfiguration: 'Configuration',
    // ExtractionInterface dashboard
    dashboardArticles: 'Articles',
    dashboardInProject: 'in project',
    dashboardExtractionsStarted: 'Extractions Started',
    dashboardComplete: 'complete',
    dashboardArticlesInExtraction: 'articles in extraction',
    dashboardOverallProgress: 'Overall Progress',
    dashboardAverageCompleteness: 'average completeness',
    // Dense stat strip + completeness distribution bar
    dashboardStatInExtraction: 'In extraction',
    dashboardStatCompleted: 'Completed',
    dashboardStatAvgCompleteness: 'Avg. completeness',
    dashboardDistributionTitle: 'Completeness distribution',
    dashboardBucketNotStarted: 'Not started',
    dashboardBucketInProgress: 'In progress',
    dashboardBucketComplete: 'Complete',
    dashboardConfigureTitle: 'Configure your extraction template',
    dashboardConfigureDesc: 'To start extracting data, you need to configure the variables that will be collected.',
    dashboardYouCan: 'You can:',
    dashboardImportCharmsOption: 'Import the CHARMS template (official checklist)',
    dashboardCreateSectionsOption: 'Create your own sections and custom fields',
    dashboardConfigureButton: 'Configure',
    // ExtractionInterface configuration
    configPanelTitle: 'Configure your extraction template',
    configPanelDesc: 'Choose how you want to structure data extraction from articles',
    configImportCharmsTitle: 'Import CHARMS Template',
    configImportCharmsFullDesc: 'Use the official checklist for systematic reviews of predictive models. Includes 11 sections and 45 pre-configured fields following CHARMS guidelines.',
    configImportButton: 'Import',
    configCreateCustomTitle: 'Create Custom Template',
    configCreateCustomFullDesc: 'Define your own extraction sections and fields. Ideal for reviews with specific needs or different frameworks.',
    configCreateTemplateButton: 'Create Template',
    configManagersNote: 'Managers can configure templates',
    configManagersNoteDesc: 'If you are not a project manager, ask a manager to configure the extraction template before you start.',
    configContactManagerToConfigure: 'Only project managers can configure the extraction template. Contact the project manager to set up templates and start extracting.',
    configImportSectionTitle: 'Import template',
    configAvailableTemplates: 'Available templates',
    configNoTemplatesAvailable: 'No templates available at the moment.',
    configImportThisTemplate: 'Import',
    configImportTemplateButton: 'Import Template',
    configHeaderTitle: 'Template configuration',
    configPublishButton: 'Publish',
    configPublishTooltip:
      'Publish these configuration changes so reviewers and AI runs see them',
    configUnpublishedChanges: 'Unpublished changes',
    configPublishedVersion: 'Published · v{{n}}',
    configPublishSuccess: 'Published v{{n}}',
    configSectionsCountOne: '{{n}} section · {{main}} main',
    configSectionsCountOther: '{{n}} sections · {{main}} main',
    configSubSectionsCountOne: '{{n}} sub-section',
    configSubSectionsCountOther: '{{n}} sub-sections',
    configSeeDetails: 'See details',
    // ExtractionInterface loading & error
    loadingTemplates: 'Loading templates',
    errorLoadTemplates: 'Error loading templates',
    errorLoadArticles: 'Error loading articles',
    errorLoadStats: 'Error loading extraction statistics',
    errors_saveValues: 'Error saving values',
    errors_autoSaveFailed: 'Error saving data automatically',
    errors_autoSaveUpdateValues: 'Error updating {{n}} values: {{message}}',
    errors_advanceFailed: 'Could not advance the extraction stage',
    errors_markReadyFailed: 'Could not update your ready signal',
    // useSectionExtraction toasts
    sectionExtractionNoSuggestionsTitle: 'Extraction completed with no suggestions',
    sectionExtractionNoSuggestionsDesc: 'Extraction finished but no suggestions were created. Check that field names match exactly or that the PDF contains the expected data.',
    sectionExtractionSuccessTitle: 'Extraction completed! {{n}} suggestion(s) created for this section.',
    sectionExtractionTokensUsed: '{{n}} tokens used',
    sectionExtractionErrorTitle: 'Extraction error',
    sectionExtractionErrorFieldMismatch: 'Error: Field names do not match',
    sectionExtractionErrorFieldMismatchDesc: 'Extracted fields do not match the expected fields. Check the logs for details.',
    sectionExtractionErrorAuth: 'Authentication error',
    sectionExtractionErrorAuthDesc: 'Please sign in again.',
    sectionExtractionTimeoutDesc: 'Extraction took too long. Try again with a smaller PDF or extract sections individually.',
    errors_templateHasNoEntityTypes: 'Template has no entity types',
    // FullAIExtractionProgress
    fullAIProgressTitle: 'Full AI Extraction',
    fullAIProgressInProgress: 'AI extraction in progress…',
    fullAIProgressExtractingModels: 'Extracting models from article with AI…',
    fullAIProgressExtractingSections: 'Extracting top-level sections: {{label}}',
    fullAIProgressExtractingAllSections: 'Extracting sections from all models…',
    fullAIProgressRestore: 'Restore',
    fullAIProgressClose: 'Close',
    fullAIProgressMinimize: 'Minimize',
    // AISuggestionsPanel
    aiPanelNoTemplate: 'No template selected',
    aiPanelNoTemplateDesc: 'Select an extraction template to use AI suggestions',
    aiPanelNoArticle: 'No article selected',
    aiPanelNoArticleDesc: 'Select an article to generate AI suggestions',
    aiPanelTitle: 'AI Suggestions',
    aiPanelSubtitle: 'Use artificial intelligence to speed up data extraction',
    aiPanelRunAI: 'Run AI',
    aiPanelStatusTitle: 'AI Status',
    aiPanelStatusNotRun: 'Not started',
    aiPanelStatusNotRunDesc: 'Run AI to generate suggestions',
    aiPanelSuggestionsGenerated: 'Suggestions Generated',
    aiPanelSuggestionsPending: 'suggestions pending',
    aiPanelAcceptanceRate: 'Acceptance Rate',
    aiPanelSuggestionsAccepted: 'suggestions accepted',
    aiPanelSettingsTitle: 'Settings',
    aiPanelConfigureDesc: 'Configure how AI should process articles',
    aiPanelAIModelLabel: 'AI Model',
    aiPanelMinConfidenceLabel: 'Minimum Confidence',
    aiPanelFieldsForExtractionLabel: 'Fields for Extraction',
    aiPanelStudyInfo: 'Study basic information',
    aiPanelParticipantChars: 'Participant characteristics',
    aiPanelStatisticalMethods: 'Statistical methods',
    aiPanelResultsMetrics: 'Results and metrics',
    aiPanelHistoryTitle: 'AI extraction history',
    aiPanelHistoryDesc: 'Previous AI extractions for this article',
    aiPanelNoRunsFound: 'No AI extractions found',
    aiPanelNoRunsDesc: 'Run AI for the first time to generate suggestions',
    aiPanelSuggestionsCardTitle: 'Suggestions',
    aiPanelSuggestionsCardDesc: 'AI-generated suggestions for review',
    aiPanelNoSuggestionsAvailable: 'No suggestions available',
    aiPanelNoSuggestionsDesc: 'Run AI to generate value suggestions',
    aiPanelBatchActionsTitle: 'Batch Actions',
    aiPanelBatchActionsDesc: 'Quick actions for multiple suggestions',
    aiPanelAcceptAll: 'Accept All',
    aiPanelRejectAll: 'Reject All',
    aiPanelReprocess: 'Reprocess',
    // BatchExtractionProgress
    batchExtractingAllSections: 'Extracting all sections of the model',
    batchChunkOf: 'Chunk {{current}} of {{total}}',
    batchSectionsOf: 'Sections: {{completed}} of {{total}}',
    batchProcessing: 'Processing: {{name}}…',
    // Field/template management toasts
    fieldValidationFallback: 'Could not validate field',
    errorHandlerFallback: 'An unexpected error occurred',
    fieldOperationCreateFallback: 'Could not create field',
    fieldOperationEditFallback: 'Could not update field',
    fieldOperationDeleteFallback: 'Could not remove field',
    fieldOperationValidateFallback: 'Could not validate field',
    permissionDeniedOperation: 'You do not have permission to perform this action',
    validationErrorTitle: 'Validation error',
    validationInvalidData: 'Invalid data provided',
    errors_validateField: 'Error validating field',
    errors_addField: 'Error adding field',
    errors_updateField: 'Error updating field',
    errors_removeField: 'Error removing field',
    errors_deleteFieldInUse:
      'This field cannot be deleted: extraction work (proposals, decisions, or published values) already references it.',
    errors_cloneTemplate: 'Error cloning template',
    errors_republishTemplate:
      'Publishing failed — your changes are still saved as a draft. Try Publish again.',
    errors_createTemplate: 'Error creating template',
    errors_updateTemplateStatus: 'Error updating status',
    templateClonedSuccess: 'Template "{{name}}" cloned successfully!',
    templateCreatedSuccess: 'Template "{{name}}" created successfully!',
    templateActivatedSuccess: 'Template activated successfully!',
    templateDeactivatedSuccess: 'Template deactivated successfully!',
    errors_loadSuggestions: 'Error loading suggestions',
    errors_batchAcceptSuggestions: 'Error accepting suggestions in batch',
    errors_loadInstances: 'Error loading instances',
    errors_createInstance: 'Error creating instance',
    errors_updateInstance: 'Error updating instance',
    errors_deleteInstance: 'Error deleting instance',
    errors_reorderInstances: 'Error reordering',
    entityTypeNotFound: 'Entity type not found',
    instanceUpdatedSuccess: 'Instance updated successfully!',
    cannotDeleteInstanceWithValues: 'Cannot delete instance that has extracted values',
    instanceDeletedSuccess: 'Instance deleted successfully!',
    instanceCreatedSuccess: 'Instance "{{label}}" created successfully!',
    instanceAlreadyExists: 'Instance already exists',
    instancesReorderSuccess: 'Instance order updated!',
    noSectionsForModel: 'No sections found for this model',
    modelExtractionErrorTitle: 'Extraction error',
    modelExtractionAuthErrorTitle: 'Authentication error',
    noModelsExtractionComplete: 'Extraction completed but no prediction models were found in the article.',
    noModelsToExtractSections: 'No models to extract sections from. Extract models first.',
    extractionMayTakeMinutes: 'This may take a few minutes',
    pdfMainNotFound: 'Main PDF not found for this article',
    pdfLoadErrorTitle: 'Error loading PDF',
    pdfLoadDocumentError: 'Error loading PDF document',
    fullAICompleteSuccessTitle: 'Full AI extraction complete!',
    fullAISuccessDescription: '{{n}} model(s) processed with all sections extracted.',
    fullAITopLevelSections: '{{n}} top-level section(s) extracted.',
    fullAIPartialTitle: 'Extraction partially complete',
    fullAIPartialTopLevelFailed: 'Prediction models were extracted, but study-level sections failed and were not saved. Re-run extraction to retry them.',
    fullAIErrorPrefix: 'Error in full AI extraction',
    modelExtractionCompleteNoModels: 'Model extraction completed but no prediction models were found.',
    modelExtractionSuccessTitle: 'Extraction complete! {{n}} model(s) found and created.',
    modelExtractionSuccessTokens: '{{n}} tokens used',
    noModelsFoundTitle: 'No models found',
    errors_loadExtractionData: 'Error loading data',
    errors_loadExtractedValues: 'Error loading extracted values',
    errors_updateLabel: 'Error updating label',
    labelUpdatedSuccess: 'Label updated successfully',
    processingArticle: 'Processing article {{current}}/{{total}}: {{title}}',
    zoteroImportCompletedWithErrors: 'Import completed with errors',
    modelNotAuthenticatedOrInvalid: 'User not authenticated or invalid template',
    modelEntityTypeNotFound: 'Model entity type not found',
    errors_createModel: 'Error creating model',
    errors_removeModel: 'Error removing model',
    errors_topLevelSectionsExtraction: 'Error in top-level sections extraction',
    errors_allSectionsExtraction: 'Error in extraction of all sections',
    batchSectionExtractionSuccess: 'Extraction complete! {{n}} section(s) extracted successfully.',
    batchSectionExtractionSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchSectionExtractionPartial: 'Extraction partially complete: {{success}}/{{total}} section(s) extracted successfully.',
    batchSectionExtractionPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} section(s) failed. Check the logs for details.',
    errors_sectionsExtraction: 'Error in section extraction',
    modelCreatedSuccess: 'Model "{{label}}" created successfully!',
    modelRemovedSuccess: 'Model "{{label}}" removed successfully',
    errors_zoteroFetch: 'Error fetching Zotero collections',
    errors_zoteroImport: 'Error importing articles',
    zoteroDisconnectSuccess: 'Zotero integration removed',
    zoteroDisconnectError: 'Error removing integration',
    zoteroImportCompleteSuccess: 'Import complete! {{imported}} imported, {{updated}} updated',
    zoteroImportPdfsDownloaded: ', {{n}} PDFs downloaded',
    zoteroConnectionSuccess: 'Connection successful! User: {{name}}',
    zoteroConnectionFailed: 'Failed to connect to Zotero',
    zoteroTestConnectionError: 'Error testing connection',
    zoteroCredentialsSavedSuccess: 'Credentials saved successfully!',
    zoteroCredentialsSaveError: 'Error saving credentials',
    noTopLevelSectionsFound: 'No top-level sections found to extract',
    zoteroProgressFetching: 'Fetching articles from Zotero…',
    zoteroProgressFetchingCount: 'Fetching articles… {{current}}/{{total}}',
    zoteroProgressProcessing: 'Processing articles…',
    zoteroProgressProcessingCount: 'Processing {{current}}/{{total}}…',
    zoteroProgressProcessingWithPdfs: 'Processing and downloading PDFs… {{current}}/{{total}}',
    zoteroProgressComplete: 'Import complete!',
    zoteroProgressError: 'Import error',
    zoteroItemNoTitle: 'Item has no title',
    zoteroItemTitleFallback: 'No title',
    newInstanceLabel: 'New instance',
    batchAcceptCountToast: '{{n}} suggestion(s) accepted in batch',
    noSuggestionConfidenceToast: 'No suggestions with confidence ≥{{pct}}%',
    errors_extractionError: 'Extraction error',
    errors_extractionAuth: 'Authentication error',
    errors_noPermissionAddField: 'You do not have permission to add fields',
    errors_validationPrefix: 'Validation: {{message}}',
    errors_duplicateFieldKey: 'A field with this key already exists in this section',
    errors_cannotChangeFieldType: 'Cannot change field type when it already has extracted data',
    errors_typeChangeProbeFailed: 'Could not verify the field’s extracted data — the type was not changed',
    // ExtractionErrorBoundary
    errorBoundaryTitle: 'Extraction error',
    errorBoundaryDescription: 'An unexpected error occurred. You can try to recover or go back to the home page.',
    errorBoundaryDetailsLabel: 'Error details:',
    errorBoundaryUnknown: 'Unknown error',
    errorBoundaryTryAgain: 'Try again',
    errorBoundaryBackToHome: 'Back to home',
    errorBoundaryExportLogs: 'Export logs',
    errorBoundarySuggestionsTitle: 'Suggestions:',
    errorBoundarySuggestionReload: 'Reload the page (F5)',
    errorBoundarySuggestionCache: 'Clear your browser cache',
    errorBoundarySuggestionConnection: 'Check your internet connection',
    errorBoundarySuggestionSupport: 'If the error persists, export the logs and contact support',
    fieldUpdatedSuccess: 'Field updated successfully!',
    fieldRemovedSuccess: 'Field removed successfully!',
    // Article extraction list/table shared strings
    listStatusNotStarted: 'Not started',
    listStatusComplete: 'Complete',
    listStatusInProgress: 'In progress',
    statusInProgressPct: 'In progress · {{n}}%',
    listTryAgain: 'Try again',
    listNoArticles: 'No articles found in this project',
    listNoArticlesDesc: 'Add articles first to start data extraction.',
    // HeaderMoreMenu
    moreOptions: 'More options',
    moreActions: 'Actions',
    moreExtractAI: 'Extract with AI',
    moreExtractingAI: 'Extracting with AI…',
    moreOpenQA: 'Open Quality Assessment',
    moreKeyboardShortcuts: 'Keyboard Shortcuts',
    moreHelp: 'Help',
    moreShortcutsDialogTitle: 'Keyboard Shortcuts',
    moreShortcutsDialogDesc: 'Shortcuts available in the extraction interface',
    moreShortcutSave: 'Save manually',
    moreShortcutSearch: 'Search',
    moreShortcutCancel: 'Cancel action',
    moreShortcutNextField: 'Next field',
    moreShortcutPrevField: 'Previous field',
    moreShortcutTip: 'Tip: Press ? to view this list quickly',
    // HeaderAIActions
    aiSuggestionPending: 'AI suggestion pending',
    aiSuggestionsPending: 'AI suggestions pending',
    aiClickToView: ' — Click to view',
    // ArticleExtractionTable (toast)
    tableErrorLoadArticles: 'Error loading articles',
    tableSelectAtLeastOne: 'Select at least one article',
    tableErrorProcessAI: 'Error processing AI extraction',
    tableErrorUnknown: 'Unknown error',
    batchChunkedSuccessTitle: 'Extraction complete! {{n}} section(s) extracted successfully.',
    batchChunkedSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchChunkedPartialTitle: 'Extraction partially complete: {{success}}/{{total}} section(s) extracted successfully.',
    batchChunkedPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} section(s) failed. {{tokens}} tokens used.',
    topLevelSuccessTitle: 'Top-level sections extracted: {{success}}/{{total}}',
    topLevelSuccessDesc: '{{suggestions}} suggestion(s) created.',
    topLevelPartialTitle: 'Top-level extraction partially complete: {{success}}/{{total}} section(s).',
    topLevelPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} section(s) failed.',
    topLevelFailedTitle: 'Failed to extract top-level sections',
    topLevelFailedDesc: 'All {{failed}} section(s) failed.',
    batchAllModelsSuccessTitle: 'Extraction complete! Sections extracted from {{n}} model(s) successfully.',
    batchAllModelsSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchAllModelsPartialTitle: 'Extraction partially complete: {{success}}/{{total}} model(s) processed successfully.',
    batchAllModelsPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} model(s) failed. {{tokens}} tokens used.',
    zoteroImportStarting: 'Starting import…',
    zoteroImportCancelled: 'Import cancelled',
    configNoGlobalTemplates: 'No global templates available',
    sectionLabelLabel: 'Section label *',
    sectionDescriptionOptional: 'Description (optional)',
    sectionTypeLabel: 'Section type *',
    sectionTypeSingle: 'Single section',
    sectionTypeMultiple: 'Multiple sections',
    sectionRequiredLabel: 'Required section',
    evidenceCited: 'Cited evidence',
    pageLabel: 'Page {{n}}',
    tableNoArticlesInProject: 'No articles found in this project',
    tableNoArticles: 'No articles found',
    // ImportTemplateDialog
    importTitle: 'Import Global Template',
    importDesc: 'Select a standardized template to use in your project.',
    importLoadingTemplates: 'Loading templates…',
    importNoTemplates: 'No global templates available at the moment.',
    importSections: 'sections',
    importTemplateSelected: 'Selected template:',
    importTemplateSelectedDetail: 'with pre-configured sections. All sections and fields will be imported to your project.',
    importCancel: 'Cancel',
    importImporting: 'Importing…',
    importImportButton: 'Import Template',
    importErrorSelect: 'Select a template to import',
    importErrorImport: 'Error importing template',
    importSuccess: 'Template imported successfully',
    // CreateCustomTemplateDialog
    createTitle: 'Create Custom Template',
    createDesc: 'Create an empty template and add custom sections and fields',
    createNameLabel: 'Template Name',
    createNamePlaceholder: 'e.g. Custom Extraction - Diabetes',
    createNameDesc: 'Descriptive name to identify this template',
    createDescriptionLabel: 'Description',
    createDescriptionPlaceholder: 'Describe the purpose of this template…',
    createDescriptionDesc: 'Explain what data will be extracted and for what purpose',
    createFrameworkLabel: 'Base Framework',
    createFrameworkPlaceholder: 'Select a framework',
    createFrameworkCustom: 'Custom',
    createFrameworkCharms: 'CHARMS (customized)',
    createFrameworkPicos: 'PICOS (customized)',
    createFrameworkDesc: 'Conceptual base of the template (can be CUSTOM if fully custom)',
    createCreating: 'Creating…',
    createTemplateButton: 'Create Template',
    createAuthRequired: 'You must be signed in',
    createSuccessCreated: 'Template created successfully!',
    createInfoAddSections: 'Now add sections and fields in the Setup tab',
    createErrorCreate: 'Error creating template',
    createValidationNameMin: 'Name must be at least 3 characters',
    createValidationNameMax: 'Name must be at most 100 characters',
    createValidationDescMax: 'Description must be at most 500 characters',
    createValidationFramework: 'Select a framework',
    noDescription: 'No description',
    // ArticleExtractionTable (columns, filters, actions)
    tableFilterAllStatus: 'All statuses',
    tableColumnTitle: 'Title',
    tableColumnYear: 'Year',
    tableColumnProgress: 'Progress',
    tableColumnStatus: 'Status',
    tableColumnAuthors: 'Authors',
    tableColumnCreatedAt: 'Created at',
    tableColumnField: 'Field',
    tableFilterSelectStatus: 'Select status…',
    tableSearchTitle: 'Search in title…',
    tableSearchYearPlaceholder: 'e.g. 2023, 2020-2024…',
    tableSearchProgressPlaceholder: 'e.g. complete, in progress, 50…',
    tableSearchAuthor: 'Search author…',
    tableSearchPlaceholder: 'Search…',
    tableClearFilter: 'Clear',
    tableSearchAllFields: 'Search in all fields…',
    tableSearchPlaceholderShortcut: 'Search… (⌘F / Ctrl+F)',
    tableShortcutFilter: 'Filter (F)',
    tableShortcutSearch: 'Search (⌘F / Ctrl+F)',
    tableDisplayAndSort: 'Display & sort',
    tableOrdering: 'Ordering',
    tableDisplayOptions: 'Display options',
    tableClearAll: 'Clear all',
    tableRemoveFilter: 'Remove filter {{label}}',
    tableSelectArticleAria: 'Select article: {{title}}',
    tableOpenRowAria: 'Open extraction for {{title}}',
    tableStatusLegendAria: 'Status legend',
    tableArticlesCount: 'articles',
    tableSelectFiltered: 'Select filtered articles',
    tableSelectAll: 'Select all articles',
    tableActions: 'Actions',
    tableActionOpen: 'Open',
    tableStart: 'Start',
    tableView: 'View',
    tableContinue: 'Continue',
    tableAdjustFilters: 'Try adjusting the search filters.',
    tableClearFilters: 'Clear filters',
    tableBatchAIStarting: 'Starting AI extraction for {{count}} article(s)…',
    tableArticleSelected: 'article selected',
    tableArticlesSelected: 'articles selected',
    tableSelectedCount: '{{n}} selected',
    tableSelectionMenuTooltip: 'Actions menu for selected articles',
    tableBatchActionsLabel: 'Batch actions',
    tableAIExtraction: 'AI extraction',
    tableExport: 'Export',
    tableInDevelopment: 'In development',
    tableClearSelection: 'Clear selection',
    // AISuggestionReviewPopover – invalid-timestamp fallback
    historyInvalidDate: 'Invalid date',
    suggestionAccepted: 'Accepted',
    suggestionRejected: 'Rejected',
    aiAccepted: 'AI accepted',
    toastSuggestionAcceptedSuccess: 'Suggestion accepted successfully',
    toastSuggestionRejectedSuccess: 'Suggestion rejected',
    emptyValue: '(empty)',
    // FieldInput
    fieldRequired: 'Required field',
    fieldMustBeNumber: 'Value must be a number',
    valuesCommaSeparated: 'Comma-separated values',
    yes: 'Yes',
    no: 'No',
    defaultUnit: '(default)',
    // AISuggestionsPanel
    panelNotRun: 'Not started',
    panelNoSuggestions: 'No suggestions available',
    panelBatchActions: 'Batch actions',
    panelBatchActionsDesc: 'Quick actions for multiple suggestions',
    // Field vocabulary shared by the grid, inspector and value editors
    otherSpecifyDefault: 'Other (specify)',
    fieldTypeBoolean: 'Yes/No',
    fieldTypeText: 'Text',
    fieldTypeNumber: 'Number',
    fieldTypeDate: 'Date',
    fieldTypeSelect: 'Selection',
    fieldTypeMultiselect: 'Multiple choice',
    actionsForFieldAria: 'Actions for field {{label}}',
    // RemoveModelDialog
    removeModelAnyway: 'Yes, remove anyway',
    removeModel: 'Remove {{noun}}',
    // DeleteFieldConfirm
    cannotDelete: 'Cannot delete',
    // AllowedUnitsList
    firstIsDefault: 'First is default',
    orAddCustomFirstDefault: 'or add custom units above. The first unit will be the default.',
    unitsEmptyHint: 'Leave empty to use automatic suggestions based on context, or add custom units above. The first unit will be the default.',
    // TemplateManager
    cloneError: 'Could not clone the selected template.',
    cloneOrCreateDesc: 'Clone a default template or create a custom one',
    cloneOneOrCreate: 'Clone a default template or create a custom one to get started',
    defaultTemplatesAvailable: 'Default templates available for cloning',
    runMigrationsHint: 'Run Supabase migrations to populate the database (CHARMS, PICOS, etc.)',
    updateList: 'Refresh list',
    cloneTemplateTitle: 'Clone template',
    chooseTemplateToClone: 'Choose a global template to clone',
    comingSoon: 'This feature will be available soon',
    cloneButton: 'Clone',
    createButton: 'Create',
    createCustomTemplateDesc: 'Create a custom template for this project',
    sectionsConfigured: 'sections configured',
    // RemoveModelDialog
    removeModelTitle: 'Remove {{noun}}',
    removeModelDesc: 'You are about to remove the {{noun}} "{{name}}"',
    removeModelWarningTitle: 'Warning: This {{noun}} contains extracted data!',
    removeModelFieldFilled: 'field is filled in this {{noun}}.',
    removeModelFieldsFilled: 'fields are filled in this {{noun}}.',
    removeModelDataPermanent: 'All extracted data will be permanently removed and cannot be recovered.',
    removeModelNoData: 'This {{noun}} has no extracted data. Removal will not affect other entries or study-level sections.',
    removeModelWhatRemoved: 'What will be removed:',
    removeModelSubsections: 'All sub-sections of this {{noun}}',
    removeModelAllValues: 'All extracted values ({{count}} fields)',
    removeModelRemoving: 'Removing…',
    removeModelError: 'Error removing {{noun}}',
    noUnitsConfigured: 'No units configured',
    loadingGlobalTemplates: 'Loading global templates…',
    createCustomTemplateTitle: 'Create custom template',
    loadingConfiguration: 'Loading configuration…',
    noSectionsConfigured: 'No sections configured',
    noStudyLevelFields: 'No study-level fields configured in the template.',
    noModelsAdded: 'No {{noun}} added yet',
    noModelsAddedDesc: 'Add a {{noun}} manually or extract it automatically from the article.',
    // RunHeader (extraction-specific keys — shared header keys now live in the runs namespace)
    runHeaderFinishExtraction: 'Finish extraction',
    runHeaderFinishExtractionTooltip: 'Signal that you are done extracting this article and open the next one.',
    runHeaderExtractionFinished: 'Extraction finished',
    runHeaderStartConsensus: 'Start consensus',
    runHeaderStartConsensusTooltip: 'Move this article into consensus for review and publishing.',
    runHeaderApproveFinalize: 'Approve & finalize',
    runHeaderApproveFinalizeTooltip: 'Publish every agreed value and finalize this article.',
    runHeaderApproveBlocked: 'Resolve every diverging field and fill all required fields first',
    runHeaderFinalize: 'Finalize',
    runHeaderFinalizeTooltip: 'Lock and publish the agreed values.',
    runHeaderGateBlocked: 'Complete the required fields first',
    runHeaderCompareToggle: 'Compare reviewers',
    runHeaderReopenForRevision: 'Reopen for revision',
    runHeaderReopening: 'Reopening…',
    // Reopen consensus -> extraction (arbitrator-only, destructive). See ADR-0017.
    runHeaderReopenExtraction: 'Reopen extraction',
    reopenExtractionTitle: 'Reopen for extraction?',
    reopenExtractionBodyDiscard:
      'This discards {{count}} resolved consensus decision(s), and any evidence attached to them, and returns the article to Extraction where reviewers can edit again. This cannot be undone.',
    reopenExtractionBodyClean:
      'This returns the article to Extraction so reviewers can edit again. Nothing has been resolved yet, so nothing is discarded.',
    reopenExtractionConfirmDiscard: 'Reopen & discard',
    reopenExtractionConfirmClean: 'Reopen',
    reopenExtractionToast: 'Article reopened for extraction.',
    // Section navigation rail
    sectionNavRequiredLeft: '{{count}} required left',
    sectionNavComplete: 'All required fields complete',
    sectionNavAria: 'Section navigation',
    errorCalculatingProgress: 'Error calculating progress',
    loadingComparison: 'Loading comparison…',
    requiredLabel: 'Required',
    // DeleteFieldConfirm
    confirmDeleteTitle: 'Confirm deletion',
    deleteField: 'Delete field',
    understood: 'Understood',
    deleteFieldWarningUndo: 'This action cannot be undone',
    deleteFieldWarningRemoved: 'The field will be permanently removed from the section',
    deleteFieldWarningNewArticles: 'New articles will no longer have this field',
    deleteFieldWarningExisting: 'Already started articles will not be affected (structure preserved)',
    cannotDeleteReason: 'This field has {{count}} extracted values',
    cannotDeleteAffects: 'Affects {{count}} article(s) in extraction',
    cannotDeleteWouldLose: 'Deleting would cause data loss and inconsistencies',
    alternativesTip: 'Alternatives:',
    markNotRequired: 'Mark as "not required" instead of deleting',
    deleteValuesFirst: 'Delete extracted values first (with care)',
    contactAdmin: 'Contact the administrator',
    youAreTryingToDelete: 'You are trying to delete the field:',
    impossibleToDelete: 'Cannot delete:',
    exportButton: 'Export',
    // UnitEditor
    unitPlaceholder: 'e.g. years, kg, %, mmHg (or leave empty)',
    unitSuggestionsButton: 'Suggestions',
    unitSearchPlaceholder: 'Search unit…',
    unitNoneFound: 'No unit found',
    // AddSectionDialog
    selectTypePlaceholder: 'Select type',
    placeholderSectionNameExample: 'e.g. exclusion_criteria',
    // ModelSelector / AddModelDialog
    selectModelPlaceholder: 'Select a {{noun}}…',
    modelNamePlaceholder: 'Enter a name for this {{noun}}…',
    modelDescriptionPlaceholder: 'e.g. Supervised learning, Neural network…',
    modelNameLabel: '{{noun}} name',
    modelNameHint: 'Choose a descriptive name to identify this {{noun}}',
    modellingMethodLabel: 'Modelling method',
    modellingMethodOptional: '(optional)',
    modellingMethodHint: 'You can fill this in later during extraction',
    modelSelectorTitle: '{{noun}} entries',
    modelSelectorDesc: 'Select a {{noun}} to extract its data',
    modelExtractAITitle: 'Extract {{noun}} entries automatically with AI',
    modelExtractAIShort: 'Extract with AI',
    modelExtractModelsOnly: 'Extract {{noun}} entries only',
    modelExtractAllSections: 'Extract sections from every {{noun}}',
    modelAddManuallyTitle: 'Add new {{noun}} manually',
    modelNewShort: 'New',
    modelRemoveActiveTitle: 'Remove active {{noun}}',
    modelActiveLabel: 'Active {{noun}}',
    // TemplateManager
    templateManageTitle: 'Manage templates',
    templateManageDesc: 'Clone default templates or create custom ones',
    templateGlobalTitle: 'Global Templates',
    templateGlobalDesc: 'Default templates available for cloning',
    templateCloneButton: 'Clone template',
    templateCreateButton: 'Create template',
    templateProjectTemplates: 'Project templates',
    templateProjectDesc: 'Active templates available for this project',
    templateNoneFound: 'No template found',
    templateNoneHint: 'Clone a default template or create a custom one to get started',
    templateCreatedAt: 'Created on',
    // SectionAccordion
    sectionNoInstances: 'No instances created for this section',
    sectionAddInstance: 'Add',
    // AllowedUnitsList
    unitMoveUp: 'Move up',
    unitMoveDown: 'Move down',
    unitRemove: 'Remove',
    // AISuggestionEvidence
    copyCopied: 'Copied!',
    copySnippet: 'Copy snippet',
    // PDF / UI aria
    zoomPercentageAria: 'Zoom percentage',
    searchDocumentAria: 'Search in document',
    removeFileAria: 'Remove file',
    placeholderTypeHere: 'Type here',
    allowOtherSpecifyLabel: 'Allow "Other (specify)"',
    otherLabelLabel: '"Other" label',
    placeholderLabel: 'Placeholder',
    fieldPlaceholderEnter: 'Enter {{label}}',
    // Impact-probe messages (delete confirm + type-change guard)
    fieldExtractedValuesMessage: 'This field has {{count}} extracted values in {{n}} article(s).',
    fieldSafeToModifyMessage: 'Field can be modified safely.',
    // Placeholders and inline UI (FieldInput, dialogs)
    selectFieldPlaceholder: 'Select {{label}}',
    addInstanceLabel: 'Add {{label}}',
    sectionConfirmPlaceholder: 'Type "{{name}}" to confirm',
    createModel: 'Create {{noun}}',
    addNewModel: 'Add new {{noun}}',
    addNewModelDesc: 'Create a new {{noun}} to extract its data. You can add as many as you need.',
    modelsAlreadyAdded: 'Already added:',
    creating: 'Creating…',
    addManually: 'Add manually',
    addSection: 'Add section',
    addNewSection: 'Add new section',
    createSection: 'Create section',
    typeAbovePressEnter: 'Type above and press Enter or click',
    dragToReorder: 'Drag to reorder',
    noOptionsAddedYet: 'No options added yet',
    selectTemplateToStart: 'Select an extraction template to get started',
    selectInstance: 'Select an instance',
    clickInstanceToEdit: 'Click an instance above to edit its fields',
    instanceEditorTitle: 'Instance editor',
    instanceEditorDesc: 'Manage entity instances for template {{name}}',
    noTemplateSelected: 'No template selected',
    newInstance: 'New instance',
    totalInstances: 'Total instances',
    instancesCreated: 'instances created',
    valuesExtracted: 'Values extracted',
    valuesFilled: 'values filled',
    completeness: 'completeness',
    progressLabel: 'Progress',
    instancesCardTitle: 'Instances',
    instancesCardDesc: 'Entity instances created for extraction',
    loadingInstances: 'Loading instances…',
    noInstancesCreated: 'No instances created',
    createInstancesToStart: 'Create entity instances to start extracting data',
    createFirstInstance: 'Create first instance',
    valuesFilledCount: 'values filled',
    complete: 'complete',
    fieldEditorTitle: 'Field editor',
    fieldEditorDesc: 'Fill in values for the selected instance',
    // ExtractionExportDialog (009-extraction-excel-export)
    exportDialogTitle: 'Export extraction data',
    exportDialogSubtitle: 'Export extracted data from the active template as an Excel workbook (.xlsx).',
    exportSourceLabel: 'Source of values',
    exportSourceConsensus: 'Consensus',
    exportSourceConsensusDesc: 'Canonical post-consensus values for finalized articles.',
    exportSourceSingleUser: 'Single user',
    exportSourceSingleUserDesc: 'Latest non-reject decisions for one reviewer.',
    exportSourceAllUsers: 'All users',
    exportSourceAllUsersDesc: 'Consensus plus one column per reviewer (manager only).',
    exportSourceAllUsersDisabledTooltip: 'Only project managers can export all reviewers side-by-side.',
    exportReviewerLabel: 'Reviewer',
    exportReviewerSelfFallback: 'Only your own decisions are available — your role does not allow exporting other reviewers.',
    exportReviewerEmptyState: 'No reviewer has recorded decisions on this template yet, so there is nothing to export for a single user. Run extraction and review first, or pick another source.',
    exportScopeLabel: 'Articles to export',
    exportScopeCurrentList: 'Current list',
    exportScopeSelectedOnly: 'Selected only',
    exportAdditionalLabel: 'Additional content',
    exportIncludeAiMetadata: 'Include AI metadata sheet',
    exportIncludeAiMetadataDesc: 'Adds a flat sheet listing every AI proposal with confidence, rationale, evidence, and reviewer outcome.',
    exportAnonymizeReviewers: 'Anonymize reviewer names',
    exportAnonymizeReviewersDesc: 'Replace reviewer names with Reviewer A / B / … in the exported file. Useful when sharing the file outside your team.',
    exportEmptyConsensusReason: 'No finalized data to export yet.',
    exportEmptySingleUserReason: 'No decisions recorded yet for this reviewer.',
    exportEmptyAllUsersReason: 'No reviewer decisions recorded yet.',
    exportEmptyNoArticlesReason: 'No articles in scope — adjust filters or pick a different article scope.',
    exportConfirm: 'Export',
    exportGenerating: 'Generating…',
    exportRetry: 'Retry',
    exportCancel: 'Cancel',
    exportSuccessToast: 'Export downloaded.',
    exportStartedToast: 'Export started — we will notify you when it is ready.',
    exportFailedToast: 'Export failed.',
    exportFilenamePreviewLabel: 'File',
    exportPreviewLineFmt: 'Will export {articles} articles × {fields} fields → {delivery}',
    exportPreviewLineNoFieldsFmt: 'Will export {articles} articles → {delivery}',
    exportPreviewDeliveryInline: 'inline download',
    exportPreviewDeliveryAsync: 'background job',
    // TemplateInspector section summary
    fieldsCountLabel: 'field(s)',
    // TemplateConfigEditor section card labels
    typeLabel: 'Type',
    cardinalityUnique: 'Unique',
    cardinalityMultiple: 'Multiple',
    subSections: 'Subsections',
    editLabelButton: 'Edit label',
    removeButton: 'Remove',
    // Template config grid (B-1 shell): columns, section metadata, search
    gridAria: 'Template fields',
    gridColLabel: 'Label',
    gridColType: 'Type',
    gridColRequired: 'Req.',
    gridColKey: 'Key',
    gridColOptions: 'Options',
    gridColAi: 'AI instruction',
    gridNewField: 'New field',
    gridNewSection: 'New section',
    gridSectionCount: '{{n}}',
    gridSearchPlaceholder: 'Search fields…',
    gridSearchCount: '{{n}}/{{total}}',
    gridSearchClear: 'Clear search',
    gridNoMatches: 'No field matches this search.',
    gridDisplayMenu: 'Display options',
    gridDisplayKeyColumn: 'Key column',
    gridDisplayOptionsColumn: 'Options column',
    gridEditLabelAria: 'Edit label',
    gridEditKeyAria: 'Edit key',
    gridRenameSectionAria: 'Rename section',
    gridNewFieldAria: 'New field label',
    gridNewFieldPlaceholder: 'Field label',
    gridRowActions: 'Field actions',
    gridEmptyTemplate: 'This template has no sections yet.',
    gridCollapseSection: 'Collapse section',
    gridExpandSection: 'Expand section',
    gridAddMenu: 'Add',
    // Control cells (B-5 Task 5): act on first click
    gridTypeMenuAria: 'Change type — {{label}}',
    gridRequiredToggleAria: 'Required — {{label}}',
    gridAiCellAria: 'AI instruction — {{label}}',
    gridOptionsCellAria: 'Options — {{label}}',
    sectionMetaRepeatingGroup: 'Repeating group',
    sectionMetaRepeatsPerArticle: 'repeats per article',
    sectionMetaRepeatsPerModel: 'repeats per {{noun}}', // B-8 D7: grid call site interpolates the group's entry noun
    matchHintKey: 'in key',
    matchHintDescription: 'in description',
    matchHintAiInstruction: 'in AI instruction',
    matchHintOptions: 'in options',
    // Template config inspector (B-1 shell; field form editable in place)
    inspectorEmptyTitle: 'Nothing selected',
    inspectorEmptyHint: 'Select a field or a section to see its details.',
    inspectorSectionLabel: 'Section',
    inspectorKeyLabel: 'Key',
    inspectorTypeLabel: 'Type',
    inspectorRequiredLabel: 'Required',
    inspectorRequiredYes: 'Required',
    inspectorRequiredNo: 'Optional',
    inspectorOptionsLabel: 'Options',
    inspectorAiLabel: 'AI instruction — this field',
    inspectorAiHint: 'Guides the AI on this field only.',
    inspectorAiEmpty: 'No field-level instruction.',
    inspectorDescriptionLabel: 'Description — for reviewers',
    inspectorDescriptionHint: 'Never sent to the AI.',
    inspectorDescriptionEmpty: 'No description.',
    inspectorLabelLabel: 'Label',
    inspectorSave: 'Save changes',
    inspectorReset: 'Reset',
    inspectorRequiredSwitch: 'Mark this field as required',
    inspectorKindRoot: 'Section',
    inspectorKindGroup: 'Repeating group',
    inspectorKindGroupChild: 'Per-{{noun}} section', // B-8 D7: badge call site interpolates the entry noun
    // Inspector absorption + visibility (B-5 Task 5)
    inspectorUnitsLabel: 'Units',
    inspectorUnitsHint: 'The first unit is the default reviewers see.',
    inspectorDispositionsLabel: 'Dispositions',
    inspectorTypeChangeHint: 'Changing the type of a field that already holds answers is a destructive change — you will confirm it before publishing.',
    inspectorToggle: 'Show or hide the inspector (⌘./Ctrl+.)',
    inspectorSheetTitle: 'Field inspector',
    // TemplateInstructionRow (general AI instruction, config row zero)
    instructionTitle: 'General AI instruction',
    instructionEmpty:
      'No general instruction — the AI receives only section and field instructions.',
    instructionPlaceholder:
      'Guidance sent to the AI before every section of this template…',
    instructionCustomizeChip: '{{n}} to customize',
    instructionEditedBadge: 'edited',
    instructionCounter: '{{n}} / 4000',
    instructionSave: 'Save',
    instructionCancel: 'Cancel',
    instructionResetDefault: 'Reset to template default',
    instructionInsertDefault: 'Insert suggested default',
    instructionSuggestedDefault:
      "You are extracting data for a systematic review. Report values exactly as stated in the article, do not infer unreported values, and quote the passage supporting each value. [customize: describe this review's scope]",
    instructionSavedToast: 'General AI instruction saved',
    errors_saveInstruction: 'Could not save the general AI instruction',
    // QualityAssessmentInterface / dashboard
    dashboardProgress: 'Progress',
    sectionSingle: 'section',
    sectionMultiple: 'sections',
    // AddSectionDialog – validation messages
    nameRequired: 'Name is required',
    nameMin2: 'Name must be at least 2 characters',
    nameMax50: 'Name must be at most 50 characters',
    nameFormat: 'Invalid name format',
    labelRequired: 'Label is required',
    labelMin2: 'Label must be at least 2 characters',
    labelMax100: 'Label must be at most 100 characters',
    descriptionMax500: 'Description must be at most 500 characters',
    cardinalityRequired: 'Required',
    sectionCreatedSuccess: 'Section "{{label}}" created successfully',
    sectionCreateError: 'Error creating section',
    placeholderSectionLabel: 'Section label',
    placeholderSectionDescription: 'Section description',
    // AllowedUnitsList
    enterUnit: 'Enter a unit',
    unitAlreadyAdded: 'Unit already added',
    max20Units: 'At most 20 units',
    placeholderUnits: 'Enter units',
    suggestionsButton: 'Suggestions',
    searchUnit: 'Search unit',
    noUnitFound: 'No unit found',
    // AllowedValuesList
    enterValue: 'Enter a value',
    valueAlreadyAdded: 'Value already added',
    max100Values: 'At most 100 values',
    placeholderOptions: 'Enter options',
    // SectionAccordion – AI extraction buttons
    extractSectionWithAI: 'Extract {{label}} with AI',
    extractAllSectionsWithAI: 'Extract all sections with AI',
    extractingWithAI: 'Extracting with AI…',
    extractingAllSectionsWithAI: 'Extracting all sections with AI…',
    createInstanceBeforeExtract: 'Create an instance before extracting',
    // AddModelDialog – validation & errors
    modelCreateError: 'Error creating {{noun}}',
    modelNameEmpty: '{{noun}} name cannot be empty',
    modelNameMinLength: '{{noun}} name must be at least 3 characters',
    modelNameDuplicate: 'A {{noun}} with this name already exists',
    evidenceCitedAria: 'Cited evidence',
    // AISuggestionReviewPopover – rationale section label
    aiRationaleLabel: 'Rationale',
    // AISuggestionConfidence
    aiConfidenceTooltip: 'AI suggestion confidence level',
    // AISuggestionReviewPopover – unified version review + selection
    reviewTitle: 'Review suggestion',
    reviewVersionsCount: '{{n}} version(s)',
    reviewNoVersions: 'No AI versions yet',
    reviewHistoryError: 'Couldn’t load the version history. Close and reopen to retry.',
    reviewSelected: 'Selected',
    reviewUseThisVersion: 'Use this version',
    reviewNoInformation: 'No information found',
    reviewNoInformationDesc: 'The model reported no information for this field in the document.',
    reviewLowConfidence: 'low',
    reviewClear: 'Clear',
    reviewClearHint: 'Each selection is recorded with who chose it and when.',
    reviewDetails: 'Details',
    reviewOpenFromValue: 'Open review · see other versions, evidence and provenance',
    reviewPinNotInHistory: 'The adopted version is older than the loaded history.',
    // Consensus-trace attribution (D3) — pinned-row chip + cross-marks + run headers
    reviewAdoptedBy: 'Adopted by {{name}}',
    reviewEditedBy: 'Edited by {{name}}',
    reviewRunBy: 'Run by {{name}}',
    // Verified-mode verdict chip (§5) — the second pass's per-value judgement.
    // No chip = "not verified" (Fast run, degraded pass, or no-info proposal).
    verificationConfirmed: 'Verified',
    verificationUnsupported: 'Not supported',
    verificationUncertain: 'Uncertain',
    // Runtime disposition control (ADR-0016) — set a "no value, on purpose" answer
    // on any field type when the source is silent / the item does not apply.
    dispositionNoInformation: 'No information',
    dispositionNotApplicable: 'Not applicable',
    dispositionNotEvaluated: 'Not evaluated',
    // Hover descriptions — same wording as the export legend (value_semantics
    // labels ↔ extraction_export_service legend), so screen and export agree.
    dispositionNoInformationHint: 'The source does not state this item.',
    dispositionNotApplicableHint: 'The item does not apply to this study.',
    dispositionNotEvaluatedHint: 'The item was not assessed.',
    dispositionSet: 'Mark as…',
    dispositionClear: 'Clear',
    dispositionActiveHint: 'Recorded as a resolved answer.',
    // Template builder — opt-in disposition flags. "No information" is universal.
    dispositionBuilderHint: '"No information" is available on every field automatically.',
    dispositionAllowNotApplicableLabel: 'Allow "Not applicable"',
    dispositionAllowNotEvaluatedLabel: 'Allow "Not evaluated"',
    // Provenance summary + GenerationDetailsDialog – "how this was generated"
    provenanceToggle: 'How this was generated',
    provenanceRanBy: 'Ran by',
    provenanceProvider: 'Provider',
    provenanceModel: 'Model',
    provenanceReasoning: 'Reasoning',
    provenanceTemperature: 'Temperature',
    provenanceOutputRetries: 'Output retries',
    provenanceTimeout: 'Timeout',
    provenanceTokensPrompt: 'Prompt tokens',
    provenanceTokensCompletion: 'Completion tokens',
    provenanceTokens: 'Tokens',
    provenanceStrategy: 'Strategy',
    provenancePromptVersion: 'Prompt version',
    provenanceTokensSummary: '{{n}} tokens',
    provenanceCopyPrompt: 'Copy prompt',
    provenanceCopied: 'Copied!',
    // GenerationDetailsDialog – full "how this was generated" surface
    generationParamsHeading: 'Run parameters',
    generationCompositionHeading: 'Prompt composition',
    generationSystemPrompt: 'System prompt',
    generationSectionInstruction: 'Section instruction',
    generationArticleInserted: 'Full article text inserted here',
    generationArticleTokens: '{{n}} tokens',
    generationArticleTruncated: 'A budgeted subset of this text was sent',
    generationViewTextSent: 'View text sent',
    generationHideTextSent: 'Hide text sent',
    generationFieldsRequested: 'Requested fields ({{n}})',
    generationSplitCalls: 'Split across {{n}} calls',
    generationShowAll: 'Show all',
    generationShowLess: 'Show less',
    generationLegacyPrompt: 'Prompt sent',
    generationTextError: "Couldn't load the text. Retry",
    generationTextRetry: 'Retry',
    // AISuggestionEvidence – markdown-first citation locate
    evidenceLocate: 'Locate in document',
    evidenceLocatedInReader: 'Highlighted in the reader',
    // AISuggestionEvidence – multi-citation list + attribution badges
    evidenceAlsoCited: 'Also cited ({{n}})',
    attributionEntailed: 'Verified',
    attributionWeak: 'Weak match',
    attributionUnsupported: 'Not supported',
    attributionUngroundable: 'Verify manually',
    // Attribution badge tooltips — this grades whether the CITED QUOTE supports
    // the value, independent of the AI's confidence or its rationale.
    attributionTooltipEntailed:
      'The cited quote supports this value. This grades the quote — not the AI confidence or rationale.',
    attributionTooltipWeak:
      'The cited quote is related but does not clearly establish this value. This grades the quote, not whether the value is right — verify in the document.',
    attributionTooltipUnsupported:
      'The cited quote does not establish this value. This grades the quote, not the AI confidence or rationale — the value may still be correct, but verify it against the document.',
    attributionTooltipUngroundable:
      'The value could not be located in the document text (e.g. it appears only in a figure). Verify manually.',
    // useExtractionJob async polling toasts
    extractionJobFailedTitle: 'AI extraction failed',
    extractionJobCancelledTitle: 'AI extraction cancelled',
} as const;

export type ExtractionCopy = typeof extraction;
