/**
 * UI copy for extraction area. English only.
 */
export const extraction = {
    headerBlindMode: 'Blind mode',
    headerSaving: 'Saving…',
    headerSavedAt: 'Saved at',
    headerUnsavedChanges: 'Unsaved changes',
    headerSaveFailed: 'Save failed — will retry on next edit',
    headerProgressFields: 'fields complete',
    headerProgressOf: 'of',
    headerViewAllStatus: 'View all status',
    headerRole: 'Role',
    headerProgress: 'Progress',
    headerStatus: 'Status',
    // HeaderFinalizeButton
    headerFinalize: 'Finalize',
    headerFinalizing: 'Finalizing…',
    // HeaderPDFControls
    pdfHide: 'Hide PDF',
    pdfShow: 'Show PDF',
    pdfHideShort: 'Hide',
    pdfShowShort: 'Show',
    comparisonToggleAria: 'Toggle comparison mode',
    comparison: 'Comparison',
    // HeaderNavigation
    back: 'Back',
    articlePrevious: 'Previous article',
    articleNext: 'Next article',
    articleFirst: 'First article',
    articleLast: 'Last article',
    // ConfigureTemplateFirst
    configTemplateFirstTitle: 'Configure the template first',
    configTemplateFirstDesc: 'You need to configure the variables that will be extracted from articles. Go to the Configuration tab and choose:',
    configImportCharms: 'Import CHARMS template',
    configImportCharmsDesc: 'Use the official checklist for predictive model reviews',
    configCreateCustom: 'Create custom sections',
    configCreateCustomDesc: 'Define your own extraction variables',
    configGoToConfig: 'Go to Configuration',
    // ExtractionInterface tabs
    tabExtraction: 'Extraction',
    tabDashboard: 'Dashboard',
    tabConfiguration: 'Configuration',
    // ExtractionInterface dashboard
    dashboardArticles: 'Articles',
    dashboardInProject: 'in project',
    dashboardExtractionsStarted: 'Extractions Started',
    dashboardComplete: 'complete',
    dashboardArticlesInExtraction: 'articles in extraction',
    dashboardOverallProgress: 'Overall Progress',
    dashboardAverageCompleteness: 'average completeness',
    // Dense stat strip + completeness distribution bar
    dashboardStatInExtraction: 'In extraction',
    dashboardStatCompleted: 'Completed',
    dashboardStatAvgCompleteness: 'Avg. completeness',
    dashboardDistributionTitle: 'Completeness distribution',
    dashboardBucketNotStarted: 'Not started',
    dashboardBucketInProgress: 'In progress',
    dashboardBucketComplete: 'Complete',
    dashboardConfigureTitle: 'Configure your extraction template',
    dashboardConfigureDesc: 'To start extracting data, you need to configure the variables that will be collected.',
    dashboardYouCan: 'You can:',
    dashboardImportCharmsOption: 'Import the CHARMS template (official checklist)',
    dashboardCreateSectionsOption: 'Create your own sections and custom fields',
    dashboardConfigureButton: 'Configure',
    // ExtractionInterface configuration
    configPanelTitle: 'Configure your extraction template',
    configPanelDesc: 'Choose how you want to structure data extraction from articles',
    configImportCharmsTitle: 'Import CHARMS Template',
    configImportCharmsFullDesc: 'Use the official checklist for systematic reviews of predictive models. Includes 11 sections and 45 pre-configured fields following CHARMS guidelines.',
    configImportButton: 'Import',
    configCreateCustomTitle: 'Create Custom Template',
    configCreateCustomFullDesc: 'Define your own extraction sections and fields. Ideal for reviews with specific needs or different frameworks.',
    configCreateTemplateButton: 'Create Template',
    configManagersNote: 'Managers can configure templates',
    configManagersNoteDesc: 'If you are not a project manager, ask a manager to configure the extraction template before you start.',
    configContactManagerToConfigure: 'Only project managers can configure the extraction template. Contact the project manager to set up templates and start extracting.',
    configImportSectionTitle: 'Import template',
    configAvailableTemplates: 'Available templates',
    configNoTemplatesAvailable: 'No templates available at the moment.',
    configImportThisTemplate: 'Import',
    configImportTemplateButton: 'Import Template',
    configHeaderTitle: 'Template configuration',
    configSectionsCountOne: '{{n}} section · {{main}} main',
    configSectionsCountOther: '{{n}} sections · {{main}} main',
    configSubSectionsCountOne: '{{n}} sub-section',
    configSubSectionsCountOther: '{{n}} sub-sections',
    configSeeDetails: 'See details',
    // ExtractionInterface loading & error
    loadingTemplates: 'Loading templates',
    errorLoadTemplates: 'Error loading templates',
    errorLoadArticles: 'Error loading articles',
    errorLoadStats: 'Error loading extraction statistics',
    errors_saveValues: 'Error saving values',
    errors_autoSaveFailed: 'Error saving data automatically',
    errors_autoSaveUpdateValues: 'Error updating {{n}} values: {{message}}',
    errors_advanceFailed: 'Could not advance the extraction stage',
    // useSectionExtraction toasts
    sectionExtractionNoSuggestionsTitle: 'Extraction completed with no suggestions',
    sectionExtractionNoSuggestionsDesc: 'Extraction finished but no suggestions were created. Check that field names match exactly or that the PDF contains the expected data.',
    sectionExtractionSuccessTitle: 'Extraction completed! {{n}} suggestion(s) created for this section.',
    sectionExtractionTokensUsed: '{{n}} tokens used',
    sectionExtractionErrorTitle: 'Extraction error',
    sectionExtractionErrorFieldMismatch: 'Error: Field names do not match',
    sectionExtractionErrorFieldMismatchDesc: 'Extracted fields do not match the expected fields. Check the logs for details.',
    sectionExtractionErrorAuth: 'Authentication error',
    sectionExtractionErrorAuthDesc: 'Please sign in again.',
    sectionExtractionTimeoutDesc: 'Extraction took too long. Try again with a smaller PDF or extract sections individually.',
    errors_templateHasNoEntityTypes: 'Template has no entity types',
    // FullAIExtractionProgress
    fullAIProgressTitle: 'Full AI Extraction',
    fullAIProgressInProgress: 'AI extraction in progress…',
    fullAIProgressExtractingModels: 'Extracting models from article with AI…',
    fullAIProgressExtractingSections: 'Extracting top-level sections: {{label}}',
    fullAIProgressExtractingAllSections: 'Extracting sections from all models…',
    fullAIProgressRestore: 'Restore',
    fullAIProgressClose: 'Close',
    fullAIProgressMinimize: 'Minimize',
    // AISuggestionsPanel
    aiPanelNoTemplate: 'No template selected',
    aiPanelNoTemplateDesc: 'Select an extraction template to use AI suggestions',
    aiPanelNoArticle: 'No article selected',
    aiPanelNoArticleDesc: 'Select an article to generate AI suggestions',
    aiPanelTitle: 'AI Suggestions',
    aiPanelSubtitle: 'Use artificial intelligence to speed up data extraction',
    aiPanelRunAI: 'Run AI',
    aiPanelStatusTitle: 'AI Status',
    aiPanelStatusNotRun: 'Not started',
    aiPanelStatusNotRunDesc: 'Run AI to generate suggestions',
    aiPanelSuggestionsGenerated: 'Suggestions Generated',
    aiPanelSuggestionsPending: 'suggestions pending',
    aiPanelAcceptanceRate: 'Acceptance Rate',
    aiPanelSuggestionsAccepted: 'suggestions accepted',
    aiPanelSettingsTitle: 'Settings',
    aiPanelConfigureDesc: 'Configure how AI should process articles',
    aiPanelAIModelLabel: 'AI Model',
    aiPanelMinConfidenceLabel: 'Minimum Confidence',
    aiPanelFieldsForExtractionLabel: 'Fields for Extraction',
    aiPanelStudyInfo: 'Study basic information',
    aiPanelParticipantChars: 'Participant characteristics',
    aiPanelStatisticalMethods: 'Statistical methods',
    aiPanelResultsMetrics: 'Results and metrics',
    aiPanelHistoryTitle: 'AI extraction history',
    aiPanelHistoryDesc: 'Previous AI extractions for this article',
    aiPanelNoRunsFound: 'No AI extractions found',
    aiPanelNoRunsDesc: 'Run AI for the first time to generate suggestions',
    aiPanelSuggestionsCardTitle: 'Suggestions',
    aiPanelSuggestionsCardDesc: 'AI-generated suggestions for review',
    aiPanelNoSuggestionsAvailable: 'No suggestions available',
    aiPanelNoSuggestionsDesc: 'Run AI to generate value suggestions',
    aiPanelBatchActionsTitle: 'Batch Actions',
    aiPanelBatchActionsDesc: 'Quick actions for multiple suggestions',
    aiPanelAcceptAll: 'Accept All',
    aiPanelRejectAll: 'Reject All',
    aiPanelReprocess: 'Reprocess',
    // BatchExtractionProgress
    batchExtractingAllSections: 'Extracting all sections of the model',
    batchChunkOf: 'Chunk {{current}} of {{total}}',
    batchSectionsOf: 'Sections: {{completed}} of {{total}}',
    batchProcessing: 'Processing: {{name}}…',
    // Field/template management toasts
    errors_loadFields: 'Error loading fields',
    loadingFields: 'Loading fields…',
    fieldDescriptionPlaceholder: 'Describe what should be collected in this field…',
    fieldValidationFallback: 'Could not validate field',
    errorHandlerFallback: 'An unexpected error occurred',
    fieldOperationCreateFallback: 'Could not create field',
    fieldOperationEditFallback: 'Could not update field',
    fieldOperationDeleteFallback: 'Could not remove field',
    fieldOperationValidateFallback: 'Could not validate field',
    permissionDeniedOperation: 'You do not have permission to perform this action',
    validationErrorTitle: 'Validation error',
    validationInvalidData: 'Invalid data provided',
    errors_checkPermissions: 'Error checking permissions',
    errors_validateField: 'Error validating field',
    errors_addField: 'Error adding field',
    errors_updateField: 'Error updating field',
    errors_removeField: 'Error removing field',
    errors_reorderFields: 'Error reordering',
    errors_cloneTemplate: 'Error cloning template',
    errors_createTemplate: 'Error creating template',
    errors_updateTemplateStatus: 'Error updating status',
    templateClonedSuccess: 'Template "{{name}}" cloned successfully!',
    templateCreatedSuccess: 'Template "{{name}}" created successfully!',
    templateActivatedSuccess: 'Template activated successfully!',
    templateDeactivatedSuccess: 'Template deactivated successfully!',
    errors_loadSuggestions: 'Error loading suggestions',
    errors_acceptSuggestion: 'Error accepting suggestion',
    errors_rejectSuggestion: 'Error rejecting suggestion',
    errors_batchAcceptSuggestions: 'Error accepting suggestions in batch',
    errors_loadSuggestionsHistory: 'Error loading suggestion history',
    errors_loadInstances: 'Error loading instances',
    errors_createInstance: 'Error creating instance',
    errors_updateInstance: 'Error updating instance',
    errors_deleteInstance: 'Error deleting instance',
    errors_reorderInstances: 'Error reordering',
    entityTypeNotFound: 'Entity type not found',
    instanceUpdatedSuccess: 'Instance updated successfully!',
    cannotDeleteInstanceWithValues: 'Cannot delete instance that has extracted values',
    instanceDeletedSuccess: 'Instance deleted successfully!',
    instanceCreatedSuccess: 'Instance "{{label}}" created successfully!',
    instanceAlreadyExists: 'Instance already exists',
    instancesReorderSuccess: 'Instance order updated!',
    noSectionsForModel: 'No sections found for this model',
    modelExtractionErrorTitle: 'Extraction error',
    modelExtractionAuthErrorTitle: 'Authentication error',
    noModelsExtractionComplete: 'Extraction completed but no prediction models were found in the article.',
    noModelsToExtractSections: 'No models to extract sections from. Extract models first.',
    extractionMayTakeMinutes: 'This may take a few minutes',
    pdfMainNotFound: 'Main PDF not found for this article',
    pdfLoadErrorTitle: 'Error loading PDF',
    pdfLoadDocumentError: 'Error loading PDF document',
    fullAICompleteSuccessTitle: 'Full AI extraction complete!',
    fullAISuccessDescription: '{{n}} model(s) processed with all sections extracted.',
    fullAITopLevelSections: '{{n}} top-level section(s) extracted.',
    fullAIPartialTitle: 'Extraction partially complete',
    fullAIPartialTopLevelFailed: 'Prediction models were extracted, but study-level sections failed and were not saved. Re-run extraction to retry them.',
    fullAIErrorPrefix: 'Error in full AI extraction',
    modelExtractionCompleteNoModels: 'Model extraction completed but no prediction models were found.',
    modelExtractionSuccessTitle: 'Extraction complete! {{n}} model(s) found and created.',
    modelExtractionSuccessTokens: '{{n}} tokens used',
    noModelsFoundTitle: 'No models found',
    errors_loadExtractionData: 'Error loading data',
    errors_loadExtractedValues: 'Error loading extracted values',
    errors_updateLabel: 'Error updating label',
    labelUpdatedSuccess: 'Label updated successfully',
    processingArticle: 'Processing article {{current}}/{{total}}: {{title}}',
    zoteroImportCompletedWithErrors: 'Import completed with errors',
    modelNotAuthenticatedOrInvalid: 'User not authenticated or invalid template',
    modelEntityTypeNotFound: 'Model entity type not found',
    errors_createModel: 'Error creating model',
    errors_removeModel: 'Error removing model',
    errors_topLevelSectionsExtraction: 'Error in top-level sections extraction',
    errors_allSectionsExtraction: 'Error in extraction of all sections',
    batchSectionExtractionSuccess: 'Extraction complete! {{n}} section(s) extracted successfully.',
    batchSectionExtractionSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchSectionExtractionPartial: 'Extraction partially complete: {{success}}/{{total}} section(s) extracted successfully.',
    batchSectionExtractionPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} section(s) failed. Check the logs for details.',
    errors_sectionsExtraction: 'Error in section extraction',
    modelCreatedSuccess: 'Model "{{label}}" created successfully!',
    modelRemovedSuccess: 'Model "{{label}}" removed successfully',
    errors_zoteroFetch: 'Error fetching Zotero collections',
    errors_zoteroImport: 'Error importing articles',
    zoteroDisconnectSuccess: 'Zotero integration removed',
    zoteroDisconnectError: 'Error removing integration',
    zoteroImportCompleteSuccess: 'Import complete! {{imported}} imported, {{updated}} updated',
    zoteroImportPdfsDownloaded: ', {{n}} PDFs downloaded',
    zoteroConnectionSuccess: 'Connection successful! User: {{name}}',
    zoteroConnectionFailed: 'Failed to connect to Zotero',
    zoteroTestConnectionError: 'Error testing connection',
    zoteroCredentialsSavedSuccess: 'Credentials saved successfully!',
    zoteroCredentialsSaveError: 'Error saving credentials',
    noTopLevelSectionsFound: 'No top-level sections found to extract',
    zoteroProgressFetching: 'Fetching articles from Zotero…',
    zoteroProgressFetchingCount: 'Fetching articles… {{current}}/{{total}}',
    zoteroProgressProcessing: 'Processing articles…',
    zoteroProgressProcessingCount: 'Processing {{current}}/{{total}}…',
    zoteroProgressProcessingWithPdfs: 'Processing and downloading PDFs… {{current}}/{{total}}',
    zoteroProgressComplete: 'Import complete!',
    zoteroProgressError: 'Import error',
    zoteroItemNoTitle: 'Item has no title',
    zoteroItemTitleFallback: 'No title',
    newInstanceLabel: 'New instance',
    batchAcceptCountToast: '{{n}} suggestion(s) accepted in batch',
    noSuggestionConfidenceToast: 'No suggestions with confidence ≥{{pct}}%',
    errors_extractionError: 'Extraction error',
    errors_extractionAuth: 'Authentication error',
    errors_noPermissionAddField: 'You do not have permission to add fields',
    errors_noPermissionEditField: 'You do not have permission to edit fields',
    errors_noPermissionRemoveField: 'You do not have permission to remove fields',
    errors_noPermissionReorderField: 'You do not have permission to reorder fields',
    onlyManagersCanAddFields: 'Only managers can add fields',
    onlyManagersCanEdit: 'Only managers can edit',
    onlyManagersCanDelete: 'Only managers can delete',
    advancedEditHint: 'Advanced edit (type, unit, etc.)',
    fieldsOfThisSection: 'Fields in this section',
    reordering: 'Reordering…',
    errors_fieldExistsInSection: 'A field with the name "{{name}}" already exists in this section',
    errors_validationPrefix: 'Validation: {{message}}',
    errors_cannotRemoveField: 'This field cannot be removed',
    errors_cannotChangeFieldType: 'Cannot change field type when it already has extracted data',
    errors_cannotRemoveFieldWithData: 'Cannot remove field "{{label}}" because it has {{n}} extracted value(s)',
    // ExtractionErrorBoundary
    errorBoundaryTitle: 'Extraction error',
    errorBoundaryDescription: 'An unexpected error occurred. You can try to recover or go back to the home page.',
    errorBoundaryDetailsLabel: 'Error details:',
    errorBoundaryUnknown: 'Unknown error',
    errorBoundaryTryAgain: 'Try again',
    errorBoundaryBackToHome: 'Back to home',
    errorBoundaryExportLogs: 'Export logs',
    errorBoundarySuggestionsTitle: 'Suggestions:',
    errorBoundarySuggestionReload: 'Reload the page (F5)',
    errorBoundarySuggestionCache: 'Clear your browser cache',
    errorBoundarySuggestionConnection: 'Check your internet connection',
    errorBoundarySuggestionSupport: 'If the error persists, export the logs and contact support',
    fieldAddedSuccess: 'Field "{{label}}" added successfully!',
    fieldUpdatedSuccess: 'Field updated successfully!',
    fieldRemovedSuccess: 'Field removed successfully!',
    fieldsReorderSuccess: 'Field order updated!',
    // Article extraction list/table shared strings
    listStatusNotStarted: 'Not started',
    listStatusComplete: 'Complete',
    listStatusInProgress: 'In progress',
    listTryAgain: 'Try again',
    listNoArticles: 'No articles found in this project',
    listNoArticlesDesc: 'Add articles first to start data extraction.',
    // HeaderMoreMenu
    moreOptions: 'More options',
    moreActions: 'Actions',
    moreExtractAI: 'Extract with AI',
    moreExtractingAI: 'Extracting with AI…',
    moreOpenQA: 'Open Quality Assessment',
    moreKeyboardShortcuts: 'Keyboard Shortcuts',
    moreHelp: 'Help',
    moreShortcutsDialogTitle: 'Keyboard Shortcuts',
    moreShortcutsDialogDesc: 'Shortcuts available in the extraction interface',
    moreShortcutSave: 'Save manually',
    moreShortcutSearch: 'Search',
    moreShortcutCancel: 'Cancel action',
    moreShortcutNextField: 'Next field',
    moreShortcutPrevField: 'Previous field',
    moreShortcutTip: 'Tip: Press ? to view this list quickly',
    // HeaderAIActions
    aiSuggestionPending: 'AI suggestion pending',
    aiSuggestionsPending: 'AI suggestions pending',
    aiClickToView: ' — Click to view',
    // ArticleExtractionTable (toast)
    tableErrorLoadArticles: 'Error loading articles',
    tableSelectAtLeastOne: 'Select at least one article',
    tableErrorProcessAI: 'Error processing AI extraction',
    tableErrorUnknown: 'Unknown error',
    batchChunkedSuccessTitle: 'Extraction complete! {{n}} section(s) extracted successfully.',
    batchChunkedSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchChunkedPartialTitle: 'Extraction partially complete: {{success}}/{{total}} section(s) extracted successfully.',
    batchChunkedPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} section(s) failed. {{tokens}} tokens used.',
    batchAllModelsSuccessTitle: 'Extraction complete! Sections extracted from {{n}} model(s) successfully.',
    batchAllModelsSuccessDesc: '{{suggestions}} suggestion(s) created. {{tokens}} tokens used in {{duration}}s',
    batchAllModelsPartialTitle: 'Extraction partially complete: {{success}}/{{total}} model(s) processed successfully.',
    batchAllModelsPartialDesc: '{{suggestions}} suggestion(s) created. {{failed}} model(s) failed. {{tokens}} tokens used.',
    zoteroImportStarting: 'Starting import…',
    zoteroImportCancelled: 'Import cancelled',
    configNoGlobalTemplates: 'No global templates available',
    sectionLabelLabel: 'Section label *',
    sectionDescriptionOptional: 'Description (optional)',
    sectionTypeLabel: 'Section type *',
    sectionTypeSingle: 'Single section',
    sectionTypeMultiple: 'Multiple sections',
    sectionRequiredLabel: 'Required section',
    addFirstFieldInSectionAria: 'Add first field in this section',
    evidenceCited: 'Cited evidence',
    otherOptionInlineHint: 'Shows inline option and contextual input',
    noFieldsInSection: 'No fields in this section',
    addFirstFieldButton: 'Add first field',
    pageLabel: 'Page {{n}}',
    tableNoArticlesInProject: 'No articles found in this project',
    tableNoArticles: 'No articles found',
    // ImportTemplateDialog
    importTitle: 'Import Global Template',
    importDesc: 'Select a standardized template to use in your project.',
    importLoadingTemplates: 'Loading templates…',
    importNoTemplates: 'No global templates available at the moment.',
    importSections: 'sections',
    importTemplateSelected: 'Selected template:',
    importTemplateSelectedDetail: 'with pre-configured sections. All sections and fields will be imported to your project.',
    importCancel: 'Cancel',
    importImporting: 'Importing…',
    importImportButton: 'Import Template',
    importErrorSelect: 'Select a template to import',
    importErrorImport: 'Error importing template',
    importSuccess: 'Template imported successfully',
    // CreateCustomTemplateDialog
    createTitle: 'Create Custom Template',
    createDesc: 'Create an empty template and add custom sections and fields',
    createNameLabel: 'Template Name',
    createNamePlaceholder: 'e.g. Custom Extraction - Diabetes',
    createNameDesc: 'Descriptive name to identify this template',
    createDescriptionLabel: 'Description',
    createDescriptionPlaceholder: 'Describe the purpose of this template…',
    createDescriptionDesc: 'Explain what data will be extracted and for what purpose',
    createFrameworkLabel: 'Base Framework',
    createFrameworkPlaceholder: 'Select a framework',
    createFrameworkCustom: 'Custom',
    createFrameworkCharms: 'CHARMS (customized)',
    createFrameworkPicos: 'PICOS (customized)',
    createFrameworkDesc: 'Conceptual base of the template (can be CUSTOM if fully custom)',
    createCreating: 'Creating…',
    createTemplateButton: 'Create Template',
    createAuthRequired: 'You must be signed in',
    createSuccessCreated: 'Template created successfully!',
    createInfoAddSections: 'Now add sections and fields in the Setup tab',
    createErrorCreate: 'Error creating template',
    createValidationNameMin: 'Name must be at least 3 characters',
    createValidationNameMax: 'Name must be at most 100 characters',
    createValidationDescMax: 'Description must be at most 500 characters',
    createValidationFramework: 'Select a framework',
    examplePlaceholder: 'e.g. Extract the total number of participants at baseline, before exclusions…',
    noDescription: 'No description',
    historySuggestionsAria: 'Suggestion history',
    // ArticleExtractionTable (columns, filters, actions)
    tableFilterAllStatus: 'All statuses',
    tableColumnTitle: 'Title',
    tableColumnYear: 'Year',
    tableColumnProgress: 'Progress',
    tableColumnStatus: 'Status',
    tableColumnAuthors: 'Authors',
    tableColumnCreatedAt: 'Created at',
    tableColumnField: 'Field',
    tableFilterSelectStatus: 'Select status…',
    tableSearchTitle: 'Search in title…',
    tableSearchYearPlaceholder: 'e.g. 2023, 2020-2024…',
    tableSearchProgressPlaceholder: 'e.g. complete, in progress, 50…',
    tableSearchAuthor: 'Search author…',
    tableSearchPlaceholder: 'Search…',
    tableClearFilter: 'Clear',
    tableSearchAllFields: 'Search in all fields…',
    tableSearchPlaceholderShortcut: 'Search… (⌘F / Ctrl+F)',
    tableShortcutFilter: 'Filter (F)',
    tableShortcutSearch: 'Search (⌘F / Ctrl+F)',
    tableDisplayAndSort: 'Display & sort',
    tableOrdering: 'Ordering',
    tableDisplayOptions: 'Display options',
    tableClearAll: 'Clear all',
    tableRemoveFilter: 'Remove filter {{label}}',
    tableSelectArticleAria: 'Select article: {{title}}',
    tableOpenRowAria: 'Open extraction for {{title}}',
    tableStatusLegendAria: 'Status legend',
    tableArticlesCount: 'articles',
    tableSelectFiltered: 'Select filtered articles',
    tableSelectAll: 'Select all articles',
    tableActions: 'Actions',
    tableActionOpen: 'Open',
    tableStart: 'Start',
    tableView: 'View',
    tableContinue: 'Continue',
    tableAdjustFilters: 'Try adjusting the search filters.',
    tableClearFilters: 'Clear filters',
    tableBatchAIStarting: 'Starting AI extraction for {{count}} article(s)…',
    tableArticleSelected: 'article selected',
    tableArticlesSelected: 'articles selected',
    tableSelectionMenuTooltip: 'Actions menu for selected articles',
    tableBatchActionsLabel: 'Batch actions',
    tableAIExtraction: 'AI extraction',
    tableExport: 'Export',
    tableInDevelopment: 'In development',
    tableClearSelection: 'Clear selection',
    // AI suggestion history popover
    historyExtractionRun: 'Extraction',
    historyProcessing: 'Processing…',
    // AISuggestionHistoryPopover
    historyInvalidDate: 'Invalid date',
    historySuggestionsTitle: 'Suggestion history',
    historySuggestionsCount: 'suggestion(s) found',
    historyNoSuggestions: 'No previous suggestions found',
    suggestionAccepted: 'Accepted',
    suggestionRejected: 'Rejected',
    aiAccepted: 'AI accepted',
    acceptButton: 'Accept',
    rejectButton: 'Reject',
    toastSuggestionAcceptedSuccess: 'Suggestion accepted successfully',
    toastSuggestionRejectedSuccess: 'Suggestion rejected',
    emptyValue: '(empty)',
    // FieldInput
    fieldRequired: 'Required field',
    fieldUnitLabel: 'Unit',
    fieldMustBeNumber: 'Value must be a number',
    valuesCommaSeparated: 'Comma-separated values',
    yes: 'Yes',
    no: 'No',
    defaultUnit: '(default)',
    // AISuggestionsPanel
    panelNotRun: 'Not started',
    panelNoSuggestions: 'No suggestions available',
    panelBatchActions: 'Batch actions',
    panelBatchActionsDesc: 'Quick actions for multiple suggestions',
    // AddFieldDialog / EditFieldDialog / Fields
    addFieldTitle: 'Add New Field',
    addFieldDescInSection: 'Add a new field to section',
    addFieldDescDefault: 'Create a new field to collect data from articles',
    otherSpecifyDefault: 'Other (specify)',
    fieldTypeBoolean: 'Yes/No',
    fieldTypeText: 'Text',
    fieldTypeNumber: 'Number',
    fieldTypeDate: 'Date',
    fieldTypeSelect: 'Selection',
    fieldTypeMultiselect: 'Multiple choice',
    fieldsListAria: 'Extraction fields list',
    fieldNumberAria: 'Field number',
    editFieldDescriptionAria: 'Edit description for field {{label}}',
    editFieldLabelAria: 'Edit label for field {{label}}',
    fieldRequiredAria: 'Field {{label}} is required',
    saveFieldChangesAria: 'Save changes for field {{label}}',
    cancelFieldEditAria: 'Cancel editing field {{label}}',
    actionsForFieldAria: 'Actions for field {{label}}',
    firstUnitDefault: 'First unit is the default/suggested. Leave empty for automatic suggestions.',
    unitsAvailableHint: 'Available units: configure the options that will appear for the reviewer (first is default)',
    firstUnitDefaultShort: 'First unit is the default. Leave empty for automatic suggestions.',
    cannotChangeTypeValues: 'Cannot change this field type because it has {{count}} extracted values.',
    // RemoveModelDialog
    removeModelAnyway: 'Yes, remove anyway',
    removeModel: 'Remove model',
    // DeleteFieldConfirm
    cannotDelete: 'Cannot delete',
    // AllowedUnitsList
    firstIsDefault: 'First is default',
    orAddCustomFirstDefault: 'or add custom units above. The first unit will be the default.',
    unitsEmptyHint: 'Leave empty to use automatic suggestions based on context, or add custom units above. The first unit will be the default.',
    // TemplateManager
    cloneError: 'Could not clone the selected template.',
    cloneOrCreateDesc: 'Clone a default template or create a custom one',
    cloneOneOrCreate: 'Clone a default template or create a custom one to get started',
    defaultTemplatesAvailable: 'Default templates available for cloning',
    runMigrationsHint: 'Run Supabase migrations to populate the database (CHARMS, PICOS, etc.)',
    updateList: 'Refresh list',
    cloneTemplateTitle: 'Clone template',
    chooseTemplateToClone: 'Choose a global template to clone',
    comingSoon: 'This feature will be available soon',
    cloneButton: 'Clone',
    createButton: 'Create',
    createCustomTemplateDesc: 'Create a custom template for this project',
    sectionsConfigured: 'sections configured',
    // RemoveModelDialog
    removeModelTitle: 'Remove model',
    removeModelDesc: 'You are about to remove the model "{{name}}"',
    removeModelWarningTitle: 'Warning: This model contains extracted data!',
    removeModelFieldFilled: 'field is filled',
    removeModelFieldsFilled: 'fields are filled',
    removeModelDataPermanent: 'All extracted data will be permanently removed and cannot be recovered.',
    removeModelNoData: 'This model has no extracted data. Removal will not affect other models or study-level sections.',
    removeModelWhatRemoved: 'What will be removed:',
    removeModelSubsections: 'All sub-sections of this model (Candidate Predictors, Final Predictors, etc.)',
    removeModelAllValues: 'All extracted values ({{count}} fields)',
    removeModelRemoving: 'Removing…',
    removeModelError: 'Error removing model',
    removeSection: 'Remove section',
    removeSectionDesc: 'This action cannot be undone. All related data will be permanently lost.',
    analyzingImpact: 'Analyzing impact…',
    sectionToBeRemoved: 'Section to be removed:',
    fieldsLabel: 'Fields',
    instancesLabel: 'Instances',
    dataLabel: 'Data',
    removalImpactTitle: 'Removal impact:',
    confirmationLabel: 'Confirmation *',
    confirmRemovalHint: 'To confirm removal, type the section name exactly as shown above.',
    removingLabel: 'Removing…',
    noUnitsConfigured: 'No units configured',
    loadingGlobalTemplates: 'Loading global templates…',
    createCustomTemplateTitle: 'Create custom template',
    loadingConfiguration: 'Loading configuration…',
    noSectionsConfigured: 'No sections configured',
    noStudyLevelFields: 'No study-level fields configured in the template.',
    noModelsAdded: 'No models added',
    noModelsAddedDesc: 'Add a model manually or extract it automatically from the article.',
    // RunHeader
    runHeaderRevision: 'Revision',
    extractWithAI: 'Extract with AI',
    runHeaderGateRemaining: '{{count}} left',
    runHeaderRequiredOfTotal: '{{done}} of {{total}} required',
    runHeaderReviewersDiffer: '{{count}} differ',
    runHeaderBlindSuffix: 'blind',
    runHeaderRevealedSuffix: 'revealed',
    runHeaderReveal: 'Reveal reviewers',
    runHeaderBlindExplainer: "You're blind to reviewers' values for this kind.",
    runHeaderMore: 'More options',
    runHeaderTogglePanel: 'Toggle source panel',
    runHeaderSaved: 'Saved',
    runHeaderSaving: 'Saving…',
    runHeaderSaveFailed: 'Save failed',
    // Section navigation rail
    sectionNavRequiredLeft: '{{count}} required left',
    sectionNavComplete: 'All required fields complete',
    sectionNavAria: 'Section navigation',
    noFieldsInThisSection: 'No fields in this section',
    errorCalculatingProgress: 'Error calculating progress',
    loadingComparison: 'Loading comparison…',
    requiredLabel: 'Required',
    // EditFieldDialog (extra)
    configureUnitsDesc: 'Configure the units the reviewer can choose during extraction.',
    changesAffectNewOnly: 'Changes will only affect new extractions ({{count}} existing values).',
    // DeleteFieldConfirm
    confirmDeleteTitle: 'Confirm deletion',
    deleteField: 'Delete field',
    deleteFieldButton: 'Delete field',
    quickEdit: 'Quick edit',
    fullEdit: 'Full edit',
    understood: 'Understood',
    deleteFieldWarningUndo: 'This action cannot be undone',
    deleteFieldWarningRemoved: 'The field will be permanently removed from the section',
    deleteFieldWarningNewArticles: 'New articles will no longer have this field',
    deleteFieldWarningExisting: 'Already started articles will not be affected (structure preserved)',
    cannotDeleteReason: 'This field has {{count}} extracted values',
    cannotDeleteAffects: 'Affects {{count}} article(s) in extraction',
    cannotDeleteWouldLose: 'Deleting would cause data loss and inconsistencies',
    alternativesTip: 'Alternatives:',
    markNotRequired: 'Mark as "not required" instead of deleting',
    deleteValuesFirst: 'Delete extracted values first (with care)',
    contactAdmin: 'Contact the administrator',
    youAreTryingToDelete: 'You are trying to delete the field:',
    impossibleToDelete: 'Cannot delete:',
    exportButton: 'Export',
    // UnitEditor
    unitPlaceholder: 'e.g. years, kg, %, mmHg (or leave empty)',
    unitSuggestionsButton: 'Suggestions',
    unitSearchPlaceholder: 'Search unit…',
    unitNoneFound: 'No unit found',
    // FieldsHeader
    addFieldAria: 'Add new field',
    addFieldButton: 'Add Field',
    // AddFieldDialog / EditFieldDialog placeholders
    placeholderLabelExample: 'e.g. Participant Age',
    placeholderNameExample: 'e.g. participant_age',
    selectTypePlaceholder: 'Select type',
    // AddSectionDialog
    placeholderSectionNameExample: 'e.g. exclusion_criteria',
    // ModelSelector / AddModelDialog
    selectModelPlaceholder: 'Select a model…',
    modelNamePlaceholder: 'e.g. Logistic Regression, Random Forest, XGBoost…',
    modelDescriptionPlaceholder: 'e.g. Supervised learning, Neural network…',
    modelNameLabel: 'Model name',
    modelNameHint: 'Choose a descriptive name to identify this model',
    modellingMethodLabel: 'Modelling method',
    modellingMethodOptional: '(optional)',
    modellingMethodHint: 'You can fill this in later during extraction',
    modelSelectorTitle: 'Prediction models',
    modelSelectorDesc: 'Select a model to extract its data',
    modelExtractAITitle: 'Extract models automatically with AI',
    modelExtractAIShort: 'Extract with AI',
    modelExtractModelsOnly: 'Extract models only',
    modelExtractAllSections: 'Extract sections from all models',
    modelAddManuallyTitle: 'Add new model manually',
    modelNewShort: 'New',
    modelRemoveActiveTitle: 'Remove active model',
    modelActiveLabel: 'Active model',
    // TemplateManager
    templateManageTitle: 'Manage templates',
    templateManageDesc: 'Clone default templates or create custom ones',
    templateGlobalTitle: 'Global Templates',
    templateGlobalDesc: 'Default templates available for cloning',
    templateCloneButton: 'Clone template',
    templateCreateButton: 'Create template',
    templateProjectTemplates: 'Project templates',
    templateProjectDesc: 'Active templates available for this project',
    templateNoneFound: 'No template found',
    templateNoneHint: 'Clone a default template or create a custom one to get started',
    templateCreatedAt: 'Created on',
    // SectionAccordion
    sectionNoInstances: 'No instances created for this section',
    sectionAddInstance: 'Add',
    // AllowedUnitsList
    unitMoveUp: 'Move up',
    unitMoveDown: 'Move down',
    unitRemove: 'Remove',
    // AISuggestionEvidence
    copyCopied: 'Copied!',
    copySnippet: 'Copy snippet',
    // PDF / UI aria
    zoomPercentageAria: 'Zoom percentage',
    searchDocumentAria: 'Search in document',
    removeFileAria: 'Remove file',
    placeholderTypeHere: 'Type here',
    allowOtherSpecifyLabel: 'Allow "Other (specify)"',
    otherLabelLabel: '"Other" label',
    placeholderLabel: 'Placeholder',
    fieldPlaceholderEnter: 'Enter {{label}}',
    // EditFieldDialog
    editFieldTitle: 'Edit Field',
    editFieldDescInSection: 'Editing field {{label}} in section {{section}}',
    editFieldDescDefault: 'Edit settings for field {{label}}',
    editFieldBasicInfo: 'Basic Information',
    editFieldTechnicalName: 'Technical name',
    editFieldTechnicalNameHint: 'Internal name (cannot be changed after creation)',
    editFieldTypeLabel: 'Field type',
    editFieldDescription: 'Description',
    editFieldDescriptionHint: 'Instructions to help reviewers',
    editFieldLLMInstruction: 'AI instruction (optional)',
    editFieldLLMInstructionDesc: 'Specific instruction for AI extraction. Describe WHAT to extract and WHERE to find it in the article.',
    editFieldRequired: 'Required field',
    editFieldRequiredDesc: 'Check if this field must be filled in',
    editFieldSpecificSettings: 'Specific settings',
    editFieldUnitsAvailable: 'Available units (optional)',
    allowedValuesLabel: 'Allowed values',
    editFieldCancel: 'Cancel',
    editFieldSaveChanges: 'Save changes',
    editFieldWarningExtracted: 'Attention: This field has {{count}} extracted values in {{n}} article(s). Some changes may not be allowed.',
    fieldExtractedValuesMessage: 'This field has {{count}} extracted values in {{n}} article(s).',
    fieldSafeToModifyMessage: 'Field can be modified safely.',
    addFieldTipsTitle: 'Tips:',
    addFieldTipName: 'Technical name is auto-generated from the label',
    addFieldTipUnitsEmpty: 'Leave units empty to use automatic suggestions based on context',
    addFieldTipSelectOptions: 'For selection fields, define at least 2 options',
    // Placeholders and inline UI (FieldInput, dialogs)
    selectFieldPlaceholder: 'Select {{label}}',
    addInstanceLabel: 'Add {{label}}',
    sectionConfirmPlaceholder: 'Type "{{name}}" to confirm',
    createModel: 'Create model',
    addNewModel: 'Add new model',
    addNewModelDesc: 'Create a new prediction model to extract its data. You can add as many models as you need.',
    modelsAlreadyAdded: 'Models already added:',
    creating: 'Creating…',
    addManually: 'Add manually',
    addFirstFieldFull: 'Add first field',
    addSection: 'Add section',
    addNewSection: 'Add new section',
    createSection: 'Create section',
    onlyManagersEditDelete: 'Only managers can edit or delete',
    typeAbovePressEnter: 'Type above and press Enter or click',
    dragToReorder: 'Drag to reorder',
    noOptionsAddedYet: 'No options added yet',
    addFieldButtonLabel: 'Add field',
    selectTemplateToStart: 'Select an extraction template to get started',
    selectInstance: 'Select an instance',
    clickInstanceToEdit: 'Click an instance above to edit its fields',
    instanceEditorTitle: 'Instance editor',
    instanceEditorDesc: 'Manage entity instances for template {{name}}',
    noTemplateSelected: 'No template selected',
    newInstance: 'New instance',
    totalInstances: 'Total instances',
    instancesCreated: 'instances created',
    valuesExtracted: 'Values extracted',
    valuesFilled: 'values filled',
    completeness: 'completeness',
    progressLabel: 'Progress',
    instancesCardTitle: 'Instances',
    instancesCardDesc: 'Entity instances created for extraction',
    loadingInstances: 'Loading instances…',
    noInstancesCreated: 'No instances created',
    createInstancesToStart: 'Create entity instances to start extracting data',
    createFirstInstance: 'Create first instance',
    valuesFilledCount: 'values filled',
    complete: 'complete',
    fieldEditorTitle: 'Field editor',
    fieldEditorDesc: 'Fill in values for the selected instance',
    // ExtractionExportDialog (009-extraction-excel-export)
    exportDialogTitle: 'Export extraction data',
    exportDialogSubtitle: 'Export extracted data from the active template as an Excel workbook (.xlsx).',
    exportSourceLabel: 'Source of values',
    exportSourceConsensus: 'Consensus',
    exportSourceConsensusDesc: 'Canonical post-consensus values for finalized articles.',
    exportSourceSingleUser: 'Single user',
    exportSourceSingleUserDesc: 'Latest non-reject decisions for one reviewer.',
    exportSourceAllUsers: 'All users',
    exportSourceAllUsersDesc: 'Consensus plus one column per reviewer (manager only).',
    exportSourceAllUsersDisabledTooltip: 'Only project managers can export all reviewers side-by-side.',
    exportReviewerLabel: 'Reviewer',
    exportReviewerSelfFallback: 'Only your own decisions are available — your role does not allow exporting other reviewers.',
    exportReviewerEmptyState: 'No reviewer has recorded decisions on this template yet, so there is nothing to export for a single user. Run extraction and review first, or pick another source.',
    exportScopeLabel: 'Articles to export',
    exportScopeCurrentList: 'Current list',
    exportScopeSelectedOnly: 'Selected only',
    exportAdditionalLabel: 'Additional content',
    exportIncludeAiMetadata: 'Include AI metadata sheet',
    exportIncludeAiMetadataDesc: 'Adds a flat sheet listing every AI proposal with confidence, rationale, evidence, and reviewer outcome.',
    exportAnonymizeReviewers: 'Anonymize reviewer names',
    exportAnonymizeReviewersDesc: 'Replace reviewer names with Reviewer A / B / … in the exported file. Useful when sharing the file outside your team.',
    exportEmptyConsensusReason: 'No finalized data to export yet.',
    exportEmptySingleUserReason: 'No decisions recorded yet for this reviewer.',
    exportEmptyAllUsersReason: 'No reviewer decisions recorded yet.',
    exportEmptyNoArticlesReason: 'No articles in scope — adjust filters or pick a different article scope.',
    exportConfirm: 'Export',
    exportGenerating: 'Generating…',
    exportRetry: 'Retry',
    exportCancel: 'Cancel',
    exportSuccessToast: 'Export downloaded.',
    exportStartedToast: 'Export started — we will notify you when it is ready.',
    exportFailedToast: 'Export failed.',
    exportFilenamePreviewLabel: 'File',
    exportPreviewLineFmt: 'Will export {articles} articles × {fields} fields → {delivery}',
    exportPreviewLineNoFieldsFmt: 'Will export {articles} articles → {delivery}',
    exportPreviewDeliveryInline: 'inline download',
    exportPreviewDeliveryAsync: 'background job',
    // FieldsTable / FieldsManagerWithDragDrop column headers
    typeColumn: 'Type',
    fieldColumn: 'Field',
    requiredColumn: 'Required',
    technicalName: 'Technical name',
    fieldsCountLabel: 'field(s)',
    fieldLabelPlaceholder: 'Field label',
    // TemplateConfigEditor section card labels
    typeLabel: 'Type',
    cardinalityUnique: 'Unique',
    cardinalityMultiple: 'Multiple',
    subSections: 'Subsections',
    editLabelButton: 'Edit label',
    removeButton: 'Remove',
    // QualityAssessmentInterface / dashboard
    dashboardProgress: 'Progress',
    sectionSingle: 'section',
    sectionMultiple: 'sections',
    // AddSectionDialog – validation messages
    nameRequired: 'Name is required',
    nameMin2: 'Name must be at least 2 characters',
    nameMax50: 'Name must be at most 50 characters',
    nameFormat: 'Invalid name format',
    labelRequired: 'Label is required',
    labelMin2: 'Label must be at least 2 characters',
    labelMax100: 'Label must be at most 100 characters',
    descriptionMax500: 'Description must be at most 500 characters',
    cardinalityRequired: 'Required',
    sectionCreatedSuccess: 'Section "{{label}}" created successfully',
    sectionCreateError: 'Error creating section',
    placeholderSectionLabel: 'Section label',
    placeholderSectionDescription: 'Section description',
    // AllowedUnitsList
    enterUnit: 'Enter a unit',
    unitAlreadyAdded: 'Unit already added',
    max20Units: 'At most 20 units',
    placeholderUnits: 'Enter units',
    suggestionsButton: 'Suggestions',
    searchUnit: 'Search unit',
    noUnitFound: 'No unit found',
    unitLabel: 'Unit',
    // AllowedValuesList
    enterValue: 'Enter a value',
    valueAlreadyAdded: 'Value already added',
    max100Values: 'At most 100 values',
    placeholderOptions: 'Enter options',
    // RemoveSectionDialog – impact analysis
    sectionAnalyzeError: 'Error analyzing section',
    sectionErrorAnalyzing: 'Error analyzing section',
    sectionEmptySafe: 'This section is empty and safe to remove',
    sectionWarnDataLost: 'This data will be permanently lost ({{count}} value(s))',
    sectionWarnFieldsRemoved: '{{count}} field(s) will be removed',
    sectionWarnInstancesRemoved: '{{count}} instance(s) will be removed',
    confirmSectionName: 'Type the section name to confirm',
    confirmSectionNameExact: 'The name must match exactly: {{name}}',
    sectionRemovedSuccess: 'Section "{{name}}" removed successfully',
    sectionRemoveError: 'Error removing section',
    // SectionAccordion – AI extraction buttons
    extractSectionWithAI: 'Extract {{label}} with AI',
    extractAllSectionsWithAI: 'Extract all sections with AI',
    extractingWithAI: 'Extracting with AI…',
    extractingAllSectionsWithAI: 'Extracting all sections with AI…',
    createInstanceBeforeExtract: 'Create an instance before extracting',
    // AddModelDialog – validation & errors
    modelCreateError: 'Error creating model',
    modelNameEmpty: 'Model name cannot be empty',
    modelNameMinLength: 'Model name must be at least 2 characters',
    modelNameDuplicate: 'A model with this name already exists',
    // AISuggestionDisplay / AISuggestionDetailsPopover – evidence accessibility
    aiEvidenceClickTitle: 'Click to view evidence',
    aiEvidenceClickAria: 'View evidence for this suggestion',
    evidenceCitedAria: 'Cited evidence',
    // AISuggestionEvidence – citation highlight
    evidenceNotLocated: "Couldn't locate in source",
    evidenceJumpToSource: 'Jump to source in PDF',
    // CitationLiveRegion – aria-live jump announcement
    citationJumpAnnouncement: 'Jumped to cited source on page {{n}}',
    // CitationOverlay – focusable active highlight box
    citationHighlightLabel: 'Cited source highlight',
} as const;

export type ExtractionCopy = typeof extraction;
