/**
 * UI copy for AI connections (spec §5.2): the Integrations list and form,
 * the worklist engine picker, and the project AI engine card. English only.
 */
export const llmConnections = {
    // --- Integrations → AI connections ---
    integrationsTitle: 'AI connections',
    integrationsDescription: 'Your own keys and hosts for AI providers. Encrypted, never shared.',
    listLoading: 'Loading connections…',
    listEmpty: 'No AI connections yet',
    listLoadError: "Couldn't load your connections.",
    retry: 'Retry',
    addButton: 'Add connection',
    providerLabel: 'Provider',
    providerPlaceholder: 'Select provider',
    docsLink: 'How to get a key?',
    keyLabel: 'API key',
    keyPlaceholder: 'sk-…',
    keyOptionalPlaceholder: 'Leave blank for a keyless host',
    hostLabel: 'Base URL',
    hostHint: 'HTTPS only, reachable from the internet.',
    labelLabel: 'Label',
    labelPlaceholder: 'e.g. Personal key',
    saveButton: 'Save connection',
    saving: 'Saving…',
    cancelButton: 'Cancel',
    statusUnverified: 'Unverified',
    statusOk: 'Verified',
    statusFailed: 'Failed',
    hostTag: 'host',
    globalKeyNote: 'prumo provides a key for this provider; add your own to run on it instead.',
    createSuccess: 'Connection added.',
    createError: 'Failed to add the connection',
    errorDetail: '{{error}}: {{reason}}',
    verifyAria: 'Verify connection',
    removeAria: 'Remove connection',
    removeTitle: 'Remove this connection?',
    removeDescription: 'The stored key is destroyed. Any run pinned to this connection stops working.',
    removeConfirm: 'Remove',
    removeSuccess: 'Connection removed.',
    removeError: 'Failed to remove the connection',
    verifySuccess: 'Connection verified.',
    verifyFailed: 'Verification failed: {{reason}}',
    verifyError: 'Failed to verify the connection',

    // --- Worklist gear picker ---
    gearAria: 'Your engine for new runs',
    gearLoading: 'Loading…',
    gearTooltip: 'Your engine for new runs: {{engine}}',
    projectDefaultLine: 'Project default: {{engine}}',
    lockedReason: 'A project manager locked this project to its default engine.',
    pickerLoadError: "Couldn't load the engines.",
    pickerNoMatch: 'No engines match.',
    tagYourKey: 'your key',
    tagProjectKey: 'project key',
    tagPrumo: 'prumo',
    tagNeedsKey: 'needs a key',
    needsKeyLink: 'Add a key under Integrations',
    retiredNote: 'This engine is no longer available. Pick a new model.',
    pickSuccess: 'Your engine for new runs is set.',
    pickError: 'Failed to set your engine',
    pickErrorNeedsKey: 'That engine needs a key. Add one under Integrations.',
    noHostsLink: 'Connect your own host under Integrations',
    hostGroupNote: 'Your host — runs on your connection',
    modeLabel: 'Mode',
    modeFast: 'Fast',
    modeVerified: 'Verified',
    followDefault: 'Follow the project default',

    // --- Project Settings → AI engine card + Shared keys ---
    cardTitle: 'AI engine',
    cardDescription: 'The project default for new runs. Members may pick their own engine unless locked.',
    cardLoadError: "Couldn't load the AI engine.",
    defaultLabel: 'Project default',
    lockLabel: 'Lock members to the project default',
    lockHint: 'Managers are never bound by the lock.',
    lockedBadge: 'Locked',
    defaultSaveSuccess: 'Project default updated.',
    defaultSaveError: 'Failed to update the project default',
    sharedTitle: 'Shared keys',
    sharedDescription:
        'Keys every member of this project runs on when they have none of their own. LlamaCloud here enables high-quality parsing for everyone.',
    sharedEmpty: 'No shared keys yet',
    sharedLoadError: "Couldn't load the shared keys.",
    sharedAddButton: 'Add shared key',
    sharedRemoveAria: 'Remove shared key',
    sharedRemoveTitle: 'Remove this shared key?',
    sharedRemoveDescription: 'Members without a key of their own lose this provider until another key is added.',
    sharedCreateSuccess: 'Shared key added.',
    sharedCreateError: 'Failed to add the shared key',
    sharedRemoveSuccess: 'Shared key removed.',
    sharedRemoveError: 'Failed to remove the shared key',
    servesLlm: 'LLM',
    servesParsing: 'parsing',
} as const;
