/**
 * UI copy for the per-project LLM engine chip + picker popover (§5, C1b).
 * English only.
 */
export const llmEngine = {
    chipAria: 'Extraction model',
    chipTooltip: 'Model used for AI extraction in this project',
    modeGroupAria: 'Extraction mode',
    modeFast: 'Fast',
    modeVerified: 'Verified',
    searchPlaceholder: 'Search models…',
    emptyResults: 'No models match.',
    providerOpenai: 'OpenAI',
    providerAnthropic: 'Anthropic',
    byokGroupNote: 'each user runs on their own key',
    lockedAddKeyCta: 'Add your key',
    lockedAddKeyItem: 'Add your key…',
    currentModelAria: 'Current model',
    attribution: 'Model changed by {{name}} · {{date}} · was {{model}}',
    attributionNoPrevious: 'Model changed by {{name}} · {{date}}',
    retiredNote:
        'This model is no longer in the catalogue. AI extraction is blocked — choose a new model.',
    alternatesTitle: 'Alternate engines',
    alternatesHelper:
        "Reviewers who can't run the default may run these instead — labeled as deviations.",
    alternatesEmpty: 'None — policy locked to the default engine.',
    alternatesRemoveAria: 'Remove alternate',
    alternatesPrimaryNote: 'Current default',
    alternatesByokWarn:
        "BYOK-only — won't unblock reviewers without their own key.",
    alternatesAddLabel: 'Add alternate',
    alternatesDoneLabel: 'Done',
    alternatesSaveSuccess: 'Alternates updated.',
    alternatesSaveError: 'Failed to update alternates',
    saveSuccess: 'Extraction model updated.',
    saveError: 'Failed to update the extraction model',
    // --- Custom endpoints (§5.2, C2) ---
    manageEndpoints: 'Manage custom endpoints…',
    endpointsTitle: 'Custom endpoints',
    endpointsDesc:
        'OpenAI-compatible endpoints this project runs on its own shared key.',
    endpointsEmpty: 'No custom endpoints yet.',
    endpointsLoading: 'Loading custom endpoints…',
    endpointsLoadError: "Couldn't load the custom endpoints. Try reopening this dialog.",
    endpointAddLabel: 'Add endpoint',
    endpointLabelLabel: 'Label',
    endpointBaseUrlLabel: 'Base URL',
    endpointBaseUrlHint: 'HTTPS only, and it must be reachable from the internet.',
    endpointKeyLabel: 'API key',
    endpointKeyKeptPlaceholder: 'Key stored — leave blank to keep',
    endpointKeyNewPlaceholder: 'Leave blank for a keyless endpoint',
    endpointKeyClearLabel: 'Clear the stored key',
    endpointModelsLabel: 'Allowed models',
    endpointModelsHint: 'Type a model id and press Enter.',
    endpointModelRemoveAria: 'Remove {{model}}',
    endpointModelsCount: 'Models: {{count}}',
    endpointSaveLabel: 'Save endpoint',
    endpointVerifyAria: 'Verify endpoint',
    endpointEditAria: 'Edit endpoint',
    endpointDeleteAria: 'Delete endpoint',
    endpointDeleteTitle: 'Delete this endpoint?',
    endpointDeleteDesc:
        'The stored key is destroyed with it. Any extraction pinned to this endpoint will stop working.',
    endpointDeleteConfirm: 'Delete endpoint',
    endpointStatusUnverified: 'Unverified',
    endpointStatusOk: 'Verified',
    endpointStatusFailed: 'Failed',
    endpointModeTool: 'Tool calling',
    endpointModeNative: 'Native JSON',
    endpointModePrompted: 'Prompted JSON',
    endpointPromptedWarn:
        'Prompted JSON only — this endpoint cannot back Verified mode.',
    endpointValidationLabelRequired: 'A label is required.',
    endpointValidationLabelMax: 'Keep the label under 80 characters.',
    endpointValidationBaseUrl: 'Enter a full URL, e.g. https://host/v1.',
    endpointCreateSuccess: 'Endpoint added.',
    endpointUpdateSuccess: 'Endpoint updated.',
    endpointDeleteSuccess: 'Endpoint removed.',
    endpointVerifyError: 'Failed to verify the endpoint',
    endpointGroupNote: 'Project endpoint — runs on its shared key',
    endpointPromptedGroupNote: 'Prompted JSON only — cannot back Verified mode',
    endpointPromptedBlocked:
        'Switch this project to Fast to extract with this model.',
} as const;
