/**
 * UI copy for navigation. English only.
 */
export const navigation = {
    notifications: 'Notifications',
    notificationsAriaBackgroundActive:
        'Notifications — background activity in progress',
    notificationsCleared: 'Notifications cleared',
    viewProject: 'View project',
    errorPrefix: 'Error',
    operationFailed: 'Operation failed',
    statusCompleted: 'Completed',
    statusInProgress: 'In progress',
    backgroundTask: 'Background task',
    defaultProjectName: 'Project',
    importingTo: 'Importing',
    importedSuccess: 'imported successfully',
    importError: 'Import error',
    importedCount: 'imported',
    updatedCount: 'updated',
    importComplete: 'Import complete!',
    taskCompleteSuccess: 'Task completed successfully!',
    timeNow: 'now',
    clear: 'Clear',
    timeAgo: 'ago',
    zoteroImport: 'Zotero import',
    noNotifications: 'No notifications',
    notifProjectCompletedTitle: 'Project completed',
    notifProjectCompletedMessage: 'The project was completed successfully',
    topbarBrand: 'Prumo',
    topbarBrandFull: 'Prumo',
    ariaOpenMenu: 'Open menu',
    ariaExpandSidebar: 'Expand sidebar',
    ariaCollapseSidebar: 'Collapse sidebar',
    ariaBack: 'Back',
    searchPlaceholder: 'Search…',
    ariaOpenSearch: 'Open search',
    sendFeedback: 'Send feedback',
    feedbackTitle: 'Send Feedback',
    feedbackDescription: 'Found a bug or have a suggestion? We would love to hear from you!',
    feedbackTypeLabel: 'Feedback type',
    feedbackTypeBug: 'Bug / Issue',
    feedbackTypeSuggestion: 'Improvement suggestion',
    feedbackTypeQuestion: 'Question',
    feedbackTypeOther: 'Other',
    feedbackSeverityLabel: 'Severity (optional)',
    feedbackSeverityPlaceholder: 'Select severity',
    feedbackSeverityLow: 'Low — Cosmetic issue',
    feedbackSeverityMedium: 'Medium — Feature affected',
    feedbackSeverityHigh: 'High — Cannot use',
    feedbackSeverityCritical: 'Critical — App crashed',
    feedbackDescriptionLabel: 'Description',
    feedbackDescriptionPlaceholder: 'Describe the issue or suggestion in detail...',
    feedbackDescriptionMin: 'Minimum 10 characters',
    feedbackDescriptionRemaining: 'remaining',
    feedbackDescriptionValid: 'Description valid. Technical context will be captured automatically.',
    feedbackSubmit: 'Send Feedback',
    feedbackSubmitting: 'Sending…',
} as const;

export type NavigationCopy = typeof navigation;
