/**
 * UI copy for navigation. English only.
 */

// Spelled out by both the attachment hint and its wrong-type error, so the
// accepted formats are written once rather than drifting between the two.
const FEEDBACK_FORMATS = 'PNG, JPEG, WebP, GIF, MP4, WebM or MOV';

export const navigation = {
    notifications: 'Notifications',
    notificationsAriaBackgroundActive:
        'Notifications — background activity in progress',
    notificationsAriaUnread: 'Notifications, {{count}} unread',
    notificationsCleared: 'Notifications cleared',
    viewProject: 'View project',
    errorPrefix: 'Error',
    operationFailed: 'Operation failed',
    statusCompleted: 'Completed',
    statusInProgress: 'In progress',
    backgroundTask: 'Background task',
    defaultProjectName: 'Project',
    importingTo: 'Importing',
    importedSuccess: 'imported successfully',
    importError: 'Import error',
    importedCount: 'imported',
    updatedCount: 'updated',
    removedCount: 'removed',
    reactivatedCount: 'reactivated',
    pdfsLabel: 'PDFs',
    unitItems: 'items',
    unitArticles: 'articles',
    defaultCollectionName: 'Collection',
    defaultTemplateName: 'Template',
    exportStatusCheckFailed: 'Failed to check export status',
    importComplete: 'Import complete!',
    taskCompleteSuccess: 'Task completed successfully!',
    timeNow: 'now',
    clear: 'Clear',
    timeAgo: 'ago',
    zoteroImport: 'Zotero import',
    noNotifications: 'No notifications',
    notifProjectCompletedTitle: 'Project completed',
    notifProjectCompletedMessage: 'The project was completed successfully',
    topbarBrand: 'Prumo',
    topbarBrandFull: 'Prumo',
    ariaOpenMenu: 'Open menu',
    ariaExpandSidebar: 'Expand sidebar',
    ariaCollapseSidebar: 'Collapse sidebar',
    ariaBack: 'Back',
    searchPlaceholder: 'Search…',
    ariaOpenSearch: 'Open search',
    sendFeedback: 'Send feedback',
    feedbackTitle: 'Send Feedback',
    feedbackDescription: 'Found a bug or have a suggestion? We would love to hear from you!',
    feedbackTypeLabel: 'Feedback type',
    feedbackTypeBug: 'Bug / Issue',
    feedbackTypeSuggestion: 'Improvement suggestion',
    feedbackTypeQuestion: 'Question',
    feedbackTypeOther: 'Other',
    feedbackSeverityLabel: 'Severity (optional)',
    feedbackSeverityPlaceholder: 'Select severity',
    feedbackSeverityLow: 'Low — Cosmetic issue',
    feedbackSeverityMedium: 'Medium — Feature affected',
    feedbackSeverityHigh: 'High — Cannot use',
    feedbackSeverityCritical: 'Critical — App crashed',
    feedbackDescriptionLabel: 'Description',
    feedbackDescriptionPlaceholder: 'Describe the issue or suggestion in detail...',
    feedbackDescriptionMin: 'Minimum 10 characters',
    feedbackDescriptionRemaining: 'remaining',
    feedbackDescriptionValid: 'Description valid. Technical context will be captured automatically.',
    feedbackSubmit: 'Send Feedback',
    feedbackSubmitting: 'Sending…',
    feedbackSummaryLabel: 'Summary (optional)',
    feedbackSummaryPlaceholder: 'One-line title',
    feedbackAttachLabel: 'Attachment (optional)',
    feedbackAttachChoose: 'Attach image or video',
    feedbackAttachNone: 'No file selected',
    feedbackAttachRemove: 'Remove',
    feedbackAttachNotice: `${FEEDBACK_FORMATS} — images up to 10 MB, videos up to 50 MB. Attachments are shared with the Prumo team in Linear.`,
    feedbackAttachWrongType: `That file type is not supported. Attach a ${FEEDBACK_FORMATS} file.`,
    feedbackAttachTooLarge: 'That file is too large. Images must be under 10 MB and videos under 50 MB.',
    feedbackAttachUploadFailed: 'Could not upload the attachment.',
    feedbackSuccessSent: 'Thanks — your report was sent.',
    viewsExtractionAria: 'Extraction views',
    viewsQualityAria: 'Quality assessment views',
    viewSwitcherTrigger: 'Switch view',
    sectionDescriptionExtraction: 'Extract structured data using standard templates',
    sectionDescriptionQuality: 'Assess article quality with PROBAST, QUADAS-2, and other risk-of-bias tools',
} as const;

