/**
 * UI copy for pages (routes). English only.
 */
export const pages = {
    notFoundTitle: '404',
    notFoundMessage: 'Oops! Page not found',
    notFoundBackHome: 'Return to Home',
    indexWelcome: 'Welcome to Your Blank App',
    indexSubtitle: 'Start building your amazing project here!',
    dashboardNewProject: 'New Project',
    dashboardAuthRequired: 'You must be signed in to create a project',
    dashboardErrorCreating: 'Error creating project',
    dashboardErrorProjectIdNotReturned: 'Error: Project ID was not returned',
    dashboardProjectCreated: 'Project created successfully!',
    dashboardUnexpectedError: 'Unexpected error creating project',
    dashboardCouldNotLoadProjects: 'Could not load projects.',
    dashboardStartFirstProject: 'Start with your first project',
    dashboardStartFirstProjectDesc: 'Create a project to import articles, extract data, and run systematic assessments.',
    dashboardCreateProject: 'Create Project',
    dashboardCreatedDate: 'Created',
    dashboardUpdatedPrefix: 'Updated',
    dashboardArchivedBadge: 'Archived',
    dashboardRowActionsAria: 'Project actions',
    dashboardArchive: 'Archive',
    dashboardRestore: 'Restore',
    dashboardArchived: 'Project archived',
    dashboardRestored: 'Project restored',
    dashboardArchiveDenied: 'You do not have permission to change this project',
    dashboardArchiveFailed: 'Could not update the project',
    dashboardSearchPlaceholder: 'Search projects…',
    dashboardFilterStatusAria: 'Filter projects by status',
    dashboardFilterActive: 'Active',
    dashboardFilterArchived: 'Archived',
    dashboardSortName: 'Name',
    dashboardSortUpdated: 'Updated',
    dashboardSortOrdering: 'Ordering',
    dashboardSortTooltip: 'Sort',
    dashboardSortAria: 'Sort options',
    dashboardNoMatches: 'No projects match your search',
    dashboardNoMatchesDesc: 'Try a different term, or switch the status filter.',
    dashboardClearSearch: 'Clear search',
    dashboardNoArchived: 'No archived projects',
    dashboardNoArchivedDesc: 'Projects you archive are kept here and can be restored at any time.',
    // ProjectView
    projectViewErrorLoading: 'Error loading project',
    projectViewLoading: 'Loading project...',
    projectViewProjectNotFound: 'Project not found',
    projectViewTabExtractionDesc: 'Extract structured data using standard templates',
    // ExtractionFullScreen
    extractionScreenLoading: 'Loading extraction interface...',
    extractionScreenErrorLoad: 'Error loading data',
    extractionScreenNoFieldsTitle: 'No fields for extraction',
    extractionScreenNoFieldsDesc: 'The template does not have any fields configured for data extraction.',
    extractionScreenToResolve: 'To resolve:',
    extractionScreenContactManager: 'Contact the project manager',
    extractionScreenRequestConfig: 'Request extraction fields to be configured',
    extractionScreenOrConfigureTemplate: 'Or configure a new template with fields',
    extractionScreenRunErrorTitle: 'Could not open this extraction',
    extractionScreenRunErrorDesc: 'The extraction session could not be loaded. This is usually temporary — please try again.',
    extractionScreenRetry: 'Try again',
    extractionScreenYou: 'You',
    extractionScreenParentNotFound: 'Parent instance not found. Create the parent section first.',
    extractionScreenInstanceAddedSuccess: 'added successfully',
    extractionScreenEntryKeyDuplicate: 'An entry with that key already exists here. Open it instead, or use a different key.',
    extractionScreenConfirmRemoveInstance: 'This instance has extracted values. Are you sure you want to remove it?',
    extractionScreenInstanceRemoved: 'Instance removed successfully',
    extractionScreenErrorRemoveInstance: 'Error removing instance',
  extractionScreenInstancePinned:
    'This item carries published values from a previous revision and cannot be removed.',
    extractionScreenCompleteRequiredFields: 'Complete all required fields before finalizing',
    extractionScreenErrorArticleNotFound: 'Error: Article data not found',
    extractionScreenErrorNoInstances: 'Error: No extraction instances found',
    extractionScreenFinalizeSuccess: 'Extraction completed successfully!',
    extractionScreenReopenSuccess: 'Extraction reopened for revision.',
    extractionScreenReopenError: 'Failed to reopen extraction',
    extractionScreenErrorUpdateStatus: 'Error updating instance status',
    extractionScreenErrorPermission: 'Permission error: You do not have permission to finalize this extraction',
    extractionScreenErrorRelatedData: 'Error: Related data not found. Reload the page and try again',
    extractionScreenNoInstanceUpdated: 'No instance was updated. Check permissions and try again',
    extractionScreenErrorFinalizeUnknown: 'Unknown error while finalizing extraction',
} as const;

