/**
 * UI copy for pages (routes). English only.
 */
export const pages = {
    notFoundTitle: '404',
    notFoundMessage: 'Oops! Page not found',
    notFoundBackHome: 'Return to Home',
    indexWelcome: 'Welcome to Your Blank App',
    indexSubtitle: 'Start building your amazing project here!',
    dashboardMyProjects: 'My Projects',
    dashboardNewProject: 'New Project',
    dashboardAuthRequired: 'You must be signed in to create a project',
    dashboardErrorCreating: 'Error creating project',
    dashboardErrorProjectIdNotReturned: 'Error: Project ID was not returned',
    dashboardProjectCreated: 'Project created successfully!',
    dashboardUnexpectedError: 'Unexpected error creating project',
    dashboardCouldNotLoadProjects: 'Could not load projects.',
    dashboardNoDescription: 'No additional description',
    dashboardStartFirstProject: 'Start with your first project',
    dashboardStartFirstProjectDesc: 'Create a project to import articles, extract data, and run systematic assessments.',
    dashboardCreateProject: 'Create Project',
    dashboardCreatedDate: 'Created',
    // ProjectView
    projectViewErrorLoading: 'Error loading project',
    projectViewLoading: 'Loading project...',
    projectViewProjectNotFound: 'Project not found',
    projectViewTabExtractionDesc: 'Extract structured data using standard templates',
    projectViewTabAssessmentDesc: 'Assess methodological quality of articles',
    projectViewImportArticles: 'Import',
    projectViewFromZotero: 'From Zotero',
    projectViewFromRisFile: 'From RIS file',
    projectViewAddArticle: 'Add',
    projectViewExportArticles: 'Export',
    // ExtractionFullScreen
    extractionScreenLoading: 'Loading extraction interface...',
    extractionScreenErrorLoad: 'Error loading data',
    extractionScreenNoFieldsTitle: 'No fields for extraction',
    extractionScreenNoFieldsDesc: 'The template does not have any fields configured for data extraction.',
    extractionScreenToResolve: 'To resolve:',
    extractionScreenContactManager: 'Contact the project manager',
    extractionScreenRequestConfig: 'Request extraction fields to be configured',
    extractionScreenOrConfigureTemplate: 'Or configure a new template with fields',
    extractionScreenProjectFallback: 'Project',
    extractionScreenYou: 'You',
    extractionScreenSelectModelFirst: 'Select a model before adding this section',
    extractionScreenParentNotFound: 'Parent instance not found. Create the parent section first.',
    extractionScreenInstanceAddedSuccess: 'added successfully',
    extractionScreenInstanceAlreadyExists: 'Instance already exists',
    extractionScreenErrorAddInstance: 'Error adding instance',
    extractionScreenConfirmRemoveInstance: 'This instance has extracted values. Are you sure you want to remove it?',
    extractionScreenInstanceRemoved: 'Instance removed successfully',
    extractionScreenErrorRemoveInstance: 'Error removing instance',
    extractionScreenCompleteRequiredFields: 'Complete all required fields before finalizing',
    extractionScreenErrorArticleNotFound: 'Error: Article data not found',
    extractionScreenErrorNoInstances: 'Error: No extraction instances found',
    extractionScreenFinalizeSuccess: 'Extraction completed successfully!',
    extractionScreenErrorUpdateStatus: 'Error updating instance status',
    extractionScreenErrorPermission: 'Permission error: You do not have permission to finalize this extraction',
    extractionScreenErrorRelatedData: 'Error: Related data not found. Reload the page and try again',
    extractionScreenNoInstanceUpdated: 'No instance was updated. Check permissions and try again',
    extractionScreenErrorFinalizeUnknown: 'Unknown error while finalizing extraction',
    // AssessmentFullScreen
    assessmentScreenCompleteRequired: 'Complete all required questions before finalizing',
    assessmentScreenSubmitSuccess: 'Assessment completed successfully!',
    assessmentScreenErrorFinalize: 'Error finalizing assessment',
    assessmentScreenErrorLoad: 'Error loading data',
    assessmentScreenBackToProject: 'Back to project',
    assessmentScreenNoInstrument: 'No instrument configured',
    assessmentScreenFinalizing: 'Finalizing...',
    assessmentScreenCompleteAssessment: 'Complete Assessment',
} as const;

export type PagesCopy = typeof pages;
