/**
 * UI copy for Integrations → Personal access tokens (spec §4.5, §4.7): the
 * token list, the create dialog and the one-time secret reveal. English only.
 * Task 4b adds the "Connect an AI agent" card's keys to this same file.
 */
export const personalAccessTokens = {
    groupTitle: 'Personal access tokens',
    groupHint: "Let an AI agent read and, with a read-write token, edit your projects through prumo's MCP server.",
    clientsNote: 'Works with agents that send an Authorization header, such as Claude Code or Cursor. Web chat apps (claude.ai, ChatGPT) are not supported.',
    readRecommendation: 'Use a read token unless the agent needs to edit.',
    listLoading: 'Loading tokens…',
    listEmpty: 'No tokens yet',
    listLoadError: "Couldn't load your tokens.",
    retry: 'Retry',
    createButton: 'Create token',
    createTitle: 'Create a personal access token',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Claude Code on my laptop',
    scopeLabel: 'Access',
    scopeRead: 'Read',
    scopeReadWrite: 'Read and write',
    expiryLabel: 'Expires in',
    expiryDays: '{{n}} days',
    createSubmit: 'Create',
    creating: 'Creating…',
    cancel: 'Cancel',
    createLimitError: '10 active tokens is the limit — revoke one first',
    createError: "Couldn't create the token.",
    revealTitle: 'Copy your token now',
    revealWarning: 'This token will not be shown again. Store it like a password.',
    copy: 'Copy',
    copied: 'Copied',
    copyTokenAria: 'Copy token',
    revealDone: 'I copied it',
    expiresOn: 'Expires {{date}}',
    lastUsed: 'Last used {{when}}',
    neverUsed: 'Never used',
    expiredBadge: 'Expired {{date}}',
    revokedBadge: 'Revoked {{date}}',
    revokeAria: 'Revoke token',
    revokeTitle: 'Revoke token?',
    revokeDescription: '"{{name}}" stops working immediately. Agents using it lose access.',
    revokeConfirm: 'Revoke',
    revoking: 'Revoking…',
    revokeSuccess: 'Token revoked',
    revokeError: "Couldn't revoke the token.",
} as const;
