/**
 * UI copy for Integrations → Personal access tokens (spec §4.5, §4.7): the
 * token list, the create dialog and the one-time secret reveal. English only.
 * Task 4b adds the "Connect an AI agent" card's keys to this same file.
 */
export const personalAccessTokens = {
    groupTitle: 'Personal access tokens',
    groupHint: "Let an AI agent read and, with a read-write token, edit your projects through prumo's MCP server.",
    clientsNote: 'Works with agents that send an Authorization header, such as Claude Code or Cursor. Web chat apps (claude.ai, ChatGPT) are not supported.',
    readRecommendation: 'Use a read token unless the agent needs to edit.',
    listLoading: 'Loading tokens…',
    listEmpty: 'No tokens yet',
    listLoadError: "Couldn't load your tokens.",
    retry: 'Retry',
    createButton: 'Create token',
    createTitle: 'Create a personal access token',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Claude Code on my laptop',
    scopeLabel: 'Access',
    scopeRead: 'Read',
    scopeReadWrite: 'Read and write',
    expiryLabel: 'Expires in',
    expiryDays: '{{n}} days',
    createSubmit: 'Create',
    creating: 'Creating…',
    cancel: 'Cancel',
    createLimitError: '10 active tokens is the limit — revoke one first',
    createError: "Couldn't create the token.",
    revealTitle: 'Copy your token now',
    revealWarning: 'This token will not be shown again. Store it like a password.',
    copy: 'Copy',
    copied: 'Copied',
    copyTokenAria: 'Copy token',
    tokenLabel: 'Your token',
    clientPickerAria: 'AI client',
    revealDone: 'I copied it',
    expiresOn: 'Expires {{date}}',
    lastUsed: 'Last used {{when}}',
    neverUsed: 'Never used',
    expiredBadge: 'Expired {{date}}',
    revokedBadge: 'Revoked {{date}}',
    revokeAria: 'Revoke token',
    revokeTitle: 'Revoke token?',
    revokeDescription: '"{{name}}" stops working immediately. Agents using it lose access.',
    revokeConfirm: 'Revoke',
    revoking: 'Revoking…',
    revokeSuccess: 'Token revoked',
    revokeError: "Couldn't revoke the token.",
    connectTitle: 'Connect an AI agent (MCP)',
    connectHint: 'Pick your agent for a ready-to-paste config.',
    docsLink: 'Docs',
    chipClaudeCode: 'Claude Code',
    chipCursor: 'Cursor',
    chipVsCode: 'VS Code / Copilot',
    chipGeminiCli: 'Gemini CLI',
    chipCodex: 'Codex',
    chipWindsurf: 'Windsurf',
    instructionClaudeCode: 'Run this in your terminal.',
    instructionCursor: 'In Cursor, open Settings > MCP > Add, or edit ~/.cursor/mcp.json directly.',
    instructionVsCode: 'In VS Code, run "MCP: Add Server" from the Command Palette, or edit .vscode/mcp.json directly.',
    instructionGeminiCli: 'Add this to ~/.gemini/settings.json, or run "gemini mcp add" with these values.',
    instructionCodex: 'Add this to ~/.codex/config.toml.',
    instructionWindsurf: 'In Windsurf, open Cascade > MCP Servers > Add, or edit ~/.codeium/windsurf/mcp_config.json directly.',
} as const;
