/**
 * UI copy for project area. English only.
 */
export const project = {
    addDialogTitle: 'Create New Project',
    addDialogDescription: 'Set up your systematic review project',
    addDialogNameRequired: 'Project name is required',
    addDialogNameMinLength: 'Name must be at least 3 characters',
    addDialogNameMaxLength: 'Name too long (max 100 characters)',
    addDialogDescriptionMaxLength: 'Description too long (max 500 characters)',
    addDialogNameLabel: 'Project Name',
    addDialogNamePlaceholder: 'e.g. Systematic Review on Type 2 Diabetes',
    addDialogDescriptionLabel: 'Description',
    addDialogOptional: '(optional)',
    addDialogDescriptionPlaceholder: 'Brief description of the review objective...',
    addDialogCreating: 'Creating…',
    addDialogCreateProject: 'Create Project',
    addDialogMoreDetailsAfter: 'You can add more details in project settings after creation.',

    // Project settings page
    settingsTitle: 'Project settings',
    settingsTitleUnsaved: 'Project settings · Unsaved',
    settingsLoading: 'Loading settings…',
    settingsSaveChanges: 'Save changes',
    settingsSaving: 'Saving…',
    settingsSaveSuccess: 'Changes saved successfully!',
    settingsSaveError: 'Error saving changes',
    settingsDiscardTitle: 'Discard unsaved changes?',
    settingsDiscardBody: 'Your edits to the review question have not been saved.',
    settingsDiscardCancel: 'Keep editing',
    settingsDiscardConfirm: 'Discard',
    tabBasic: 'Basic info',
    tabBasicDesc: 'Project name and description',
    tabReview: 'Review details',
    tabReviewDesc: 'Title, context, rationale and search strategy',
    tabReviewQuestion: 'Review question',
    tabReviewQuestionDesc: 'What the AI is told this review asks',
    tabAiEngine: 'AI engine',
    tabAiEngineDesc: 'Default model, mode and shared keys',
    tabTeam: 'Team',
    tabTeamDesc: 'Members and permissions',
    tabAdvanced: 'Advanced',
    tabAdvancedDesc: 'Additional settings',

    // BasicInfoSection
    basicProjectNameLabel: 'Project name',
    basicProjectNameHint: 'A short, descriptive name to identify your project.',
    basicProjectNamePlaceholder: 'e.g. Systematic Review - Type 2 Diabetes',
    basicDescriptionLabel: 'Description',
    basicDescriptionHint: 'An optional overview of what this project covers.',
    basicDescriptionPlaceholder: 'Briefly describe the objectives and scope of this systematic review...',
    basicReviewTypeLabel: 'Review type',

    // ReviewDetailsSection
    reviewCardGeneralTitle: 'General information',
    reviewTitleLabel: 'Review title',
    reviewTitleHint: 'The official title that will appear in publications and reports.',
    reviewTitlePlaceholder: 'Full, formal title of the systematic review',
    reviewConditionStudiedLabel: 'Condition studied',
    reviewConditionStudiedHint: 'The health condition or clinical phenomenon under investigation.',
    reviewConditionStudiedPlaceholder: 'e.g. Type 2 diabetes, Breast cancer, Hypertension',
    reviewContextLabel: 'Review context',
    reviewContextHint: 'Information about the scenario and relevance of the condition studied.',
    reviewContextPlaceholder: 'Describe the relevant clinical, epidemiological or social context...',
    reviewRationaleLabel: 'Review rationale',
    reviewRationaleHint: 'Explain the importance and need for this systematic review.',
    reviewRationalePlaceholder: 'Why is this review needed? What knowledge gap does it aim to fill?',
    reviewCardSearchTitle: 'Search strategy',
    reviewStrategyLabel: 'Strategy description',
    reviewStrategyHint: 'Document your databases, search terms and applied filters.',
    reviewStrategyPlaceholder: 'Databases: PubMed, Scopus\nPeriod: January 2010 - December 2023\nTerms: (diabetes OR "metabolic syndrome") AND (treatment OR therapy)',

    // PICOTS fields (ReviewDetailsSection + PICOTSItemEditor)
    picotsInclusionCriteriaLabel: 'Inclusion criteria',
    picotsExclusionCriteriaLabel: 'Exclusion criteria',
    picotsCriteriaOptional: 'Optional',
    picotsAddInclusionPlaceholder: 'Add inclusion criterion...',
    picotsAddExclusionPlaceholder: 'Add exclusion criterion...',

    // TeamMembersSection
    teamCardAddTitle: 'Add member',
    teamEmailPlaceholder: 'email@example.com',
    teamAddButton: 'Add',
    teamAdding: 'Adding…',
    teamUserMustBeRegistered: 'The user must be registered on the platform before being added.',
    teamCardMembersTitle: 'Current members',
    teamNoMembersYet: 'No members added yet. Use the form above to invite collaborators.',
    teamUserFallback: 'User',
    teamAvatarFallback: 'Avatar',
    teamAriaSaveChange: 'Save change',
    teamAriaCancel: 'Cancel',
    teamAriaEditRole: 'Edit role',
    teamAriaRemoveMember: 'Remove member',
    teamCardRolesTitle: 'Roles and permissions',
    teamCardRolesDesc: 'Each role has different levels of access to the project.',
    teamErrorLoadingMembers: 'Error loading members',
    teamErrorFindingUser: 'Error finding user',
    teamErrorOnlyManagersInvite: 'Only project managers can invite members',
    teamUserNotFound: 'User not found with this email',
    teamUserAlreadyMember: 'User is already a project member',
    teamMemberAddedAs: 'Member added as',
    teamErrorAddingMember: 'Error adding member',
    teamRoleChangedTo: 'Role changed to',
    teamErrorUpdatingRole: 'Error updating member role',
    teamConfirmRemoveMember: 'Are you sure you want to remove this member?',
    teamMemberRemoved: 'Member removed',
    teamErrorRemovingMember: 'Error removing member',
    // Shown both as the tooltip on a sole manager's disabled Remove button /
    // non-manager role options, and as the toast when the DB min-one-manager
    // guard (PM001) rejects a remove/demote that slipped past the UI.
    teamLastManagerGuard: 'A project must keep at least one manager',

    // AdvancedSettingsSection
    advancedCardKeywordsTitle: 'Review keywords',
    advancedCardKeywordsDesc: 'Key terms that describe the scope of the review.',
    advancedKeywordsPlaceholder: 'Enter a keyword...',
    advancedInclusionLabel: 'Inclusion criteria',
    advancedExclusionLabel: 'Exclusion criteria',
    advancedInclusionPlaceholder: 'e.g. Studies with adults over 18',
    advancedExclusionPlaceholder: 'e.g. Pre-clinical or in vitro studies',
    advancedAdditionalNotesLabel: 'Additional notes',
    advancedEligibilityNotesPlaceholder: 'Notes on eligibility criteria...',
    advancedCardStudyTypesTitle: 'Included study types',
    advancedCardStudyTypesDesc: 'Specify the study designs accepted in this review.',
    advancedStudyTypesPlaceholder: 'e.g. Randomized controlled trial, Cohort',
    advancedDesignNotesLabel: 'Design notes',
    advancedDesignNotesPlaceholder: 'Notes on accepted study types...',
    advancedCardDangerTitle: 'Danger zone',
    advancedDeleteProjectHeading: 'Delete project',
    advancedDeleteProjectWarning: 'This will permanently delete the project and all associated data (articles and extractions). It cannot be undone.',
    advancedDeleteProjectButton: 'Delete project',
    advancedConfirmDeleteTitle: 'Confirm project deletion',
    advancedConfirmDeleteDescription: 'You are about to permanently delete the project',
    advancedConfirmDeleteList: 'This will remove: articles, extractions, settings and history.',
    advancedConfirmDeleteFinal: 'This action cannot be undone.',
    advancedConfirmDeleteButton: 'Yes, delete project',
    advancedDeleting: 'Deleting…',
    advancedErrorDeleting: 'Error deleting project',
    advancedErrorDeletingMessage: 'Could not delete the project. Check your permissions.',
    advancedProjectDeleted: 'Project deleted successfully!',

    // Zotero integration (project settings)
    zoteroLoading: 'Loading…',
    zoteroConnected: 'Connected',
    zoteroUserId: 'User ID',
    zoteroLibraryType: 'Library type',
    zoteroLastSync: 'Last sync',
    zoteroTesting: 'Testing…',
    zoteroTestConnection: 'Test connection',
    zoteroDisconnect: 'Disconnect',
    zoteroDisconnectTitle: 'Disconnect from Zotero?',
    zoteroDisconnectDescription: 'This will remove your Zotero credentials. Already imported articles will not be affected. You will need to reconnect to perform new imports.',
    zoteroConfigureDesc: 'Configure Zotero to import articles.',
    zoteroGenerateApiKey: 'Generate API key',
    zoteroUserIDLabel: 'Zotero User ID',
    zoteroHowToFind: 'How to find?',
    zoteroUserIDHint: 'Your User ID appears on the API Keys settings page',
    zoteroUserIDPlaceholder: '123456',
    zoteroApiKeyLabel: 'API Key',
    zoteroApiKeyPermissions: 'Required permissions: "Allow library access" and "Allow file access"',
    zoteroLibraryTypeLabel: 'Library type',
    zoteroPersonalLibrary: 'Personal library',
    zoteroGroupLibrary: 'Group library',
    zoteroSaving: 'Saving…',
    zoteroConnect: 'Connect to Zotero',
    zoteroShow: 'Show',
    zoteroHide: 'Hide',
} as const;
