/**
 * UI copy for project area. English only.
 */
export const project = {
    addDialogTitle: 'Create New Project',
    addDialogDescription: 'Set up your systematic review project',
    addDialogNameRequired: 'Project name is required',
    addDialogNameMinLength: 'Name must be at least 3 characters',
    addDialogNameMaxLength: 'Name too long (max 100 characters)',
    addDialogDescriptionMaxLength: 'Description too long (max 500 characters)',
    addDialogNameLabel: 'Project Name',
    addDialogNamePlaceholder: 'e.g. Systematic Review on Type 2 Diabetes',
    addDialogDescriptionLabel: 'Description',
    addDialogOptional: '(optional)',
    addDialogDescriptionPlaceholder: 'Brief description of the review objective...',
    addDialogCreating: 'Creating…',
    addDialogCreateProject: 'Create Project',
    addDialogMoreDetailsAfter: 'You can add more details in project settings after creation.',

    // Project settings page
    settingsTitle: 'Project settings',
    settingsTitleUnsaved: 'Project settings · Unsaved',
    settingsLoading: 'Loading settings…',
    settingsSaveChanges: 'Save changes',
    settingsSaving: 'Saving…',
    settingsSaveSuccess: 'Changes saved successfully!',
    settingsSaveError: 'Error saving changes',
    tabBasic: 'Basic info',
    tabBasicDesc: 'Project name and description',
    tabReview: 'Review details',
    tabReviewDesc: 'PICOTS, search strategy and rationale',
    tabTeam: 'Team',
    tabTeamDesc: 'Members and permissions',
    tabAdvanced: 'Advanced',
    tabAdvancedDesc: 'Additional settings',

    // BasicInfoSection
    basicSectionTitle: 'Basic info',
    basicSectionDesc: 'Identify your project with a clear name and set the review type.',
    basicCardIdentification: 'Project identification',
    basicCardIdentificationDesc: 'This information helps you and your team identify the project.',
    basicProjectNameLabel: 'Project name',
    basicProjectNameHint: 'A short, descriptive name to identify your project.',
    basicProjectNamePlaceholder: 'e.g. Systematic Review - Type 2 Diabetes',
    basicDescriptionLabel: 'Description',
    basicDescriptionHint: 'An optional overview of what this project covers.',
    basicDescriptionPlaceholder: 'Briefly describe the objectives and scope of this systematic review...',
    basicReviewTypeCardTitle: 'Review type',
    basicReviewTypeCardDesc: 'Select the systematic review type to enable specific features.',
    basicReviewTypeLabel: 'Review type',
    basicPicotsEnabledTitle: 'PICOTS framework enabled',
    basicPicotsEnabledDesc: 'The Review details section will include the PICOTS framework with inclusion/exclusion criteria (Population, Index, Comparator, Outcomes, Timing, Setting).',

    // ReviewDetailsSection
    reviewSectionTitle: 'Review details',
    reviewSectionDesc: 'Configure the methodological aspects of your systematic review.',
    reviewCardGeneralTitle: 'General information',
    reviewCardGeneralDesc: 'Review title, condition studied and rationale.',
    reviewTitleLabel: 'Review title',
    reviewTitleHint: 'The official title that will appear in publications and reports.',
    reviewTitlePlaceholder: 'Full, formal title of the systematic review',
    reviewConditionStudiedLabel: 'Condition studied',
    reviewConditionStudiedHint: 'The health condition or clinical phenomenon under investigation.',
    reviewConditionStudiedPlaceholder: 'e.g. Type 2 diabetes, Breast cancer, Hypertension',
    reviewContextLabel: 'Review context',
    reviewContextHint: 'Information about the scenario and relevance of the condition studied.',
    reviewContextPlaceholder: 'Describe the relevant clinical, epidemiological or social context...',
    reviewRationaleLabel: 'Review rationale',
    reviewRationaleHint: 'Explain the importance and need for this systematic review.',
    reviewRationalePlaceholder: 'Why is this review needed? What knowledge gap does it aim to fill?',
    reviewCardSearchTitle: 'Search strategy',
    reviewCardSearchDesc: 'Databases, search terms and collection period.',
    reviewStrategyLabel: 'Strategy description',
    reviewStrategyHint: 'Document your databases, search terms and applied filters.',
    reviewStrategyPlaceholder: 'Databases: PubMed, Scopus\nPeriod: January 2010 - December 2023\nTerms: (diabetes OR "metabolic syndrome") AND (treatment OR therapy)',
    reviewCardPicotsTitle: 'PICOTS configuration',
    reviewCardPicotsDesc: 'PICOTS framework for predictive models — inclusion and exclusion criteria by component.',
    reviewPredictiveModelsBadge: 'Predictive models',
    reviewTimingLabel: 'Timing',
    reviewPredictionMomentLabel: 'Prediction moment',
    reviewPredictionMomentTooltip: 'Specify at which point in the disease or care course the prediction is made.',
    reviewPredictionMomentPlaceholder: 'Describe at which point in the disease/treatment course the prediction occurs...',
    reviewPredictionHorizonLabel: 'Prediction horizon',
    reviewPredictionHorizonTooltip: 'Define the future period being predicted (e.g. 30 days, 1 year).',
    reviewPredictionHorizonPlaceholder: 'Describe the temporal horizon of the prediction...',

    // PICOTS fields (ReviewDetailsSection + PICOTSItemEditor)
    picotsPopulationLabel: 'Population',
    picotsPopulationTooltip: 'Define the demographic and clinical characteristics of the target population. Consider age, health conditions, care setting and disease stage.',
    picotsPopulationPlaceholder: 'Describe the target population, relevant demographic and clinical characteristics...',
    picotsIndexModelsLabel: 'Index models / interventions',
    picotsIndexModelsTooltip: 'Specify the types of predictive models, algorithms or diagnostic tools to be included.',
    picotsIndexModelsPlaceholder: 'Predictive models, AI algorithms, diagnostic tools or interventions being evaluated...',
    picotsComparatorsLabel: 'Comparators',
    picotsComparatorsTooltip: 'Define which reference models, traditional clinical scores or gold standards will be accepted as valid comparators.',
    picotsComparatorsPlaceholder: 'Reference models, gold standard, usual care or controls used for comparison...',
    picotsOutcomesLabel: 'Outcomes',
    picotsOutcomesTooltip: 'List the outcomes of interest, including model performance metrics and clinical outcomes when available.',
    picotsOutcomesPlaceholder: 'Primary and secondary outcomes of interest (model performance, clinical impact, etc)...',
    picotsSettingLabel: 'Setting and intended use',
    picotsSettingTooltip: 'Describe where and how the model will be used in clinical practice. Consider care setting and available resources.',
    picotsSettingPlaceholder: 'Describe the clinical setting, application context and intended use of the model...',
    picotsInclusionCriteriaLabel: 'Inclusion criteria',
    picotsExclusionCriteriaLabel: 'Exclusion criteria',
    picotsAddInclusionPlaceholder: 'Add inclusion criterion...',
    picotsAddExclusionPlaceholder: 'Add exclusion criterion...',
    picotsHelpAria: 'Help',

    // TeamMembersSection
    teamSectionTitle: 'Team management',
    teamSectionDesc: 'Add collaborators and manage project access permissions.',
    teamCardAddTitle: 'Add member',
    teamCardAddDesc: 'Invite an existing user to join this project.',
    teamEmailPlaceholder: 'email@example.com',
    teamAddButton: 'Add',
    teamAdding: 'Adding…',
    teamUserMustBeRegistered: 'The user must be registered on the platform before being added.',
    teamCardMembersTitle: 'Current members',
    teamCardMembersDesc: 'All members with access to this project.',
    teamNoMembersYet: 'No members added yet. Use the form above to invite collaborators.',
    teamUserFallback: 'User',
    teamAvatarFallback: 'Avatar',
    teamAriaSaveChange: 'Save change',
    teamAriaCancel: 'Cancel',
    teamAriaEditRole: 'Edit role',
    teamAriaRemoveMember: 'Remove member',
    teamCardRolesTitle: 'Roles and permissions',
    teamCardRolesDesc: 'Each role has different levels of access to the project.',
    teamErrorLoadingMembers: 'Error loading members',
    teamErrorFindingUser: 'Error finding user',
    teamUserNotFound: 'User not found with this email',
    teamUserAlreadyMember: 'User is already a project member',
    teamMemberAddedAs: 'Member added as',
    teamErrorAddingMember: 'Error adding member',
    teamRoleChangedTo: 'Role changed to',
    teamErrorUpdatingRole: 'Error updating member role',
    teamConfirmRemoveMember: 'Are you sure you want to remove this member?',
    teamMemberRemoved: 'Member removed',
    teamErrorRemovingMember: 'Error removing member',

    // AdvancedSettingsSection
    advancedSectionTitle: 'Advanced settings',
    advancedSectionDesc: 'Set eligibility criteria, keywords and additional settings.',
    advancedCardBlindTitle: 'Blind assessment mode',
    advancedCardBlindDesc: 'Hide author information during assessment to reduce bias.',
    advancedEnableBlindLabel: 'Enable blind mode',
    advancedEnableBlindHint: 'When enabled, author names and affiliations will be hidden during assessment.',
    advancedCardKeywordsTitle: 'Review keywords',
    advancedCardKeywordsDesc: 'Key terms that describe the scope of the review.',
    advancedKeywordsPlaceholder: 'Enter a keyword...',
    advancedCardEligibilityTitle: 'Eligibility criteria',
    advancedCardEligibilityDesc: 'Define inclusion and exclusion criteria for studies.',
    advancedInclusionLabel: 'Inclusion criteria',
    advancedExclusionLabel: 'Exclusion criteria',
    advancedInclusionPlaceholder: 'e.g. Studies with adults over 18',
    advancedExclusionPlaceholder: 'e.g. Pre-clinical or in vitro studies',
    advancedAdditionalNotesLabel: 'Additional notes',
    advancedEligibilityNotesPlaceholder: 'Notes on eligibility criteria...',
    advancedCardStudyTypesTitle: 'Included study types',
    advancedCardStudyTypesDesc: 'Specify the study designs accepted in this review.',
    advancedStudyTypesPlaceholder: 'e.g. Randomized controlled trial, Cohort',
    advancedDesignNotesLabel: 'Design notes',
    advancedDesignNotesPlaceholder: 'Notes on accepted study types...',
    advancedCardDangerTitle: 'Danger zone',
    advancedCardDangerDesc: 'Irreversible actions that may permanently affect the project.',
    advancedDeleteProjectHeading: 'Delete project',
    advancedDeleteProjectWarning: 'This will permanently delete the project and all associated data (articles, extractions, assessments). It cannot be undone.',
    advancedDeleteProjectButton: 'Delete project',
    advancedConfirmDeleteTitle: 'Confirm project deletion',
    advancedConfirmDeleteDescription: 'You are about to permanently delete the project',
    advancedConfirmDeleteList: 'This will remove: articles, extractions, assessments, settings and history.',
    advancedConfirmDeleteFinal: 'This action cannot be undone.',
    advancedConfirmDeleteButton: 'Yes, delete project',
    advancedDeleting: 'Deleting…',
    advancedErrorDeleting: 'Error deleting project',
    advancedErrorDeletingMessage: 'Could not delete the project. Check your permissions.',
    advancedProjectDeleted: 'Project deleted successfully!',

    // Zotero integration (project settings)
    zoteroLoading: 'Loading…',
    zoteroConnected: 'Connected',
    zoteroUserId: 'User ID',
    zoteroLibraryType: 'Library type',
    zoteroLastSync: 'Last sync',
    zoteroTesting: 'Testing…',
    zoteroTestConnection: 'Test connection',
    zoteroDisconnect: 'Disconnect',
    zoteroDisconnectTitle: 'Disconnect from Zotero?',
    zoteroDisconnectDescription: 'This will remove your Zotero credentials. Already imported articles will not be affected. You will need to reconnect to perform new imports.',
    zoteroConfigureDesc: 'Configure Zotero to import articles.',
    zoteroGenerateApiKey: 'Generate API key',
    zoteroUserIDLabel: 'Zotero User ID',
    zoteroHowToFind: 'How to find?',
    zoteroUserIDHint: 'Your User ID appears on the API Keys settings page',
    zoteroUserIDPlaceholder: '123456',
    zoteroApiKeyLabel: 'API Key',
    zoteroApiKeyPermissions: 'Required permissions: "Allow library access" and "Allow file access"',
    zoteroLibraryTypeLabel: 'Library type',
    zoteroPersonalLibrary: 'Personal library',
    zoteroGroupLibrary: 'Group library',
    zoteroSaving: 'Saving…',
    zoteroConnect: 'Connect to Zotero',
    zoteroShow: 'Show',
    zoteroHide: 'Hide',
} as const;
