/**
 * UI copy for user area (settings: profile, security, integrations, API keys). English only.
 */
export const user = {
    // Settings page
    settingsTitle: 'Settings',
    settingsAriaSections: 'Settings sections',
    ariaGoBack: 'Go back',
    tabProfile: 'Profile',
    tabSecurity: 'Security',
    tabIntegrations: 'Integrations',
    tabProfileDesc: 'Personal information and avatar',
    tabSecurityDesc: 'Password and authentication',
    tabIntegrationsDesc: 'External services and APIs',

    // Profile
    profileTitle: 'Profile',
    profileDescription: 'Manage your personal information',
    profileCardTitle: 'Personal information',
    profileCardDescription: 'Your account details and display name.',
    profilePicture: 'Profile picture',
    profileUploadComingSoon: 'Upload coming soon',
    profileEmailLabel: 'Email',
    profileEmailHint: 'Managed by the authentication system — cannot be changed.',
    profileEmailAria: 'Email (read-only)',
    profileFullNameLabel: 'Full name',
    profileFullNameHint: 'Your full name as shown to others.',
    profileFullNamePlaceholder: 'Your full name',
    profileSaving: 'Saving…',
    profileSaveChanges: 'Save changes',
    profileNameRequired: 'Name is required',
    profileNameMaxLength: 'Name too long (max 100 characters)',
    profileErrorNotAuthenticated: 'User not authenticated',
    profileErrorLoading: 'Error loading profile',
    profileUpdated: 'Profile updated successfully!',
    profileErrorSaving: 'Error saving profile',

    // Security
    securityTitle: 'Security',
    securityDescription: 'Manage your password and security settings',
    securityCardTitle: 'Change password',
    securityCardDescription: 'Set a new password for your account.',
    securityAlertDescription: 'Choose a strong password with at least 8 characters, including uppercase, lowercase letters and numbers.',
    securityNewPasswordLabel: 'New password',
    securityNewPasswordHint: 'At least 8 characters, with uppercase, lowercase and numbers.',
    securityNewPasswordPlaceholder: 'Enter your new password',
    securityConfirmLabel: 'Confirm new password',
    securityConfirmHint: 'Re-enter the new password.',
    securityConfirmPlaceholder: 'Confirm your new password',
    securityPasswordStrength: 'Password strength:',
    securityStrengthWeak: 'Weak',
    securityStrengthMedium: 'Medium',
    securityStrengthStrong: 'Strong',
    securityAriaHidePassword: 'Hide password',
    securityAriaShowPassword: 'Show password',
    securityAriaHideConfirm: 'Hide confirmation',
    securityAriaShowConfirm: 'Show confirmation',
    securityPasswordsMatch: 'Passwords match',
    securityPasswordsDoNotMatch: 'Passwords do not match',
    securityUpdating: 'Updating…',
    securityChangePassword: 'Change password',
    securityPasswordChanged: 'Password changed successfully!',
    securityErrorChanging: 'Error changing password',
    securitySchemaMin: 'Password must be at least 8 characters',
    securitySchemaUppercase: 'Password must contain at least one uppercase letter',
    securitySchemaLowercase: 'Password must contain at least one lowercase letter',
    securitySchemaNumber: 'Password must contain at least one number',
    securitySchemaConfirm: 'Confirm your new password',
    securitySchemaMismatch: 'Passwords do not match',

    // Integrations
    integrationsApiKeysTitle: 'API keys',
    integrationsApiKeysDescription: 'Use your own API keys for AI providers. Keys are encrypted and never shared.',
    integrationsZoteroTitle: 'Zotero',
    integrationsZoteroDescription: 'Import articles from your Zotero library.',

    // API keys
    apiKeysSessionExpired: 'Session expired. Please sign in again.',
    apiKeysErrorLoading: 'Error loading API keys',
    apiKeysEnterKey: 'Enter the API key',
    apiKeysInvalidKey: 'Invalid API key',
    apiKeysAddedValidated: 'API key added and validated successfully!',
    apiKeysAddedPending: 'API key added. Validation pending.',
    apiKeysErrorAdding: 'Error adding API key',
    apiKeysSetDefault: 'API key set as default',
    apiKeysErrorSetDefault: 'Error setting as default',
    apiKeysDeactivated: 'API key deactivated',
    apiKeysErrorDeactivating: 'Error deactivating',
    apiKeysRemoved: 'API key removed',
    apiKeysErrorRemoving: 'Error removing API key',
    apiKeysValid: 'API key valid!',
    apiKeysValidationPending: 'Validation pending',
    apiKeysErrorValidating: 'Error validating API key',
    apiKeysBadgeValid: 'Valid',
    apiKeysBadgeInvalid: 'Invalid',
    apiKeysBadgePending: 'Pending',
    apiKeysLoading: 'Loading…',
    apiKeysEncryptedNote: 'Keys are encrypted and never exposed.',
    apiKeysAddButton: 'Add API Key',
    apiKeysProviderLabel: 'Provider',
    apiKeysProviderPlaceholder: 'Select provider',
    apiKeysHowToGet: 'How to get an API key?',
    apiKeysKeyLabel: 'API Key',
    apiKeysKeyPlaceholder: 'sk-...',
    apiKeysNameLabel: 'Name (optional)',
    apiKeysNamePlaceholder: 'e.g. Personal key, Work key',
    apiKeysSetAsDefault: 'Set as default',
    apiKeysValidateBeforeSave: 'Validate before saving',
    apiKeysSaving: 'Saving…',
    apiKeysNoKeys: 'No API keys configured',
    apiKeysNoKeysHint: 'Add your own keys to use AI models',
    apiKeysCreatedOn: 'Created on',
    apiKeysLastUsed: 'Last used',
    apiKeysKeyLabelFallback: 'Key',
    apiKeysTitleRevalidate: 'Revalidate',
    apiKeysTitleSetDefault: 'Set as default',
    apiKeysTitleRemove: 'Remove',
    apiKeysRemoveTitle: 'Remove API Key',
    apiKeysRemoveDescription: 'Are you sure you want to remove this API key? This action cannot be undone.',
} as const;

export type UserCopy = typeof user;
