"""Version note for template publishes (slice B-9b2b).

``note`` on extraction_template_versions records WHY a version was
published, in the publisher's words. Optional at publish time, so
nullable — and every row that existed before this column has no answer.

Deliberately version METADATA rather than part of the ``schema`` JSONB
snapshot: the snapshot is the frozen structure runs are pinned to, and
``TemplateVersionService.republish`` short-circuits on
``current.schema_ == snapshot``. Folding prose into that payload would
make two structurally identical versions compare unequal and spawn a
version row per note edit.

Hand-written rather than autogenerated: ``alembic revision
--autogenerate`` against this schema emits ~180 spurious operations
(FK re-creations, TEXT<->String churn, table comments) because
baseline_v1.sql created those objects outside the model metadata. Only
the one column below is real.

Nothing reads the column yet — the Publish flow writes it here and
History (B-9e) renders it.

Revision ID: 0052_template_version_note
Revises: 0051_entity_entry_label
"""

import sqlalchemy as sa

from alembic import op

revision = "0052_template_version_note"
down_revision = "0051_entity_entry_label"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "extraction_template_versions",
        sa.Column("note", sa.Text(), nullable=True),
        schema="public",
    )


def downgrade() -> None:
    op.drop_column("extraction_template_versions", "note", schema="public")
