"""
Pydantic Schemas.

Exporta todos os schemas para facilitar importação.
"""

from app.schemas.article import (
    ArticleCreate,
    ArticleFileCreate,
    ArticleFileResponse,
    ArticleListItem,
    ArticleListResponse,
    ArticleResponse,
    ArticleSearchRequest,
    ArticleUpdate,
    ConfirmUploadRequest,
    ExtractTextRequest,
    ExtractTextResponse,
    UploadUrlRequest,
    UploadUrlResponse,
)
from app.schemas.assessment import (
    AIAssessmentRequest,
    AIAssessmentResponse,
    AIAssessmentResult,
    ArticleAssessmentSummary,
    AssessmentInstrumentSchema,
    AssessmentItemSchema,
    AssessmentResponse,
    BatchAIAssessmentRequest,
    BatchAIAssessmentResult,
    BatchItemResult,
    DomainSummary,
    EvidencePassage,
    ItemResponse,
    ReviewAIAssessmentRequest,
    SaveAssessmentRequest,
)
from app.schemas.common import (
    ApiResponse,
    ErrorDetail,
    HealthResponse,
    PaginatedResponse,
)
from app.schemas.extraction import (
    BatchSectionResult,
    CreateInstanceRequest,
    ExtractionEntityTypeSchema,
    ExtractionFieldSchema,
    ExtractionOptions,
    ExtractionTemplateSchema,
    FieldSuggestion,
    IdentifiedModel,
    InstanceResponse,
    ModelExtractionRequest,
    ModelExtractionResult,
    ReviewSuggestionRequest,
    SaveValueRequest,
    SectionExtractionRequest,
    SingleSectionResult,
    SuggestionResponse,
    ValueResponse,
)
from app.schemas.project import (
    AddMemberRequest,
    MemberResponse,
    PICOTSConfig,
    ProjectCreate,
    ProjectListItem,
    ProjectListResponse,
    ProjectResponse,
    ProjectSettings,
    ProjectUpdate,
    TimingConfig,
    UpdateMemberRequest,
)
from app.schemas.zotero import (
    DownloadAttachmentRequest,
    DownloadAttachmentResponse,
    FetchAttachmentsRequest,
    FetchAttachmentsResponse,
    FetchItemsRequest,
    FetchItemsResponse,
    ImportResult,
    ImportToProjectRequest,
    ImportToProjectResponse,
    ListCollectionsResponse,
    SaveCredentialsRequest,
    SaveCredentialsResponse,
    TestConnectionResponse,
    ZoteroAttachment,
    ZoteroCollection,
    ZoteroCreator,
    ZoteroItem,
    ZoteroItemData,
)

__all__ = [
    # Common
    "ApiResponse",
    "ErrorDetail",
    "HealthResponse",
    "PaginatedResponse",
    # Zotero
    "SaveCredentialsRequest",
    "SaveCredentialsResponse",
    "FetchItemsRequest",
    "FetchItemsResponse",
    "FetchAttachmentsRequest",
    "FetchAttachmentsResponse",
    "DownloadAttachmentRequest",
    "DownloadAttachmentResponse",
    "ImportToProjectRequest",
    "ImportToProjectResponse",
    "ImportResult",
    "ZoteroItem",
    "ZoteroItemData",
    "ZoteroCreator",
    "ZoteroCollection",
    "ZoteroAttachment",
    "ListCollectionsResponse",
    "TestConnectionResponse",
    # Extraction
    "SectionExtractionRequest",
    "SingleSectionResult",
    "BatchSectionResult",
    "ModelExtractionRequest",
    "ModelExtractionResult",
    "IdentifiedModel",
    "ExtractionOptions",
    "FieldSuggestion",
    "ExtractionTemplateSchema",
    "ExtractionEntityTypeSchema",
    "ExtractionFieldSchema",
    "CreateInstanceRequest",
    "InstanceResponse",
    "SaveValueRequest",
    "ValueResponse",
    "SuggestionResponse",
    "ReviewSuggestionRequest",
    # Assessment
    "AIAssessmentRequest",
    "AIAssessmentResponse",
    "AIAssessmentResult",
    "BatchAIAssessmentRequest",
    "BatchAIAssessmentResult",
    "BatchItemResult",
    "EvidencePassage",
    "AssessmentInstrumentSchema",
    "AssessmentItemSchema",
    "SaveAssessmentRequest",
    "AssessmentResponse",
    "ReviewAIAssessmentRequest",
    "DomainSummary",
    "ArticleAssessmentSummary",
    "ItemResponse",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListItem",
    "ProjectListResponse",
    "ProjectSettings",
    "PICOTSConfig",
    "TimingConfig",
    "AddMemberRequest",
    "UpdateMemberRequest",
    "MemberResponse",
    # Article
    "ArticleCreate",
    "ArticleUpdate",
    "ArticleResponse",
    "ArticleListItem",
    "ArticleListResponse",
    "ArticleSearchRequest",
    "ArticleFileCreate",
    "ArticleFileResponse",
    "UploadUrlRequest",
    "UploadUrlResponse",
    "ConfirmUploadRequest",
    "ExtractTextRequest",
    "ExtractTextResponse",
]
